### ISSUE TITLE
attach is causing an "Invalid Argument" exception from os.read

### ISSUE THREAD

**Issue by mmerickel** [docker/docker-py#1211]
``` python
stream = client.attach(container, stream=True, stdout=True, stderr=True)
for chunk in stream:
    pass
```

Results in:

```
  File "/Users/michael/work/oss/marina/marina/build.py", line 695, in watcher
    for chunk in stream:
  File ".venv/lib/python3.5/site-packages/docker/utils/socket.py", line 67, in frames_iter
    yield read(socket, n)
  File ".venv/lib/python3.5/site-packages/docker/utils/socket.py", line 25, in read
    return os.read(socket.fileno(), n)
OSError: [Errno 22] Invalid argument
```

Using docker-py 1.10.2 on OS X 10.11.6 with docker for mac 1.12.0-rc3. Reverting to 1.9.0 fixes the issue.

**Comment by shin-** [comment]
Tentatively using the python3 label, but I'm not sure yet what we're dealing with here. We did change the log streaming code recently so it's possible we missed something.

**Comment by mmerickel** [comment]
I actually got a different error when trying this on Python 2.7.12, but amusingly in the same area. :-)

```
Traceback (most recent call last):
  File "/Users/michael/work/oss/marina/marina/build.py", line 697, in watcher
    if encoding:
  File ".venv/lib/python2.7/site-packages/docker/utils/socket.py", line 67, in frames_iter
    yield read(socket, n)
  File ".venv/lib/python2.7/site-packages/docker/utils/socket.py", line 24, in read
    return socket.recv(n)
OverflowError: signed integer is greater than maximum
```

**Comment by shin-** [comment]
Hm, interesting. Might be the same underlying issue presented differently. I'll look into it. Thanks for the report!

**Comment by TomasTomecek** [comment]
> docker for mac 1.12.0-rc3

Could try with latest stable release?

**Comment by mmerickel** [comment]
I was reproducing it last night with 1.12.2-rc1-beta27. Docker for mac has not had a stable release so testing with that would be difficult.
