### ISSUE TITLE
Install Failures on OS X and Ubuntu Trusty - no .dist-info directory

### ISSUE THREAD

**Issue by darkn3rd** [docker/docker-py#1229]
Attempted to `pip install docker-py` and it failed.  I use this in Ansible.  I do not have problems installing other python packages, just seems this one casuses a problem.

### RESULTS

```
Collecting docker.py
  Using cached docker_py-1.10.3-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker.py)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from docker.py)
Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16; python_version < "3.3" in /usr/local/lib/python2.7/site-packages (from docker.py)
Requirement already satisfied (use --upgrade to upgrade): requests<2.11,>=2.5.2 in /usr/local/lib/python2.7/site-packages (from docker.py)
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/local/lib/python2.7/site-packages (from docker.py)
Requirement already satisfied (use --upgrade to upgrade): docker-pycreds>=0.2.1 in /usr/local/lib/python2.7/site-packages (from docker.py)
Installing collected packages: docker.py
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 348, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: docker.py .dist-info directory not found
```

### PACKAGE INFO

```
$ pip freeze | grep docker-py && python --version && docker version
docker-py==1.10.3
docker-pycreds==0.2.1
Python 2.7.12
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Comment by shin-** [comment]
@darkn3rd Can you try upgrading `pip` and try again? Another source I found suggested using `--no-use-wheel` when running `pip install`.

**Comment by darkn3rd** [comment]
I tried to upgrade, so removed it and tried to install.  Same result.

Using `--no-use--wheel` yields this:

```
$ pip install --no-use-wheel docker.py
DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
Collecting docker.py
  Could not find a version that satisfies the requirement docker.py (from versions: )
No matching distribution found for docker.py
```

**Comment by darkn3rd** [comment]
I have found that this also reproduces on Ubuntu 14.04 Trusty Tahr

```bash
easy_install pip
pip install docker.py
...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 348, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: docker.py .dist-info directory not found
...
```

Full Results including traceback: https://gist.github.com/darkn3rd/3528b5fd01687406ae5953a297780a9a

Also: 
```
pip freeze | grep docker-py && python --version && docker version
docker-py==1.10.3
docker-pycreds==0.2.1
Python 2.7.6
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Comment by shin-** [comment]
The name of the package is `docker-py`, not `docker.py`.

**Comment by darkn3rd** [comment]
LOL
