### ISSUE TITLE
Intermittent hang during exec_start

### ISSUE THREAD

**Issue by leth** [docker/docker-py#1269]
We intermittently see a hang in our system when using exec (possibly near container shutdown) and I'm not sure whether to blame the client or engine.
I've managed to create a test harness though!

I once had it hang after 9 iterations, but another time it was ~60, so quite variable.

Here's my test harness:
```python
import time
import itertools
import docker

docker_client = docker.Client(timeout=None)
for i in itertools.count():
    print(i, time.time())
    container = docker_client.create_container('busybox:latest', 'sh -c "sleep 0.55"', )
    docker_client.start(container, network_mode='host')
    print(docker_client.exec_start(docker_client.exec_create(container, 'sh -c "killall sleep"')))
    running = True
    for j in itertools.count():
        running = docker_client.inspect_container(container)['State']['Running']
        if not running:
            break
    docker_client.remove_container(container)
```

When I kill it, it's stuck here:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(docker_client.exec_start(docker_client.exec_create(container, 'sh -c "killall sleep"')))
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/docker/api/exec_api.py", line 70, in exec_start
    self._url('/exec/{0}/start', exec_id), data=data, stream=stream
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/docker/client.py", line 198, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/docker/client.py", line 136, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/sessions.py", line 628, in send
    r.content
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/leth/src/2016/ttvm/dev/virtualenvs/ttvm/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

`docker info`:
```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 178
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 477
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.679 GiB
Name: kohlenstoff
ID: 2TCK:YUZU:NWIV:QETB:XR42:UC3N:SNR6:MP4E:UAZ3:VT6C:TMKA:UWIS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by TomasTomecek** [comment]
This could be a race condition in engine.

Could you please reproduce with docker client so we can be sure where the issue is?

**Comment by leth** [comment]
Looks like it's an engine bug, I'll reopen over there!

Here's the subprocess version:
```
import time
import itertools
from subprocess import check_output, CalledProcessError


def docker(*args):
    return check_output(('docker', ) + args)

for i in itertools.count():
    print(i, time.time())
    container = docker(
        'run', '--net=host', '-d', 'busybox:latest', 'sh', '-c', 'sleep 0.55'
    ).strip()
    try:
        docker('exec', container, 'sh', '-c', 'killall sleep || true')
    except CalledProcessError as e:
        pass
    docker('wait', container)
    docker('rm', container)
```
