### ISSUE TITLE
Error when passing env variables

### ISSUE THREAD

**Issue by jocelynthode** [docker/docker-py#1291]
```
docker-py==1.10.5
docker-pycreds==0.2.1
Python 3.5.2
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64
```

When trying to pass environment variables in a container_spec to a service as a dict (like the doc says), We get the following error:

```Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/services/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_benchmarks.py", line 95, in <module>
    mounts=[types.Mount(target='/data', source='/home/cyborg/data')])
  File "./run_benchmarks.py", line 25, in create_service
    cli.create_service(task_tmpl, name=service_name, mode={'Replicated': {'Replicas': replicas}})
  File "/usr/lib/python3.5/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/docker/api/service.py", line 33, in create_service
    self._post_json(url, data=data, headers=headers), True
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"json: cannot unmarshal object into Go value of type []string"}'")
```
Which indicates we need to pass a list of strings. And indeed passing a list of strings works.

Either the doc should be corrected or a conversion should be made

**Comment by shin-** [comment]
Thank you for the report! See discussion in #1264 . I'll close this as a duplicate.
