### ISSUE TITLE
docker.models package is missing in setup.py

### ISSUE THREAD

**Issue by kinghuang** [docker/docker-py#1311]
#1186 merged in a new user-focused API. [`docker/client.py`](/docker/docker-py/blob/master/docker/client.py) makes several imports `from .models. …`, but this isn't part of the packages specified in [`setup.py`](/docker/docker-py/blob/master/setup.py). As a result, `ImportError`s occur.

Example ImportError running docker-compose with @c66c7f8 installed.

```
$ docker-compose pull
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/site-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 3, in <module>
    from .client import Client, from_env
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 2, in <module>
    from .models.containers import ContainerCollection
ImportError: No module named models.containers
```

**Comment by bfirsh** [comment]
Fixed in #1305.

master is a bit unstable at the moment - it's recommended you pin to a version. :)
