### ISSUE TITLE
put_archive fails for client using unix socket as base_url

### ISSUE THREAD

**Issue by dimaspivak** [docker/docker-py#1348]
```
docker-py==1.10.6
docker-pycreds==0.2.1
Python 3.5.2
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```
On an Ubuntu 16.04 host running Docker, I've found that calls to `put_archive` fail with an `APIError` complaining of the path param missing:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/containers/47b3708a535dd92a4829df692d5173186f38b40424070e4b829f367de050a45f/archive

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/testframework/quick_test.py", line 10, in <module>
    data_collector.start()
  File "/root/testframework/testframework/sdc.py", line 111, in start
    client.put_archive(container=sdc_container['Id'], path='/resources/', data=tarstream) 
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/container.py", line 284, in put_archive
    self._raise_for_status(res)
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"bad parameter: \'path\' cannot be empty"}'")
```
I've specified the parameter in my code, however:
```
client.put_archive(container=sdc_container['Id'], path='/resources', data=tarstream)
```
After hitting my head for a few hours, I tried changing the `base_url` to point to `0.0.0.0:2375` and suddenly everything succeeded.

Any idea what might be going on with doing this `PUT` over Unix sockets?

**Comment by dimaspivak** [comment]
Created a quick test to repro what I'm seeing. For this to work, run on a machine whose Docker daemon is listening both the Unix socket and 0.0.0.0:2375 (change port accordingly, if needed):
```
import io
import tarfile

import docker

# Create simple tarstream.
file_contents = 'Random text!'

tarstream = io.BytesIO()
with tarfile.open(fileobj=tarstream, mode='w') as tarfile_:
    encoded_file_contents = file_contents.encode()
    tarinfo = tarfile.TarInfo('file.txt')
    tarinfo.size = len(encoded_file_contents)
    tarfile_.addfile(tarinfo, io.BytesIO(encoded_file_contents))

# We're at the end of the tarstream, go back to the beginning.
tarstream.seek(0)

for base_url in ('unix://var/run/docker.sock', '0.0.0.0:2375'):
    print('Creating client with base_url of {0}'.format(base_url))
    client = docker.Client(base_url=base_url)
    test_container = client.create_container(image='alpine:latest', command='/bin/true')
    print('Successfully created container with Id {0}'.format(test_container['Id']))
    
    print('Trying to put archive (base_url={0})...'.format(base_url))
    try:
        client.put_archive(container=test_container['Id'], path='/', data=tarstream)
        print("Didn't see exception while putting archive with base_url {0}!".format(base_url))
    except Exception as e:
        print('Saw exception {0}...'.format(e))
```
When running, I get the following output:
```
root@ip-172-31-1-222:~# python3 put_archive_test.py 
Creating client with base_url of unix://var/run/docker.sock
Successfully created container with Id 8dc5197db4bbe11a95afcfac7ca1fe7cc461731acf649d73867919b8ebd98d54
Trying to put archive (base_url=unix://var/run/docker.sock)...
Saw exception 400 Client Error: Bad Request ("b'{"message":"bad parameter: \'path\' cannot be empty"}'")...
Creating client with base_url of 0.0.0.0:2375
Successfully created container with Id ff5afb6f55fdfb4cc82d70f882aa7d7db74744f46e2d061b92c4c27e5ac22d69
Trying to put archive (base_url=0.0.0.0:2375)...
Didn't see exception while putting archive with base_url 0.0.0.0:2375!
```

**Comment by dimaspivak** [comment]
Bah, looks like this one is caused by #1321. Downgrading to requests 2.12.1 fixed things; debug logs showed that params weren't being added to the endpoint being hit in the case of the Unix socket, but were for the TCP one.

Bah. :)
