### ISSUE TITLE
TypeError: services() got an unexpected keyword argument 'name' (or 'id')

### ISSUE THREAD

**Issue by laugimethods** [docker/docker-py#1367]
The documentation says that it is possible to filter the services by name or by id (https://docker-py.readthedocs.io/en/stable/services.html#docker.models.services.ServiceCollection.list).

However, that functionality fails (forgive me if the syntax I'm using is wrong):
```
>>> client.services.list(name="my-name")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/anaconda3/lib/python3.5/site-packages/docker/models/services.py", line 169, in list
    for s in self.client.api.services(**kwargs)
  File "xxx/anaconda3/lib/python3.5/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
TypeError: services() got an unexpected keyword argument 'name'
```

Same with 'id'.

FYI, using docker-2.0.0:
```
pip install docker
  Downloading docker-2.0.0-py2.py3-none-any.whl (95kB)
```

**Comment by shin-** [comment]
The correct syntax would be the following:
```python
client.services.list(filters={ 'name': 'my-name' })
```

**Comment by pipozzz** [comment]
```
services = self.client.services.list(filters={'name': 'test'})
```
and getting all services instead of service with name test
