### ISSUE TITLE
Converting port binding issue

### ISSUE THREAD

**Issue by twllight** [docker/docker-py#1435]
Hello,

I'm upgrading  my applications which use the docker python SDK and have run into a particular issue which I cant seem to get around:

When creating a Host config:

```
        host_config  = HostConfig(  version        = ship_opts['api_version'],
                                    privileged     = True,
                                    dns            = ship_opts['cont_dns'],
                                    dns_search     = ship_opts['cont_search'],
                                    mem_limit      = ship_opts['cont_memory'][0],
                                    port_bindings  = {5520: 5520, 7088: 7088, 8088: 8088, 5020: 5020, 8181: 8181},
                                    network_mode   = ship_opts['cont_network_type'],
                                    binds          = mount_points,
                                    restart_policy = {"MaximumRetryCount": 5, "Name": "always"})
```
I get the following error:
```
Traceback (most recent call last):
  File "./swarm-deploy.py", line 796, in <module>
    main()
  File "./swarm-deploy.py", line 789, in main
    container_ports,ship_id,container_inspection = create_api_container(docker, **ship_opts)
  File "./swarm-deploy.py", line 531, in create_api_container
    tty         = True)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 696, in create
    create_kwargs = _create_container_args(kwargs)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 872, in _create_container_args
    create_kwargs['host_config'] = HostConfig(**host_config_kwargs)
  File "/usr/lib/python2.7/site-packages/docker/types/containers.py", line 253, in __init__
    self['PortBindings'] = convert_port_bindings(port_bindings)
  File "/usr/lib/python2.7/site-packages/docker/utils/utils.py", line 316, in convert_port_bindings
    for k, v in six.iteritems(port_bindings):
  File "/usr/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'
```
My host_config seems to be correct, and this did work before the 2.0.0 version update:

```
host_config:  {'RestartPolicy': {'MaximumRetryCount': 5, 'Name': 'always'}, 'PortBindings': {'8088/tcp': [{'HostPort': '8088', 'HostIp': ''}], '8181/tcp': [{'HostPort': '8181', 'HostIp': ''}], '5520/tcp': [{'HostPort': '5520', 'HostIp': ''}], '7088/tcp': [{'HostPort': '7088', 'HostIp': ''}], '5020/tcp': [{'HostPort': '5020', 'HostIp': ''}]}, 'NetworkMode': 'host', 'Privileged': True, 'Memory': 17179869184}
```

I am correctly passing the list of ports to the docker.container.create function, and as the docs say, passing a dict of ports into host_config. I'm not sure what needs to change here.

docker==2.0.1
docker-pycreds==0.2.1

docker --version
Docker version 1.12.6, build 78d1802

Thank you.

**Comment by shin-** [comment]
What version of `six` do you currently have installed? (`pip freeze | grep six`)

**Comment by twllight** [comment]
hey thanks for getting back so quick:
six==1.10.0

**Comment by shin-** [comment]
@twllight Can I ask what your `client.containers.create` call looks like? It looks like the problem might be coming from there.

**Comment by twllight** [comment]
Sure!

```
   cont_create = docker.containers.create(image       = ship_opts['cont_image'],
                                              hostname    = ship_opts['cont_hostname'],
                                              ports       = [5520, 8181, 7088, 8088, 5020],
                                              command     = ship_opts['cont_action'],
                                              volumes     = ship_opts['cont_volumes'],
                                              cpuset_cpus = ship_opts['cont_cpuset'],
                                              labels      = ship_opts['cont_label'],
                                              name        = ship_opts['cont_name'],
                                              environment = ship_opts['cont_env'],
                                              detach      = True,
                                                 tty         = True)
```
Sorry about the jank formatting :(

**Comment by shin-** [comment]
Okay, I see the issue now. With `docker.containers.create` we attempted to flatten the arguments list for HostConfig directly into the call, but it can be a bit confusing when migrating over from 1.x. As a result, `ports` and `port_bindings` have been fused into one and you'll just need to provide the dictionary in the `create` call. Same idea for `volumes` and `binds`.

You'll want to try this instead:
```python
cont_create = docker.containers.create(image       = ship_opts['cont_image'],
                                              hostname    = ship_opts['cont_hostname'],
                                              ports       = {5520: 5520, 7088: 7088, 8088: 8088, 5020: 5020, 8181: 8181},
                                              command     = ship_opts['cont_action'],
                                              cpuset_cpus = ship_opts['cont_cpuset'],
                                              labels      = ship_opts['cont_label'],
                                              name        = ship_opts['cont_name'],
                                              environment = ship_opts['cont_env'],
                                              detach      = True,
                                               tty         = True,
                                              privileged     = True,
                                               dns            = ship_opts['cont_dns'],
                                    dns_search     = ship_opts['cont_search'],
                                    mem_limit      = ship_opts['cont_memory'][0],
                                    network_mode   = ship_opts['cont_network_type'],
                                    binds          = mount_points,
                                    restart_policy = {"MaximumRetryCount": 5, "Name": "always"}
)

**Comment by twllight** [comment]
Ahhh perfect! thank you for the explanation! I'll close
