### ISSUE TITLE
prune_images is not available for version < 1.25

### ISSUE THREAD

**Issue by pradeepinmar** [docker/docker-py#1475]
1. Installed version 2.1.0, then used docker-machine to create one named 'node1'
2. Verified I can instantiate the client and create containers etc. Started to look into images api's 

3. Below script for pruning images

```
**import docker, os
import configparser

# Read Docker Daemon environment values
config = configparser.RawConfigParser()
config.read('../config/.env')

# Set Environment variables. I created a docker-machine with name node1
os.environ['DOCKER_HOST'] = config.get('docker-machine-node1', 'DOCKER_HOST')
os.environ['DOCKER_TLS_VERIFY'] = config.get('docker-machine-node1', 'DOCKER_TLS_VERIFY')
os.environ['DOCKER_CERT_PATH'] = config.get('docker-machine-node1', 'DOCKER_CERT_PATH')
client = docker.from_env()

# Prune images
pruned_images_ids = client.images.prune()
print(pruned_images_ids)
**
``` 

This results in the below error. 

```
Traceback (most recent call last):
  File "/Users/pmacharl/git-projects/docker_sdk_examples/python/random_scripts/images_examples.py", line 31, in <module>
    pruned_images_ids = client.images.prune()
  File "/Users/pmacharl/git-projects/docker_sdk_examples/venv/lib/python3.6/site-packages/docker/models/images.py", line 275, in prune
    return self.client.api.prune_images(filters=filters)
  File "/Users/pmacharl/git-projects/docker_sdk_examples/venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 32, in wrapper
    f.__name__, version
docker.errors.InvalidVersion: prune_images is not available for version < 1.25
```   

``` 
# pip freeze | grep docker && python --version && docker version
docker==2.1.0
docker-pycreds==0.2.1
Python 3.6.0
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

OS: Mac OSX El Capitan. 

*Note* My python code runs on mac, hitting the docker-engine that is on docker-machine node1

Any suggestions/help if I am missing something obvious here please ?

**Comment by shin-** [comment]
`client = docker.from_env(version='1.25')`

**Comment by pradeepinmar** [comment]
Perfect, that fixed it, thanks!
