### ISSUE TITLE
Error while updating swarm service

### ISSUE THREAD

**Issue by n1b0r** [docker/docker-py#1503]
Hello,

I'm trying to update the secrets of a running swarm service :

```
$ docker swarm init
$ docker network create -d overlay test_network
$ docker service create --name test_service --network test_network nginx
$ echo "test" | docker secret create test_secret -
```

now, using python console.

```
>>> import docker
>>> cli = docker.DockerClient(base_url='unix://var/run/docker.sock', version='1.25')
>>> service = cli.services.list()[0]
>>> secret = cli.secrets().list()[0]
>>> service.update(secrets=[docker.types.SecretReference(secret.id, secret.name)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/models/services.py", line 77, in update
    **create_kwargs
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/service.py", line 282, in update_service
    self._raise_for_status(resp)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.25/services/k0dcr80bqsn44a9izae7r7c4a/update?version=1429 ("rpc error: code = 2 desc = changing network in service is not supported")
>>> 

```

How should I update the service ? Should I really need to give every parameters for `update()` method ?

**Comment by n1b0r** [comment]
In the case that every parameters should be given to update() I'm getting stopped by:

```
>>> [x['Target'] for x in service.attrs['Spec']['Networks']]
[u'k9gcb5znnv60ah5k9iq23n40j']
>>> service.update(networks=[x['Target'] for x in service.attrs['Spec']['Networks']])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/models/services.py", line 77, in update
    **create_kwargs
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/service.py", line 282, in update_service
    self._raise_for_status(resp)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.25/services/lmwvz3uvbb09mb95e8jbfjwqj/update?version=173358 ("rpc error: code = 2 desc = changing network in service is not supported")

```

**Comment by rogergithub3** [comment]
Hi,

I have the same issue, I'm trying to scale the service with update service's method. This works for me:
```
import docker
scale = 10
cli = docker.DockerClient(base_url='unix://var/run/docker.sock', version='1.25')
service = cli.services.list()[0]
secret = cli.secrets().list()[0]
mode = docker.types.services.ServiceMode("replicated", int(scale))
service.update(name=service.attrs['Spec']['Name'], networks=service.attrs['Spec']['Networks'])
```
