### ISSUE TITLE
Closing stdin on a Running Container

### ISSUE THREAD

**Issue by ccoffrin** [docker/docker-py#1507]
I am using docker version 2.1.0.

When starting a container the parameter `stdin_open` can be used to prepare the stdin socket for writing.  I have had success doing this with code along these lines,
```
stdin_data = 'some data to send to stdin'

container = client.containers.run(image, detach=True, stdin_open=True)

socket = container.attach_socket(params={'stdin': 1, 'stream': 1})
os.write(socket.fileno(), stdin_data.encode())
socket.close()

exit_code = container.wait()
```

I have also found that this approach can easily hang indefinitely, if the underlying container is waiting for input.  The reason seems to be be that the socket status is independent of the `stdin_open` parameter, so the code running in the container never receives an EOF-like sentinel on stdin.

Any suggestions on how to address this?

**Comment by nkprince007** [comment]
I have a similar issue too. Indefinite hang of container.

**Comment by seifertm** [comment]
I ran into the same problem. This is related to #983.

**Comment by jstangroome** [comment]
If container run/create supported the `StdinOnce` parameters to the API, closing the socket should be enough.

https://docs.docker.com/engine/api/v1.35/#operation/ContainerCreate

**Comment by mschwager** [comment]
Are there any solutions here? I'm running into the exact same issue.

**Comment by mschwager** [comment]
Okay, I still couldn't find a solution, but I did some investigation. Consider the following files:

```
$ cat output.py 
#!/usr/bin/env python

import sys

print("Running output.py")

data = sys.stdin.read()
print("stdout: {}".format(data), file=sys.stdout)
print("stderr: {}".format(data), file=sys.stderr)
```

```
$ cat Dockerfile 
FROM python:3.7-slim

COPY output.py /app/

ENTRYPOINT ["python", "/app/output.py"]
```

```
$ docker build -t stdin-test .
Sending build context to Docker daemon   5.12kB
Step 1/3 : FROM python:3.7-slim
 ---> b386e7420fc3
Step 2/3 : COPY output.py /app/
 ---> Using cache
 ---> eef08dc98862
Step 3/3 : ENTRYPOINT ["python", "/app/output.py"]
 ---> Using cache
 ---> 02f03bf09cfe
Successfully built 02f03bf09cfe
Successfully tagged stdin-test:latest
```

```
$ echo -n 'test' | docker run -i stdin-test
Running output.py
stdout: test
stderr: test
```

So we have a Docker image that runs a Python script that accepts `stdin` and simply prints to `stdout` and `stderr`.

I'm trying to accomplish the same thing via `docker-py`: send data on `stdin` and read `stdout` and `stderr` separately. Building on the code above, it appears that the connection is not being fully closed, so the `wait` call hangs indefinitely. I've added some additional debugging output:

```python
#!/usr/bin/env python

import docker

client = docker.APIClient()
container = client.create_container(
    'stdin-test',
    detach=True,
    stdin_open=True,
)

print('Starting...')
client.start(container)
print('Attaching...')
sock = client.attach_socket(container, params={"stdin": 1, "stream": 1})
print('Sending...')
sock._sock.send(b'sent data')

print((
    sock,
    sock._response.raw,
    sock._response.raw._fp,
    sock._response.raw._fp.fp,
    sock._response.raw._fp.fp.raw
))

print('Before...')
print((
    sock.closed,
    sock._response.raw.closed,
    sock._response.raw._fp.closed,
    sock._response.raw._fp.fp.closed,
    sock._response.raw._fp.fp.raw.closed
))
sock.close()
print('After...')
print((
    sock.closed,
    sock._response.raw.closed,
    sock._response.raw._fp.closed,
    sock._response.raw._fp.fp.closed,
    sock._response.raw._fp.fp.raw.closed
))


print('Waiting...')
status = client.wait(container)
status_code = status["StatusCode"]
stdout = client.logs(container, stderr=False).decode()
stderr = client.logs(container, stdout=False).decode()

client.remove_container(container)

print('Exit: {}'.format(status_code))
print('stdout: {}'.format(stdout))
print('stderr: {}'.format(stderr))
```

And I see the following:

```
$ python run.py 
Starting...
Attaching...
Sending...
(<socket.SocketIO object at 0x7fcb55983518>, <urllib3.response.HTTPResponse object at 0x7fcb55983940>, <docker.transport.unixconn.UnixHTTPResponse object at 0x7fcb55983198>, <_io.BufferedReader name=6>, <socket.SocketIO object at 0x7fcb55983518>)
Before...
(False, False, False, False, False)
After...
(True, False, False, True, True)
Waiting...
```

So the first `socket.SocketIO`, second `socket.SocketIO`, and `_io.BufferedReader` have closed correctly, while the `urllib3.response.HTTPResponse` and `docker.transport.unixconn.UnixHTTPResponse` are reporting that they're not closed. Could this be the reason for the hang? It appears that: some part of the connection is not closing correctly, so the Docker container is not registering that the `stdin` `read` has finished, and thus the `wait` hangs. Does that seem right?

**Comment by mschwager** [comment]
Interestingly, it looks like there's differences between Python 2 and Python 3.

If I remove `detach=True` the following code works as expected in Python 2:

```python
print('Attaching...')
sock = client.attach_socket(container, params={"stdin": 1, "stream": 1})
print('Sending...')
sock.send(b'sent data')
print('Closing...')
sock.close()
```

```
$ python2 run.py 
Starting...
Attaching...
Sending...
Closing...
Waiting...
Exit: 0
stdout: Running output.py
stdout: sent data

stderr: stderr: sent data
```

```
$ python3 run.py 
Starting...
Attaching...
Sending...
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    sock.send(b'sent data')
AttributeError: 'SocketIO' object has no attribute 'send'
```

This is expected due to the Python 2 and 3 differences. However, changing to the following code produces different results:

```python
print('Attaching...')
sock = client.attach_socket(container, params={"stdin": 1, "stream": 1})
print('Sending...')
sock._sock.send(b'sent data')
print('Closing...')
sock.close()
```

```
$ python2 run.py 
Starting...
Attaching...
Sending...
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    sock._sock.send(b'sent data')
AttributeError: '_socket.socket' object has no attribute '_sock'
```

```
$ python3 run.py 
Starting...
Attaching...
Sending...
Closing...
Waiting...
...
Hangs
```

So the question is: can we achieve the old Python 2 behavior from `_socket.socket` with Python 3's `SocketIO`?

**Comment by mschwager** [comment]
Okay, I think I figured it out! The missing ingredient was a `_sock.close` call. So the complete example:

```python
#!/usr/bin/env python

import docker

client = docker.APIClient()
container = client.create_container(
    'stdin-test',
    stdin_open=True,
)

sock = client.attach_socket(container, params={"stdin": 1, "stdout": 1, "stderr": 1, "stream": 1})
client.start(container)
sock._sock.send(b'sent data')
sock._sock.close()
sock.close()

status = client.wait(container)
status_code = status["StatusCode"]
stdout = client.logs(container, stderr=False).decode()
stderr = client.logs(container, stdout=False).decode()

client.remove_container(container)

print('Exit: {}'.format(status_code))
print('log stdout: {}'.format(stdout))
print('log stderr: {}'.format(stderr))
```

Running against the Docker image above, which simply runs the following script, produces the following output:

```python
#!/usr/bin/env python

import sys

print("Running output.py")

data = sys.stdin.read()
print("stdout: {}".format(data), file=sys.stdout)
print("stderr: {}".format(data), file=sys.stderr)
```

```
$ python run.py 
Exit: 0
log stdout: Running output.py
stdout: b'sent data'
log stderr: stderr: b'sent data'
```

So we can see that the `output.py` script received `stdin` and successfully printed it!

I believe the original issue can be resolved with the following:

```python
socket._sock.close()
socket.close()
```

The API ergonomics leave something to be desired here. Having the muck with `sock._sock` is not ideal, but this workaround appears to work as expected :+1:
