### ISSUE TITLE
Impossible to run any command 

### ISSUE THREAD

**Issue by Amtime** [docker/docker-py#1511]
Hello, I've got this error that I can't interprete. I really don't know what info you need for helping me so let me know. Here is the error message : 

```
import docker
client = docker.from_env()
client.containers.list()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\models\containers.py", line 766, in list
    since=since)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\api\container.py", line 189, in containers
    res = self._result(self._get(u, params=params), True)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\utils\decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\api\client.py", line 183, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Kilian\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\Kilian\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Users\Kilian\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Users\Kilian\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\Kilian\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\transport\npipeconn.py", line 31, in connect
    sock.connect(self.npipe_path)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\transport\npipesocket.py", line 22, in wrapped
    return f(self, *args, **kwargs)
  File "D:\Dev\Gitlab\TX_RootUTT\env\lib\site-packages\docker\transport\npipesocket.py", line 50, in connect
    win32pipe.WaitNamedPipe(address, self._timeout)
pywintypes.error: (2, 'WaitNamedPipe', 'Le fichier spécifié est introuvable.')
```

**Comment by shin-** [comment]
Are you using Docker Machine or Docker Toolbox? If so, you might be missing this command: `docker-machine.exe env --shell=powershell dev | Invoke-Expression` (https://docs.docker.com/machine/reference/env/)

**Comment by Amtime** [comment]
I didn't run any container, what a stupid boy, sorry about that
