### ISSUE TITLE
Error closing logger: invalid argument

### ISSUE THREAD

**Issue by mschwager** [docker/docker-py#1542]
Originally I thought this was a `docker` issue, but it appears to be a `docker-py` issue. I raised an issue here (https://github.com/docker/docker/issues/32239), but I think this will have to be fixed in `docker-py`.

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1362
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2689
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.679 GiB
Name: x1
ID: AS5A:3REA:TXRP:IGYF:R4AI:IC63:KDLD:OPR2:USZX:77W2:KGNH:22S6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mattsduosec
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I'm seeing the following errors when running `commit` (https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.commit):

```
b'2017-03-30T21:27:15.881302433Z + tar --gzip --create --directory /usr/local --file /opt/duo/dag_third_party.tgz bin etc lib/python2.7 sbin ssl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 214, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.26/commit?tag=latest&container=bfa1c04149e3cd6318722b0063b725319dfd08ecb3e3247c405cdc522fcdfd3a&repo=duosecurity%2Faccess-gateway-builder-thirdparty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tupperware.py", line 877, in <module>
    main()
  File "tupperware.py", line 871, in main
    dispatch[args.command](**vars(args))
  File "tupperware.py", line 361, in build
    build_third_party_tarball(client, DAG_BUILDBASE_DOCKERFILE, tag, force=force)
  File "tupperware.py", line 398, in build_third_party_tarball
    commit_docker_container(client, third_party_id, DAG_BUILDER_THIRDPARTY_IMAGE)
  File "tupperware.py", line 183, in commit_docker_container
    client.commit(container, repository=repository, tag=tag)
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/container.py", line 129, in commit
    json=True)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error: driver aufs is returning inconsistent paths for container bfa1c04149e3cd6318722b0063b725319dfd08ecb3e3247c405cdc522fcdfd3a ('/var/lib/docker/aufs/mnt/79ca5cbc252b6f52162f370595c790973d480e9b88d89a2dad6fbfe41af59005' then '/var/lib/docker/aufs/diff/79ca5cbc252b6f52162f370595c790973d480e9b88d89a2dad6fbfe41af59005')")
```

```
Mar 30 16:53:50 x1 dockerd[1173]: time="2017-03-30T16:53:50.108905324-04:00" level=error msg="Error closing logger: invalid argument"
Mar 30 16:53:50 x1 dockerd[1173]: time="2017-03-30T16:53:50.263311304-04:00" level=error msg="Error unmounting container eaf3d589471c45714baaddd17d3d863861978bad16b01d7dba80e30767100313: no such file or directory
Mar 30 16:53:50 x1 dockerd[1173]: time="2017-03-30T16:53:50.263391788-04:00" level=error msg="Handler for POST /v1.26/commit returned error: Error: driver aufs is returning inconsistent paths for container eaf3d5
```

One thing I noticed, it's referencing `500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.26/commit?tag=latest&container=bfa1c04149e3cd6318722b0063b725319dfd08ecb3e3247c405cdc522fcdfd3a` version `1.26` but my docker version reports `1.27`. Could that be a problem?

I narrowed it down to `docker-py` because running the same code with version `2.1.0` works whereas `2.2.1` fails.

**Comment by shin-** [comment]
A 500 error is still a server-side (engine) issue and should be addressed at that level.

One significant difference between 2.1.0 and 2.2.1 is the default API version (1.24 vs 1.26). Can you reproduce the issue with 2.2.1 if you specify `version=1.24` when instantiating the Client?

**Comment by shin-** [comment]
I'm going to close this, but feel free to reopen if your issue persists.
