### ISSUE TITLE
Inconsistent behavior for pulling images with client.images.build

### ISSUE THREAD

**Issue by thejamesmarq** [docker/docker-py#1630]
When I try to build images and need to download updates to the source image, I see some inconsistent behavior when running the following:

```
DOCKER_CLIENT = docker.from_env()
DOCKER_CLIENT.images.build(fileobj=dockerfile, tag=image_name, pull=True)
```

**This works here (macOS Sierra 10.2.3, python 3.6, docker sdk 2.0.0, docker 17.03.1-ce-mac12 (17661))**

**This doesn't (Ubuntu 14.04, python 3.6, docker sdk 2.0.0, docker 1.12.3 build 6b644ec)**
Traceback (most recent call last):
  File "buildImages.py", line 95, in <module>
    main(dockerhub_username, dockerhub_password, scan_path)
  File "buildImages.py", line 85, in main
    DOCKER_CLIENT.images.build(fileobj=dockerfile, tag=image_name, pull=True)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/docker/models/images.py", line 169, in build
    raise BuildError(event.get('error') or event)
docker.errors.BuildError: Error: image [secure]/r_base_worker:latest not found

**I do notice, however, that if I explicitly pull the image I am building from and set pull to False, it does work:**
```
DOCKER_CLIENT = docker.from_env()
DOCKER_CLIENT.images.pull(image))
DOCKER_CLIENT.images.build(fileobj=dockerfile, tag=image_name, pull=True)
```

**Comment by shin-** [comment]
Please upgrade to 2.3.0
