### ISSUE TITLE
`update_service` method doesn't work

### ISSUE THREAD

**Issue by FromZeus** [docker/docker-py#1684]
**Problem:**
When I'm trying to update service via python service API I'm getting
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal object into Go struct field EndpointSpec.Mode of type swarm.ResolutionMode")
```
**Full stack trace:**
```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    client.update_service(client.services()[0]["ID"], version=client.services()[0]["Version"]["Index"], task_template=task_template, name=client.services()[0]["Spec"]["Name"], labels=client.services()[0]["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/api/service.py", line 350, in update_service
    self._raise_for_status(resp)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker-2.4.2-py2.7.egg/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal object into Go struct field EndpointSpec.Mode of type swarm.ResolutionMode")
```

**Code snippet:**
```
import docker
from docker import types

client = docker.APIClient()

task_template = types.TaskTemplate(client.services()[0]["Spec"]["TaskTemplate"])
update_config = types.UpdateConfig(client.services()[0]["Spec"]["UpdateConfig"])
networks = client.services()[0]["Spec"]["TaskTemplate"]["Networks"]
endpoint_spec = types.EndpointSpec(client.services()[0]["Spec"]["EndpointSpec"])
mode = {u'Global': {}}

client.update_service(client.services()[0]["ID"], version=client.services()[0]["Version"]["Index"], task_template=task_template, name=client.services()[0]["Spec"]["Name"], labels=client.services()[0]["Spec"]["Labels"], mode=mode, update_config=update_config, networks=networks, endpoint_spec=endpoint_spec)
```

**Software information:**
```
docker==2.4.2
docker-cleaner==1.0.1
docker-compose==1.13.0
docker-pycreds==0.2.1
docker-registry-client==0.5.1
dockerpty==0.4.1
Python 2.7.12
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

Linux null 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shin-** [comment]
That's a server error - can you submit it to [moby/moby](https://github.com/moby/moby)?

**Comment by FromZeus** [comment]
Yep, sure

**Comment by shin-** [comment]
https://github.com/moby/moby/issues/34116#issuecomment-315484688

**Comment by shin-** [comment]
Should work now with #1807
