### ISSUE TITLE
Deleting a volume with volume name containing blanks failed using docker python sdk

### ISSUE THREAD

**Issue by YuDaiWang** [docker/docker-py#1758]
Description:
Creating a volume with the volume name contains a blank successfully，but delete the volume failed. When deleting the volume that the name contains a blank, the blank is decoded to "+". 
Steps to Reproduce:
1. Create a docker python client
2. Create a volume with name "vo1 test_-" using the client
3. List volumes using the client
4. Delete the volume "vo1 test_-" using the client
The command and errors:
>>> import docker
>>> client = docker.DockerClient(base_url='tcp://ci-docker-node1:2375')
>>> client.volumes.create(name='vo1 test_-', driver='ubiquity', driver_opts={'size': "5", 'profile': 'gold'})
<Volume: vo1 test_->
>>> created_volume=client.volumes.list()
>>> created_volume
[<Volume: vo1 test_->]
>>> created_volume[0].remove()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wangyd/xenv/lib/python2.7/site-packages/docker/models/volumes.py", line 25, in remove
    return self.client.api.remove_volume(self.id, force=force)
  File "/Users/wangyd/xenv/lib/python2.7/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/wangyd/xenv/lib/python2.7/site-packages/docker/api/volume.py", line 165, in remove_volume
    self._raise_for_status(resp)
  File "/Users/wangyd/xenv/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/wangyd/xenv/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("get vo1+test_-: no such volume")
>>>

**Comment by shin-** [comment]
Thanks for the report, we'll look into it!
