### ISSUE TITLE
Fetching all tags without a `latest` tag fails

### ISSUE THREAD

**Issue by mikeage** [docker/docker-py#1761]
Hi,
I'm trying to fetch every tag for a specific image (to mimic the behavior of `docker pull --all-tags foo`, but if I don't have a `foo:latest` on the remote repository, it fails (unlike the command line version). If there is a `latest` tag, then it successfully fetches all of them.

**Comment by mikeage** [comment]
```
Traceback (most recent call last):
  File "/Users/mikemi/analyze_base.py", line 71, in <module>
    main()
  File "/Users/mikemi/analyze_base.py", line 37, in main
    client.images.pull(base)
  File "/usr/local/lib/python2.7/site-packages/docker/models/images.py", line 277, in pull
    return self.get('{0}:{1}'.format(name, tag) if tag else name)
  File "/usr/local/lib/python2.7/site-packages/docker/models/images.py", line 204, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/image.py", line 262, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: dockerhub.internal-company-server.com/foo: No such image: dockerhub.internal-company-server.com/foo:latest")
```
