### ISSUE TITLE
client.search(query) not work

### ISSUE THREAD

**Issue by magicshui** [docker/docker-py#179]
When i use the search(),it doesn't work,i want to search the index of docker.io:

```
>>> c.search('ubuntu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 680, in search
    params={'term': term}),
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 102, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
    raise Timeout(e)
requests.exceptions.Timeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=10)
```

**Comment by HackToday** [comment]
I hit the same issue for docker-py

2015-03-04 06:02:27.813 19496 ERROR oslo_messaging.rpc.dispatcher [-] Exception during message handling: UnixHTTPConnectionPool(host='localhost', port=None): Max retries exceeded with url: /run/docker.sock/v1.17/containers/2a686955856811a1cf8a2c90718a235d132b72c022cf379e02902eecff9e6f2a/restart?t=10 (Caused by ReadTimeoutError("UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=10)",))

we used the docker-py to call docker

**Comment by HackToday** [comment]
do you know what's the issue ? @mpetazzoni
