### ISSUE TITLE
build function gives broken pipe error 

### ISSUE THREAD

**Issue by mowreyw** [docker/docker-py#1824]
When running `client.images.build()` I receive a broken pipe error that seems to be related to generating chunked output. The code in question was working previously, but hasn't been used in a few weeks. In that time I upgraded my OS, so that may have caused something to break. I can still run containers and list images without issue; only `build()` has an issue so far.

Traceback:
```
>>> build = client.images.build(path='..',tag='TEST',dockerfile='./Docker/Dockerfile')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/docker/models/images.py", line 172, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/build.py", line 258, in build
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 187, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

Docker-py is `docker==2.6.1`
OS is Mac OS 10.13.1 (High Sierra)

Docker version:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by shin-** [comment]
Thanks for the report! Here are a few things worth exploring:

- Does it work with Python 3.5? We don't officially support 3.6 yet.
- Are there any named pipes in your build context, or inaccessible root-owned files?

**Comment by shin-** [comment]
Also, please check out #1825 to see if it fixes your issue.

**Comment by shin-** [comment]
Closing via #1825 , but please let me know if the issue persists despite that patch.

**Comment by Datamance** [comment]
Having this exact same issue with 3.6.0 release -- @shin- and @mowreyw did y'all ever find a resolution to this? I'm thinking the problem right now is that my build context is ginormous (like above 5.3G at the moment - trying to test some things), but wanted to be sure I wasn't missing anything obvious

**Comment by Datamance** [comment]
Nope, just tested it without the crazy build context.

the dockerd logs from the os x console don't help much either -
```
default	18:51:18.157715 -0500	com.docker.driver.amd64-linux	proxy >> POST /v1.35/build?t=ember_build%3Aa427f62d9b0a76340c0c2a0f30055525b2543e8a_b291e1bb3653808b32b32eb9c84675043d79abe3&q=False&nocache=False&rm=False&forcerm=False&pull=True&buildargs=%7B%22player_addons_concat_sha%22%3A+%22a427f62d9b0a76340c0c2a0f30055525b2543e8a_b291e1bb3653808b32b32eb9c84675043d79abe3%22%7D&cachefrom=%22ember_build%22

default	18:51:18.661741 -0500	com.docker.driver.amd64-linux	error forwarding client's request to Docker: write unix ->vms/0/00000003.00000948: write: broken pipe```

**Comment by Datamance** [comment]
Here's my `docker version`:
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by Datamance** [comment]
@shin- I'm still having this issue.

**Comment by shin-** [comment]
@Datamance We can take a look - can you provide the information requested [in this list?](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues) The more the better.

**Comment by Datamance** [comment]
So, I figured it out - when I try to

**Comment by Datamance** [comment]
```docker==3.7.2
docker-pycreds==0.4.0
Python 3.6.7
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true```

There's the info.

Although, I see where the pathology lies now - I can't pass a `cache_from` argument. It even looks like the url that makes it into the connection pool is a little off:

`'/v1.35/build?t=ember_build&q=False&nocache=False&rm=False&forcerm=False&pull=True&cachefrom=%22ember_build%22'`

If I forgo the cache_from argument, everything works just fine.

**Comment by Datamance** [comment]
@shin- it looks like it has to do [with this urllib3 issue](https://github.com/urllib3/urllib3/issues/303) - is there a reason why the cache_from arg gets put in quotes before getting encoded in the query string?

**Comment by shin-** [comment]
Again, please refer to the list I linked and provide all the information requested.

> - **SDK version**, Docker version and python version
> ```
> pip freeze | grep docker && python --version && docker version
> ```
> - **OS, distribution and OS version**
> - The issue you're encountering including a stacktrace if applicable
> - If possible, **steps or a code snippet to reproduce the issue**

**Comment by Datamance** [comment]
Here is the [line of code](https://github.com/lookit/lookit-api/blob/feature/223-new-dependency-updates/studies/experiment_builder.py#L191) for which, if I include the `cache_from` argument, I get the BrokenPipe error.

You can see from the [Pipfile](https://github.com/lookit/lookit-api/blob/feature/223-new-dependency-updates/Pipfile#L56) that I've got the latest version of the SDK.

**Comment by Datamance** [comment]
```

**Comment by shin-** [comment]
@Datamance Does it work if you provide `cache_from` as a list (i.e. `cache_from=['ember_build']`)?

**Comment by Datamance** [comment]
@shin- it absolutely does. I apologize, I should have double checked the type in the API docs.

**Comment by shin-** [comment]
Glad it was an easy fix! We should probably add some type-checking for this parameter, especially if it results in cryptic errors like this one.

**Comment by marciogranzotto** [comment]
Just if someone has the same problem that I did: 
I had the same error message, but it was because the container had an x86_64 binary that a python script executed, but since it was built on an M1 mac, the container was `amd64`.
Adding `--platform x86_64` to `docker build` fixed the issue.
