### ISSUE TITLE
service create issue

### ISSUE THREAD

**Issue by umardraz** [docker/docker-py#1850]
Hello 

I am trying to create docker swarm service from remote client and that is not working. Here is my code
```

import docker
from pprint import pprint

#client = docker.from_env()

tls_config = docker.tls.TLSConfig(
  client_cert=('/home/cert.pem', '/home/key.pem'),
  verify='/home/ca.pem'
)

client = docker.DockerClient(base_url='tcp://10.132.19.187:2376', tls=tls_config)

image_name = 'rocketchat/rocket.chat'
total_containers=1
replica_mode = docker.types.ServiceMode('replicated', replicas=total_containers)
target_port = docker.types.EndpointSpec(ports=[{'TargetPort':3000}])

params = {
	'endpoint_spec': docker.types.EndpointSpec(ports=[{'TargetPort':3000}]),
        'name': 'chat',
        'hostname': 'chat',
        'image': 'rocketchat/rocket.chat',
        'networks': ['ingroups'],
        'mode': docker.types.ServiceMode('replicated', replicas=1),
        'env' : ['MONGO_URL=mongodb://mongo:27017/chat','ROOT_URL=http://chat']
}

try:
    client.services.create(**params)
except docker.errors.APIError as error:
    print(error)
```
And here is the error

```
Traceback (most recent call last):
  File "create.py", line 32, in <module>
    client.services.create(**params)
  File "/usr/lib/python2.7/site-packages/docker/models/services.py", line 177, in create
    service_id = self.client.api.create_service(**create_kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/service.py", line 137, in create_service
    auth_header = auth.get_config_header(self, registry)
AttributeError: 'module' object has no attribute 'get_config_header'

```

Would you please help me what is the issue and how I can fix this.

**Comment by shin-** [comment]
Can you provide the necessary information as explained [here](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues)? Thank you!

**Comment by umardraz** [comment]
Hello
I have just did that
pip uninstall docker-pypip install docker
Then it start working    On Thursday, December 28, 2017, 12:22:02 AM GMT+5, Joffrey F <notifications@github.com> wrote:  
 
 
Can you provide the necessary information as explained here? Thank you!
