### ISSUE TITLE
Password being truncated after calling client.login

### ISSUE THREAD

**Issue by hongkunyoo** [docker/docker-py#1900]
I was using ECR registry and wanted to pull images from there
The following commands are what I've done for it.
1. `aws ecr get-login`
after this command, I retrieved the user and the password
user='AWS'
pwd='something very long'

2. in python REPL
`import docker`
`client = docker.from_env()`
`conf = client.login(username=user, password=pwd, registry=my_ecr_registry)`

3. after I've got login
I've tried to pull image but keeps failed
`client.images.pull('000.dkr.ecr.us-west-2.amazonaws.com/my_repo_name', auth_config=conf)`
> 404 Client Error: Not Found ("repository 000.dkr.ecr.us-west-2.amazonaws.com/my_repo_name not found: does not exist or no pull access")

I found out that the password I've passed to the client and the returned conf's password is different.
`pwd!= conf['password']`
It seems that the conf's password has been truncated in the tail.

So, I changed the dict password manually and try it to pull the image and it worked.
`conf['password'] = pwd`
`client.images.pull(my_repository_name, auth_config=conf)`
> Success to pull image from ECR registry

It think there is a slight bug in the client.login function
Please take a look at it and let me know whether I'am doing something wrong.

**Comment by shin-** [comment]
Thanks for the report!

Can you provide the information requested in the [guidelines](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues)? It would help a lot knowing what version you're working with.

Also note that you don't need to provide `auth_config` in `pull` if you've logged in with the same client object, as the client retains the login information internally. Does it work if you don't pass `auth_config`? 

e.g. this should work:

```python
import docker
client = docker.from_env()
client.login(user, pwd, registry=my_ecr_registry)
client.images.pull(('000.dkr.ecr.us-west-2.amazonaws.com/my_repo_name')
```

**Comment by hongkunyoo** [comment]
This is my environment settings
`pip freeze | grep docker && python --version && docker version`
>docker==3.0.0
docker-pycreds==0.2.1
Python 3.6.1 :: Continuum Analytics, Inc.
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

------------------------
`lsb_release -a`
>Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
--------------------------
`uname -a'
>Linux ryan 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
--------------------------

Also, I got the same error when calling pull function without auth_config parameter even though I've used the same client object.
`client.login(user, pwd, registry=my_ecr_registry)`
`client.images.pull('000.dkr.ecr.us-west-2.amazonaws.com/name')`
> Traceback (most recent call last):
  File "/home/user_name/miniconda3/lib/python3.6/site-packages/docker/api/client.py", line 223, in _raise_for_status
    response.raise_for_status()
  File "/home/user_name/miniconda3/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.35/images/create?tag=latest&fromImage=0000.dkr.ecr.us-west-2.amazonaws.com%2Fname
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user_name/miniconda3/lib/python3.6/site-packages/docker/models/images.py", line 309, in pull
    self.client.api.pull(repository, tag=tag, **kwargs)
  File "/home/user_name/miniconda3/lib/python3.6/site-packages/docker/api/image.py", line 374, in pull
    self._raise_for_status(response)
  File "/home/user_name/miniconda3/lib/python3.6/site-packages/docker/api/client.py", line 225, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/user_name/miniconda3/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("repository 000.dkr.ecr.us-west-2.amazonaws.com/name not found: does not exist or no pull access")

**Comment by hongkunyoo** [comment]
I've acquired the password through aws boto API and it worked.
Is there a difference between acquiring the password through `aws ecr get-login` on console manually and acquiring through boto API? (I used the password getting from `aws ecr get-login` within 1hr)
Sorry to bother you.

`boto_client = boto3.client('ecr')`
`auth = boto_client.get_authorization_token(registryIds=['00'])`
`user = 'AWS'`
`pwd = auth['authorizationData'][0]['authorizationToken']`
`client = docker.from_env()`
`client.login(username=user, password=pwd, registry='https://00.dkr.ecr.us-west-2.amazonaws.com')`
`image = client.images.pull(repo)`

**Comment by shin-** [comment]
Sorry for the late reply - I think you were originally running into the follwing issue: #1895 Have you upgraded to `docker==3.0.1` since? If so that probably cleared part of the problem.

As for AWS issues specifically, I don't have experience with it, but you may find this comment useful: https://github.com/docker/docker-py/issues/1677#issuecomment-363283049

Let me know if anything's still unclear.

**Comment by widgetpl** [comment]
I have just faced the same issue
```
$ pip3 freeze | grep docker && python3 --version && docker version
docker==4.0.2
Python 3.6.8
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
without `auth_config` I get
```
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for 000000000000.dkr.ecr.eu-central-1.amazonaws.com/repo_name, repository does not exist or may require 'docker login'")
```
when I overwrite `auth_config` in `pull()` then it works fine.
`login()` returns
```
{'IdentityToken': '', 'Status': 'Login Succeeded'}
```
