### ISSUE TITLE
Pull image by full digest is broken in 3.0.1

### ISSUE THREAD

**Issue by eshepelyuk** [docker/docker-py#1912]
Using `python3` and `3.0.1` version - this can be reproduced as

```
>>> import docker
>>> client = docker.from_env()
>>> client.images.pull('python@sha256:7c3028aa4b9a30a34ce778b1fd4f460c9cdf174515a94641a89ef40c115b51e5')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 223, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://192.168.99.100:2376/v1.35/images/python:sha256:7c3028aa4b9a30a34ce778b1fd4f460c9cdf174515a94641a89ef40c115b51e5/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 311, in pull
    return self.get('{0}:{1}'.format(repository, tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 212, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/image.py", line 241, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 229, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 225, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("no such image: python:sha256:7c3028aa4b9a30a34ce778b1fd4f460c9cdf174515a94641a89ef40c115b51e5: invalid reference format")
```

Downgrading to `2.7.0` solves the issue.

**Comment by shin-** [comment]
Thanks for the report!
