### ISSUE TITLE
Package docker.utils.json_stream cannot be imported

### ISSUE THREAD

**Issue by mbroomfield-r7** [docker/docker-py#1931]
Hello,
I was trying to import a helper function to print the output of a `docker build` command. So I tried to import `docker.utils.json_stream` and got this error.

```
>>> import docker.utils.json_stream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/docker/utils/json_stream.py", line 9, in <module>
    from ..errors import StreamParseError
ImportError: cannot import name 'StreamParseError'
```

Seems like the Exception `StreamParseError` is missing.

Even if what I'm doing is wrong, seems like this code is unusable.

```
$ pip3 list | grep docker
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
docker (2.3.0)
docker-compose (1.13.0)
docker-pycreds (0.2.1)
dockerize (0.2.2)
dockerpty (0.4.1)
$ python3 --version
Python 3.6.4 
```

**Comment by mbroomfield-r7** [comment]
I definitely just have a way old version of this library installed. Apologies.
