### ISSUE TITLE
Potential Regression: float() argument must be a string or a number, not 'Timeout'

### ISSUE THREAD

**Issue by jaitaiwan** [docker/docker-py#1936]
## Summary
When attempting to connect to the docker instance, the connection is never made as there is a type mismatch of expected inputs.

## System Info
 - python 3.6.3
 - docker-py 3.1.0
 - requests 2.18.4
 - docker 17.06.2-ce cec0b72

Docker confirmed as working and running. Docker cli tool connects through socket located at `/run/docker.sock`

No env variables are set for the docker environment.

### Code
```
import docker
c = docker.from_env()
c.info()
```

### Traceback

```
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.local/lib/python3.6/site-packages/docker/client.py", line 174, in info
    return self.api.info(*args, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/docker/api/daemon.py", line 88, in info
    return self._result(self._get(self._url("/info")), True)
  File "$HOME/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/docker/api/client.py", line 192, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "$HOME/.local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "$HOME/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "$HOME/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "$HOME/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "$HOME/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "$HOME/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None.
```

**Comment by ansemjo** [comment]
I have just hit that same error when running `docker-compose`. Actually, I had a different one before that but I did not take note what it was specifically. It was obvious however that the culprit was a version mismatch of `python-requests`.

I proceeded to reinstall `python-requests` through my package manager to get the latest version. When I ran `docker-compose` afterwards I got the error message above.

Completely purging all `requests`-related files, i.e.
```
# rm -rf /usr/lib/python3.6/site-packages/requests*
```
and then reinstalling that package again fixed it for me. [Others](https://github.com/coursera-dl/coursera-dl/issues/611) seem to suggest that downgrading `requests` to `2.10.0` helps.

**Comment by canidam** [comment]
https://github.com/docker/compose/issues/634#issuecomment-965056530

**Comment by jaitaiwan** [comment]
I'm going to close this out as it seems like it's not a fault of the library.
