### ISSUE TITLE
Start container with specific name

### ISSUE THREAD

**Issue by KOPACb** [docker/docker-py#1986]
I cannot start container with specific name, or i missed something:

```python
>>> import docker
>>> client = docker.from_env()
>>> client.containers.run('selenium/hub:3.11.0-bismuth', name = 'HUB', ports = {4444:4444}, detach = True)
<Container: 45ec900b2e>
>>> hub = client.containers.list()[0]
>>> hub
<Container: 45ec900b2e>
>>> hub.name
'HUB'
>>> hub.stop()
>>> client.containers.list()
[]
>>> client.containers.run('selenium/hub:3.11.0-bismuth', name = 'HUB', ports = {4444:4444}, detach = True)
Traceback (most recent call last):
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/api/client.py", line 225, in _raise_for_status
    response.raise_for_status()
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=HUB
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/api/container.py", line 410, in create_container
    return self.create_container_from_config(config, name)
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/api/container.py", line 421, in create_container_from_config
    return self._result(res, True)
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/api/client.py", line 231, in _result
    self._raise_for_status(response)
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/api/client.py", line 227, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/sun/PycharmProjects/docker_cluster/venv/lib/python3.5/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/HUB" is already in use by container "45ec900b2e89482442ee42d992ceca96c5d60141f7a0a75922a8383143ae0695". You have to remove (or rename) that container to be able to reuse that name.")
>>> client.containers.run(name = 'HUB', detach = True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: run() missing 1 required positional argument: 'image'
```
Is there no way to specify name and call container by name instead of image, or i missed it out?

**Comment by shin-** [comment]
`Client.containers.run` creates and starts a new container. To start a container that already exists, you should do the following:
```python
hub = client.containers.get('hub')
hub.start()
```

HTH!

**Comment by KOPACb** [comment]
Yawww! i missed it out, thank you!
