### ISSUE TITLE
docker pip installation is broken with pip10+

### ISSUE THREAD

**Issue by kiorky** [docker/docker-py#2001]
17bf6f71c822c6e768e377f8f675c8094994bba5 from #1990 is only a partial fix.

setup.py has to be fixed.

```
/usr/bin/pip --version
pip 10.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

pip install --ignore-installed --no-deps --no-binary ':all:' "https://github.com/docker/docker-py/archive/2dcedec7c99da00ba282a669abcdb055acf7cec7.zip#egg=docker[tls]"
The directory '/home/gagaro/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/gagaro/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting docker[tls] from https://github.com/docker/docker-py/archive/2dcedec7c99da00ba282a669abcdb055acf7cec7.zip#egg=docker[tls]
  Downloading https://github.com/docker/docker-py/archive/2dcedec7c99da00ba282a669abcdb055acf7cec7.zip
     / 286kB 790kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-UvPGAE/docker/setup.py", line 12, in <module>
        if 'docker-py' in [x.project_name for x in pip.get_installed_distributions()]:
    AttributeError: 'module' object has no attribute 'get_installed_distributions'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-UvPGAE/docker/

```

ref #1993

**Comment by shin-** [comment]
Thanks! I went ahead and removed the check altogether (accb9de52f6e383ad0335807f73c8c35bd6e7426) as I believe it is no longer useful.
