### ISSUE TITLE
Duplicate auth modules in pypi release

### ISSUE THREAD

**Issue by dzervas** [docker/docker-py#2031]
I'm running on docker-py 3.3.0 and this happens on docker-compose:

```
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/home/dzervas/.docker/config.json', '/home/dzervas/.dockercfg']
docker.utils.config.find_config_file: No config file found
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.21.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 121, in get_project
    host=host, environment=environment
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 92, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib/python3.6/site-packages/compose/cli/docker_client.py", line 120, in docker_client
    client = APIClient(**kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 110, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

Nailed down the problem:

```
> ll /usr/lib/python3.6/site-packages/docker/
Permissions Size User Group Date Modified Name
.rw-r--r--   172 root root  26 Apr  3:55  __init__.py
drwxr-xr-x     - root root  18 May 10:36  __pycache__/
drwxr-xr-x     - root root  18 May 10:36  api/
drwxr-xr-x     - root root  19 Apr 18:49  auth/
.rw-r--r--  9.8k root root  26 Apr  3:55  auth.py
.rw-r--r--  6.7k root root  26 Apr  3:55  client.py
.rw-r--r--   571 root root  26 Apr  3:55  constants.py
.rw-r--r--  4.4k root root  26 Apr  3:55  errors.py
drwxr-xr-x     - root root  18 May 10:36  models/
drwxr-xr-x     - root root  19 Apr 18:49  ssladapter/
.rw-r--r--  4.3k root root  26 Apr  3:55  tls.py
drwxr-xr-x     - root root  18 May 10:36  transport/
drwxr-xr-x     - root root  18 May 10:36  types/
drwxr-xr-x     - root root  18 May 10:36  utils/
.rw-r--r--    91 root root  26 Apr  3:55  version.py
```

Both `auth.py` and `auth/__init__.py` exist. Although, `auth` directory does not exist on the current master, neither on 3.3.0-release, should be a mistake during the pypi packing/upload

NOTE: Removing the `auth` folder solves the problem

**Comment by TomasTomecek** [comment]
Does this happen on a fresh installation? Couldn't it be caused by an upgrade?

**Comment by dzervas** [comment]
I think so - but test it again
I installed it through `pacman` on Arch linux

**Comment by shin-** [comment]
@dzervas See also #1916 , #1968
