### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by bcnewlin** [docker/docker-py#2075]
I am using docker-py to run a test suite using docker containers. Everything works fine when I run a subset of the tests, but when I try to run the full suite I begin to get ConnectionErrors being thrown by docker-py when trying to communicate to the docker host. They are thrown from various sources, from reading logs to querying exec status. The example below is from querying the status of an exec job.

Is it possible docker-py is not closing socket connections properly and is exhausting the docker host resources? Or is it just not handling the EINPROGRESS socket status properly?

The errors occur in both 3.3 and 3.4, but did not occur in 2.7.

Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/docker/api/exec_api.py", line 98, in exec_inspect
    res = self._get(self._url("/exec/{0}/json", exec_id))
  File "venv/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "venv/lib/python2.7/site-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "venv/lib/python2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "venv/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "venv/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "venv/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.99.100', port=2376): Max retries exceeded with url: /v1.35/exec/19f91b02b6eb5e2a3d0ad82789473da8b186faf1da8dcfa34dbc226b72663df0/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10d810710>: Failed to establish a new connection: [Errno 36] Operation now in progress',))

**Comment by bcnewlin** [comment]
I neglected to include that I am using docker-machine to run these tests on MacOS 10.13.5 with Virtualbox Version 5.2.12 r122591 (Qt5.6.3). I have upgraded my boot2docker image to the latest but the errors remain.

Since reporting this issue I have installed Docker for Mac and verified that the errors do not occur. However, I am seeing other erroneous behavior with Docker for Mac that makes it an unsuitable replacement for docker-machine at this time.

**Comment by TomasTomecek** [comment]
I suggest reporting at "Docker for Mac" issue tracker.

**Comment by bcnewlin** [comment]
The error does not occur when using Docker for Mac, so I don't know how I could report it there. I considered that it may be a Docker Machine issue, but I decided to open it here as I believed that docker-py should be properly handling EINPROGRESS responses on attempts to open sockets to the Docker daemon.
