### ISSUE TITLE
timeout during commit

### ISSUE THREAD

**Issue by stefanseefeld** [docker/docker-py#2076]
Hello,

I'm using the Python SDK to prototype some in-house CI platform. my script will perform the following steps:

* build a custom image
* start a container
* execute a set of build steps

Whenever one of the build steps fail, the container is stopped, and committed to a new image for analysis. It's during the call to commit that I receive this stack trace:
```
Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/stefan/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

I have run my script on a smaller test project where everything works fine. It's when I switch to my real project that I get the above timeout. What exactly is causing this timeout ? It seems the image was committed correctly nonetheless, i.e. the timeout is generated after the image generation. How can I prevent this from happening ? Are there some config settings I can fine-tune ?

**Comment by stefanseefeld** [comment]
Here is a complete traceback. I'm getting this reliably, on different machines.
Interestingly enough, the actual `docker commit` operation seems to have succeeded.

```
Traceback (most recent call last):
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/.local/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/administrator/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ci.py", line 288, in <module>
    sys.exit(0 if main(sys.argv) else 1)
  File "./ci.py", line 281, in main
    c.commit('ci')
  File "./ci.py", line 188, in commit
    self._container.commit(repository=repository, tag=tag)
  File "/home/administrator/.local/lib/python3.5/site-packages/docker/models/containers.py", line 124, in commit
    **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/docker/api/container.py", line 143, in commit
    self._post_json(u, data=conf, params=params), json=True
  File "/home/administrator/.local/lib/python3.5/site-packages/docker/api/client.py", line 257, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/docker/api/client.py", line 194, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/administrator/.local/lib/python3.5/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by TomasTomecek** [comment]
Does increasing the timeout value solve the problem? https://docker-py.readthedocs.io/en/stable/client.html#creating-a-client

**Comment by stefanseefeld** [comment]
I will give it a try. What is the default value ?

**Comment by TomasTomecek** [comment]
The error message says it. It's `60`. If your image is big, `600` could be a good candidate.
