### ISSUE TITLE
socket.timeout: timed out while streaming log

### ISSUE THREAD

**Issue by felixsiju** [docker/docker-py#2077]
The script i am executing is a time taking one.

res = client.api.exec_start(res, stream=True)

for val in res:
    print (val)

Traceback (most recent call last):
  File "/home//PythonTest/RemoteAPI.py", line 117, in <module>
    for val in res:
  File "/home//.local/lib/python2.7/site-packages/docker/utils/socket.py", line 72, in frames_iter
    n = next_frame_size(socket)
  File "/home//.local/lib/python2.7/site-packages/docker/utils/socket.py", line 59, in next_frame_size
    data = read_exactly(socket, 8)
  File "/home//.local/lib/python2.7/site-packages/docker/utils/socket.py", line 44, in read_exactly
    next_data = read(socket, n - len(data))
  File "/home//.local/lib/python2.7/site-packages/docker/utils/socket.py", line 30, in read
    return socket.recv(n)
socket.timeout: timed out

**Comment by felixsiju** [comment]
Any Suggestions?

**Comment by TomasTomecek** [comment]
Did you try to increase the timeout? https://docker-py.readthedocs.io/en/stable/client.html#creating-a-client

**Comment by felixsiju** [comment]
@TomasTomecek  Tried it and that worked 
Thanks

closed the issue
