### ISSUE TITLE
404 on containers.create for valid images

### ISSUE THREAD

**Issue by etienne-napoleone** [docker/docker-py#2101]
tested under:

Python 3.6.5
Docker version 17.12.1-ce, build 7390fc6
docker 3.4.1

and

Python 3.7.0
Docker version 18.06.0-ce, build 0ffa825
docker 3.4.1

When running
```python
>>> import docker as dockerpy
>>> _client = dockerpy.from_env()
>>> container = _client.containers.create(image='tomochain/infra-telegraf:devnet', name='telegraf')
Traceback (most recent call last):
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=telegraf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/etienne/Library/Caches/pypoetry/virtualenvs/tmn-py3.7/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: tomochain/infra-telegraf:devnet")
```
If I use the docker client:
```
➜ docker pull tomochain/infra-telegraf:devnet
devnet: Pulling from tomochain/infra-telegraf
55cbf04beb70: Downloading [===============>                                   ]  14.27MB/45.31MB
1607093a898c: Downloading [=====================>                             ]  4.586MB/10.74MB
9a8ea045c926: Download complete
9dbf507f8efa: Downloading [==>                                                ]  817.9kB/15.96MB
b7bbc4db97cd: Waiting
b8898b2dd4b3: Waiting
595512eec936: Waiting
d4bd43885499: Waiting
```
Works fine. And after that there will be no exceptions as the images are already present locally
It also works with the images.pull function:
```
>>> client.images.pull('tomochain/infra-telegraf:devnet')
<Image: 'tomochain/infra-telegraf:devnet'>
```

**Comment by mitar** [comment]
Have you figured out what was wrong?

**Comment by etienne-napoleone** [comment]
@mitar Nope, ended up pulling the image if the this exception is raised :man_shrugging:

**Comment by Bnjmn83** [comment]
Same issue here, _docker-py_ not usable at all.

**Comment by inhumantsar** [comment]
just want to chime in. i had the same issue and worked around it by using Docker CLI to pull the image before attempting to use docker-py. 

@etienne-napoleone this issue probably shouldn't have been closed

**Comment by starboarder2001** [comment]
I suddenly started running into this issue with docker-py.  Why was this issue closed without a resolution other than a workaround of not using docker-py?

**Comment by boundless-thread** [comment]
Experiencing the same here

**Comment by etienne-napoleone** [comment]
Reopening I guess

**Comment by yehoshuadimarsky** [comment]
Update - I upgraded docker-py from 4.1 to 4.4.1 and the issue seems fixed.

**Comment by etienne-napoleone** [comment]
If someone else can confirm, I will close this issue

**Comment by juledwar** [comment]
I'm using 5.0.0 and it still happens randomly.

**Comment by bregydoc** [comment]
Same here, version 5.0.0.

**Comment by bruce-szalwinski** [comment]
Success on mac with `pull()` under following configuration

docker: 20.10.6
docker-py: 5.0.0 
python: 3.8

I then bundle the code in a container and deploy to AWS ECS where docker is 19.03.  `pull()` fails with 

```
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.40/images/xxx.dkr.ecr.my-region.amazonaws.com/my-repo:my-version/json: Not Found ("no such image: xxx.dkr.ecr.my-region.amazonaws.com/my-repo:my-version No such image: xxx.dkr.ecr.my-region.amazonaws.com/my-repo:my-version")
```

If I log into the host container in the ECS cluster and pull the container using docker cli, I'm successful.  Then pulling using docker-py is successful.

**Comment by paritoshpr** [comment]
Can confirm this is happening with version 5.0.2

**Comment by billyvg** [comment]
We're seeing this happen intermittently in CI on GitHub Actions.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/yandex/clickhouse-server:20.3.9.70/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry', 'console_scripts', 'sentry')())
  File "/.pip/sentry/src/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/.pip/sentry/src/sentry/runner/commands/devservices.py", line 217, in up
    _start_service(
  File "/.pip/sentry/src/sentry/runner/commands/devservices.py", line 279, in _start_service
    client.images.pull(options["image"])
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 449, in pull
    return self.get('{0}{2}{1}'.format(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/image.py", line 244, in inspect_image
    return self._result(
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: yandex/clickhouse-server:20.3.9.70: No such image: yandex/clickhouse-server:20.3.9.70")
```

**Comment by maggie0002** [comment]
Oddly `_raise_for_status` is a function used to call the error which doesn’t receive the function that called `_raise_for_status`. Not sure where to start looking.

**Comment by RyanGannon-Embark** [comment]
I was seeing this locally for a few days on Ubuntu 22.10, and even reproduced bizarre, seemingly contradictory output like this in `ipython`:
```
In [4]: client.images.list()
Out[4]: 
[List of old, unused images from...somewhere?]

In [5]: !docker images --all
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
[nothing]
```
I dug deeper and found, buried in `~/.docker/contexts/meta/[long hash]]/meta.json`, that my CLI docker was connecting to a socket in my `~/.local` directory, whereas `docker.from_env()` was connecting to `/var/run/docker` **because I had not explicitly set/exported DOCKER_HOST**.

Adding `export DOCKER_HOST=[the correct host]` and re-sourcing my shell fixed this for me.  Hopefully this is helpful for someone stumbling upon this in the future.

**Comment by sylvainv** [comment]
I am using

```
client.images.build
```

instead of 


```
client.api.build
```

before creating my container based on that image. So far so good.

**Comment by patrickdk77** [comment]
I was having the same issue, I had 12g of free diskspace, downloading a 6g image, I used client.image.pull, and got no error, but when doing a client.containers.run, it got the 404, image not found issue.

When I used docker pull cli, it worked fine.
After finding this bug report, I added another 20g of diskspace, and things worked without problems.

Maybe client.image.pull should return an error if the image doesn't actually download?

**Comment by TMUNYU** [comment]
Ran into this issue while trying to run a docker container via jupyter notebooks.

The issue for me seems to have been related to the docker daemon endpoint. I needed to expose it without TLS.
![image](https://github.com/docker/docker-py/assets/1405525/134f0df2-b12d-4128-be28-861c9d648749)
