### ISSUE TITLE
docker.errors.DockerException: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.

### ISSUE THREAD

**Issue by muf3e** [docker/docker-py#2107]
I'm getting this error since beginning. I tried to solve it from many ways, tried many other articles on same issue but nothing happen. If anyone knows what to do please tell me.
I'm using ubuntu 18.04 LTS on virtual box 
My base OS is windows 10

```
[2018-08-09 11:15:49,528] Making new env: flashgames.DuskDrive-v0
[2018-08-09 11:15:49,572] Writing logs to file: /tmp/universe-24594.log
[2018-08-09 11:15:49,591] Connection pool is full, discarding connection: localhost
Traceback (most recent call last):
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mystery/.local/lib/python3.6/site-packages/docker/client.py", line 116, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/mystery/.local/lib/python3.6/site-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/home/mystery/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/mystery/.local/lib/python3.6/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 565, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _get_timeout
    return Timeout.from_float(timeout)
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/home/mystery/.local/lib/python3.6/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gymtest1.py", line 5, in <module>
    env.configure(remotes=1)  # automatically creates a local docker container
  File "/home/mystery/universe/universe/wrappers/timer.py", line 14, in configure
    self.env.configure(**kwargs)
  File "/home/mystery/universe/universe/wrappers/render.py", line 21, in configure
    self.env.configure(**kwargs)
  File "/home/mystery/universe/universe/wrappers/throttle.py", line 32, in configure
    self.env.configure(**kwargs)
  File "/home/mystery/universe/universe/envs/vnc_env.py", line 199, in configure
    use_recorder_ports=record,
  File "/home/mystery/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/mystery/universe/universe/remotes/docker_remote.py", line 44, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/home/mystery/universe/universe/remotes/docker_remote.py", line 163, in __init__
    self.client, self.info = get_client()
  File "/home/mystery/universe/universe/remotes/docker_remote.py", line 157, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/home/mystery/.local/lib/python3.6/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/home/mystery/.local/lib/python3.6/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
```

**Comment by shin-** [comment]
https://github.com/docker/docker-py/search?q=must+be+an+int+or+float&type=Issues

Make sure you use `pip` and don't depend on Ubuntu's vendored files for your Python dependencies (namely `urllib3` and `requests`).

**Comment by lovisharma1** [comment]
Hi,

Am getting the same error, may i know how the above issue has been resolved.


TASK [local_docker : Create /var/lib/awx directory] ****************************
ok: [localhost]

TASK [local_docker : Create Docker Compose Configuration] **********************
ok: [localhost] => (item=environment.sh)
ok: [localhost] => (item=credentials.py)
ok: [localhost] => (item=docker-compose.yml)

TASK [local_docker : Render SECRET_KEY file] ***********************************
ok: [localhost]

**TASK [local_docker : Start the containers] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: Timeout value connect was Timeout(connect=10, read=10, total=None), but it must be an int or float."}**
        to retry, use: --limit @/home/piscda9/awx/installer/install.retry

PLAY RECAP *********************************************************************
