### ISSUE TITLE
Docker API fails to retrieve an image accessible via "docker pull"

### ISSUE THREAD

**Issue by ividal** [docker/docker-py#2115]
Hi,

The scenario is as follows:
* Ubuntu 17.10
* docker version 17.12.1-ce
* Python 3.6
* (python package) docker==3.5.0
* (python package) docker-pycreds==0.3.0
* private docker registry (to which the user has credentials)
* user requires an http + https proxy (configured in `/etc/systemd/system/docker.service.d/http-proxy.conf`)
* `docker login $private_registry` works :heavy_check_mark: 
* `docker pull $image` works :heavy_check_mark: 
* however, pulling via the docker python api fails to authenticate, yielding the error message:

```
2018-08-09T09:01:09,184 DEB connectionpool --- http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 90
2018-08-09T09:01:09,189 DEB connectionpool --- http://localhost:None "GET /v1.35/containers/8a1e8879fb4b5028728ebbca9f1dc275af90a13618ce57fa19147d745d977a3d/json HTTP/1.1" 200 None
2018-08-09T09:01:09,445 DEB connectionpool --- http://localhost:None "POST /v1.35/containers/8a1e8879fb4b5028728ebbca9f1dc275af90a13618ce57fa19147d745d977a3d/start HTTP/1.1" 500 139
2018-08-09T09:01:09,447 ERR cli --- 500 Server Error: Internal Server Error ("OCI runtime create failed: json: cannot unmarshal object into Go struct field Process.capabilities of type []string: unknown")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/8a1e8879fb4b5028728ebbca9f1dc275af90a13618ce57fa19147d745d977a3d/start
```

Would you have any hints as to what could be going on?

Thanks!

**Comment by shin-** [comment]
Doesn't look like an issue with your pull or your authentication - the relevant error is `"OCI runtime create failed: json: cannot unmarshal object into Go struct field Process.capabilities of type []string: unknown`, and it seems to happen when hitting the `/v1.35/containers/<id>/start` endpoint (usually through `APIClient.start()`, `Container.start()` or `DockerClient.containers.run()`). 

This issue seems relevant: https://github.com/docker/for-linux/issues/61

**Comment by ividal** [comment]
Thanks for the info. Actually, I think by the time we get to the run/start part, we already have a problem. The "pull" happens too fast, which makes me think it's retrieving an error page from our registry and not really pulling a docker image (bear in mind we use proxies - just to make things interesting).

My question for you: is there any chance that the docker python API tries to retrieve images via a different port than "docker pull" from the command line?

Thanks again!

**Comment by shin-** [comment]
No, if there was an error with the pull at any level that would be reported as such in the API, unless your proxy errors are really good at disguising as valid JSON for some reason.

As for the port used, since that is handled by the daemon rather than the client, there's no reason that it would use a different port if provided with the same parameters.
