### ISSUE TITLE
run output empty, non-deterministic

### ISSUE THREAD

**Issue by knorx** [docker/docker-py#2117]
# Environment
```
docker==3.5.0
docker-pycreds==0.3.0
Python 3.6.5
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
OS | Docker
--- | -----------------------------------------------
`Microsoft Windows [Version 10.0.16299.547]` | Docker for Windows, Community Edition

# Issue
I am getting non-deterministic output from a docker run command executed via the docker-py api. A `cat` command should output the content of a file for a test but the returned text is an empty byte string (`b''`) in some scenarios. When you manually check the output of the corresponding container via `docker logs <container>` afterwards, the correct output is printed. This is similar to the issue described in #1924. I attached a minimal example to reproduce the problem [as a zip file (errorTest_docker-py.zip)](https://github.com/docker/docker-py/files/2287805/errorTest_docker-py.zip).

# Reproducing
## Test-Scenario
I did a very stupid Dockerfile which is basically Ubuntu with a very stupid python-generated `.zip` file which is copied to root on build. The test now executes a `cat`-statement on the archive, which should return the archive's content. This is repeated 20 times. for me it fails in differing iterations. Sometimes it fails directly in the first iteration, sometimes it fails in the second, and so on.

## Steps to reproduce:
* Unpack the archive, switch to that directory
* `docker build -t docker-py .`
* execute the unit test by running: `python errorTest.py`. If the test fails, the error occurred.

**Comment by shin-** [comment]
Hm, I tried using your zip file but I'm not able to reproduce (Windows 10, Python 3.6.4)
```
python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
PS C:\Users\joffrey\work\tests\repro2117> python .\errorTest.py
.
----------------------------------------------------------------------
Ran 1 test in 5.101s

OK
PS C:\Users\joffrey\work\tests\repro2117> python .\errorTest.py
.
----------------------------------------------------------------------
Ran 1 test in 5.185s

OK
PS C:\Users\joffrey\work\tests\repro2117> python .\errorTest.py
.
----------------------------------------------------------------------
Ran 1 test in 5.146s

OK
PS C:\Users\joffrey\work\tests\repro2117> python .\errorTest.py
.
----------------------------------------------------------------------
Ran 1 test in 5.098s

OK
PS C:\Users\joffrey\work\tests\repro2117> python .\errorTest.py
.
----------------------------------------------------------------------
Ran 1 test in 4.944s

OK
```

**Comment by knorx** [comment]
Hey, of course - why should it be reproducible on your side ... that would make it easy to solve. 😆 See output on my side below. So what is the difference here? The funny thing is, if I change the command run on the container from `cat` to e.g. a hash with `sha224sum`, the error does not appear on my side as well.
I had the feeling that it has sth. to do with the binary symbols of the archive being printed. The reason for this assumption is that another clue was: When I do `cat` on a small binary like e.g. `/bin/hostname`, I also did not see the error. It drives me crazy. I once managed to debug into the `containers.py` on line 789 where the output is returned. The response object there had the empty byte string in it, while `docker logs` on command line returned the correct output like here:
```
R:\tmp\docktest>docker logs fervent_keldysh
PK     3~�<g         network_fileNetworkContentPK      3~�<g                 �    network_filePK    
```

# Error-Test on my side:
```

R:\tmp\docktest>docker build -t docker-py .
Sending build context to Docker daemon  4.608kB
Step 1/2 : FROM ubuntu:16.04
 ---> 7aa3602ab41e
Step 2/2 : COPY archive.zip /
 ---> Using cache
 ---> a5fc1fb1b8a3
Successfully built a5fc1fb1b8a3
Successfully tagged docker-py:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

R:\tmp\docktest>python errorTest.py
F
======================================================================
FAIL: testLogs (__main__.LogReturnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "errorTest.py", line 14, in testLogs
    self.assertNotEqual(b'', output, msg="iteration #{}".format(i))
AssertionError: b'' == b'' : iteration #1

----------------------------------------------------------------------
Ran 1 test in 1.100s

FAILED (failures=1)

R:\tmp\docktest>python errorTest.py
F
======================================================================
FAIL: testLogs (__main__.LogReturnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "errorTest.py", line 14, in testLogs
    self.assertNotEqual(b'', output, msg="iteration #{}".format(i))
AssertionError: b'' == b'' : iteration #2

----------------------------------------------------------------------
Ran 1 test in 2.559s

FAILED (failures=1)

R:\tmp\docktest>python errorTest.py
F
======================================================================
FAIL: testLogs (__main__.LogReturnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "errorTest.py", line 14, in testLogs
    self.assertNotEqual(b'', output, msg="iteration #{}".format(i))
AssertionError: b'' == b'' : iteration #4

----------------------------------------------------------------------
Ran 1 test in 5.614s

FAILED (failures=1)
```

**Comment by inkychris** [comment]
I'm experiencing the same issue. The issue is caused by the `process` isolation mode on Windows 18.09. Using `hyperv` isolation appears to be fine. I ran the following on Windows Server LTS2019 and the process mode test fails fairly consistently:
```dockerfile
# Dockerfile
FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator
RUN echo Hello from Docker! > hello.txt
CMD ["cmd", "/C", "type", "C:\\hello.txt"]
```
```python
# test.py
import docker
import unittest


def run(mode):
    client = docker.from_env()
    return client.containers.run('test:latest', isolation=mode)


class TestDockerRunOutput(unittest.TestCase):
    def test_hyperv(self):
        self.assertIn(b'Hello from Docker!', run('hyperv'))

    def test_process(self):
        self.assertIn(b'Hello from Docker!', run('process'))


if __name__ == '__main__':
    for i in range(8):
        unittest.main(exit=False)
```
Example output:
```
(.venv) PS C:\Users\Administrator\Desktop> python test.py
.F
======================================================================
FAIL: test_process (__main__.TestDockerRunOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 15, in test_process
    self.assertIn(b'Hello from Docker!', run('process'))
AssertionError: b'Hello from Docker!' not found in b''

----------------------------------------------------------------------
Ran 2 tests in 3.194s

FAILED (failures=1)
.F
======================================================================
FAIL: test_process (__main__.TestDockerRunOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 15, in test_process
    self.assertIn(b'Hello from Docker!', run('process'))
AssertionError: b'Hello from Docker!' not found in b''

----------------------------------------------------------------------
Ran 2 tests in 2.964s

FAILED (failures=1)
..
----------------------------------------------------------------------
Ran 2 tests in 3.218s

OK
..
----------------------------------------------------------------------
... etc ...
```
I then tried on Windows 10 Pro 20.04, changing the nanoserver base image tag to 2004 and the script ran through fine again. Both machines are running Docker 19.03.13. This seems to be an issue specifically with (at least) 18.09 and is resolve at least in 20.04.
