### ISSUE TITLE
How to load super big size image via docker api?

### ISSUE THREAD

**Issue by wekay102200** [docker/docker-py#2119]
Hi,master:
my image size is 2GB,size,when I use docker api like blow:
f = open(image_tar,"rb")
client = docker.Client(base_url='unix://var/run/docker.sock',version = '1.37',timeout = 60)
client.load_image(f.read())
f.close()

it throw error:
UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

if I load small size image,it work ok!
But when I load image size exceed 2GB,it work abnormal.
How to solve this problem?
thanks very much!

**Comment by wekay102200** [comment]
the detail error information is below:
Traceback (most recent call last):
  File "test_core.py", line 51, in <module>
    load_image("/home/ubuntu/wgs_image_gatk3.7.tar","")
  File "test_core.py", line 29, in load_image
    ret = client.load_image(f.read())
  File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 140, in load_image
    res = self._post(self._url("/images/load"), data=data)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 135, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

**Comment by wekay102200** [comment]
But when I use docker load <xxxx.tar command,it has no problem when load image size exceed 2GB.

**Comment by TomasTomecek** [comment]
https://github.com/docker/docker-py/issues/2076#issuecomment-404757752

**Comment by shin-** [comment]
Closing as a duplicate - but we do need to address this.

**Comment by wekay102200** [comment]
@TomasTomecek @shin- 
Hi Master:
when i set timeout to 600,it still run error.
Traceback (most recent call last):
  File "test_core.py", line 51, in <module>
    load_image("/home/ubuntu/wgs_image_gatk3.7.tar","")
  File "test_core.py", line 29, in load_image
    ret = client.load_image(f.read())
  File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 140, in load_image
    res = self._post(self._url("/images/load"), data=data)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 135, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)

**Comment by TomasTomecek** [comment]
So try even bigger number then: 60000. Are you doing it over network or locally?

**Comment by wekay102200** [comment]
@TomasTomecek i do it locally.when i use docker load xxxx.tar command ,it only spend less then 1 minute to load 2GB image.but when i use docker api to load,it occur the timeout error above.

**Comment by TomasTomecek** [comment]
hm, so it seems that docker-py does the I/O inefficiently and this may indeed be a bug

**Comment by shin-** [comment]
@TomasTomecek I don't know if I agree with that. I'm actually getting slightly better times with the Python API on average than I am with the CLI on my laptop, although with very high variance (getting 10s - 1m ranges on all 3 tests):
```
$ python --version
Python 3.7.0

$ pip show docker
Name: docker
Version: 3.5.0

$ ls -lh
total 2.0G
-rw------- 1 joffrey joffrey 2.0G Aug 21 11:07 bigimg.tar
-rw-rw-r-- 1 joffrey joffrey  115 Aug 21 11:15 test1.py
-rw-rw-r-- 1 joffrey joffrey  108 Aug 21 11:15 test2.py

$ time docker load -i bigimg.tar
Loaded image: bigimg:latest

real    0m51.426s
user    0m0.416s
sys 0m1.372s

$ time python test1.py

real    0m38.432s
user    0m0.196s
sys 0m1.968s


$ time python test2.py

real    0m24.617s
user    0m1.164s
sys 0m1.612s

```

```python
# test1.py
import docker

c = docker.APIClient(timeout=120)

with open('./bigimg.tar', 'rb') as f:
    c.load_image(f.read())
```

```python
# test2.py
import docker

c = docker.APIClient(timeout=120)

with open('./bigimg.tar', 'rb') as f:
    c.load_image(f)
```

Testing on a small EC2 instance gives me more stable results where performance is pretty much identical:
```
$ time docker load -i bigimg.tar 
6e53fbb1bdaf: Loading layer  2.147GB/2.147GB
Loaded image: bigimg:latest

real	1m6.209s
user	0m0.812s
sys	0m1.600s

$ time python test2.py 

real	1m6.354s
user	0m1.024s
sys	0m1.924s
```

(Unfortunately this instance is too small to load the entire file in memory with `f.read()` resulting in a memory error for `test1.py`, but it's probably a bad idea to do that anyway)

**Comment by TomasTomecek** [comment]
@shin- That's actually pretty good point. It may be possible that @wekay102200's problem is that the machine starts to swap.
