### ISSUE TITLE
`Cannot locate specified Dockerfile` error when building images

### ISSUE THREAD

**Issue by LazarusX** [docker/docker-py#2127]
docker-py version: 3.5
Python version: 3.6.5
Docker version: Docker version 18.06.0-ce, build 0ffa825, Linux container mode on Windows
OS: Windows 10 Version 1803 Build 17134.228

Steps to reproduce:
1. `git clone https://github.com/LazarusX/docker-py-repro.git`
1. `cd docker-py-repro`
1. `virtualenv venv`
1. `.\venv\Scripts\activate.ps1`
1. `pip install -r requirements.txt`
1. `python main.py`
1. See below errors:
```
Tag: my-hello-world
Context path: C:\Users\<username>\Projects\docker-py-repro
Dockerfile path: C:\Users\<username>\Projects\docker-py-repro\folder\folder\Dockerfile
Traceback (most recent call last):
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\api\client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.35/build?t=my-hello-world&q=False&nocache=False&rm=False&forcerm=False&pull=False&dockerfile=folder%5Cfolder%5CDockerfile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\main.py", line 15, in <module>
    docker_client.images.build(tag=tag, path=context, dockerfile=dockerfile)
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\models\images.py", line 264, in build
    for chunk in internal_stream:
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\utils\json_stream.py", line 66, in split_buffer
    for data in stream_as_text(stream):
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\utils\json_stream.py", line 22, in stream_as_text
    for data in stream:
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\api\client.py", line 320, in _stream_helper
    yield self._result(response, json=decode)
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\api\client.py", line 235, in _result
    self._raise_for_status(response)
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\api\client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Users\<username>\Projects\docker-py-repro\venv\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: folder\folder\Dockerfile")
```

Workaround:
1. Comment the `docker_client.images.build(tag=tag, path=context, dockerfile=dockerfile)` line
1. `python main.py`

**Comment by davclark** [comment]
This seems like an easy fix and is catastrophic for anyone doing programmatic builds on Windows. Is there any reason it's not fixed (@LazarusX  provides one fix in his git repo).

I'm guessing this may be due to the continued situation with confusion around paths on Docker for Windows? I can say fairly definitively that there is simply no right answer at this point, and I haven't seen any uptake on core devs (Docker, Docker Compose...) on documenting a right answer.

So, I think it's OK to just pick something for now. I would propose that at a minimum, native windows paths (such as would be generated by `os.path.abspath('.')`) should "just work."

I'm happy to submit a PR if folks like @LazarusX' fix (or they can).
