### ISSUE TITLE
"Invalid volume specification" when trying to use the :Z option

### ISSUE THREAD

**Issue by Kazade** [docker/docker-py#2138]
I'm converting some code that previously used subprocess to work with Docker, and I'm down to the last call which is a call to run like this:

```
    volume_mount = "{}:/simulant-project:Z".format(abspath("."))
    client.containers.run(
        "kazade/dreamcast-sdk",
        "bash --login",
        detach=True,
        volumes=[volume_mount],
        tty=True,
        stdin_open=True,
        name=DOCKER_CONTAINER_NAME,
        working_dir=working_dir
    )
```
If I change volume_mount to remove the `:Z` option then the mount succeeds but the files in the mount aren't visible from inside the container. If I add the `:Z` option (which was previously required when using subprocess due to selinux) I get the following:

```
Traceback (most recent call last):
  File "/home/kazade/Work/Home/simulant-tools/simulant", line 846, in <module>
    sys.exit(main())
  File "/home/kazade/Work/Home/simulant-tools/simulant", line 842, in main
    return COMMAND_LOOKUP[opts.subcommand](opts)
  File "/home/kazade/Work/Home/simulant-tools/simulant", line 610, in package
    build(Args(), output)
  File "/home/kazade/Work/Home/simulant-tools/simulant", line 232, in build
    _start_docker_container(container_build_dir)
  File "/home/kazade/Work/Home/simulant-tools/simulant", line 463, in _start_docker_container
    working_dir=working_dir
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/kazade/.local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid volume spec "/simulant-project:Z": invalid volume specification: '/simulant-project:Z'")
```

How do I supply the `:Z` option correctly?

**Comment by Kazade** [comment]
Typically solved it immediately after posting this. The solution was:

```
    client.containers.run(
        "kazade/dreamcast-sdk",
        "bash --login",
        detach=True,
        volumes={
            abspath("."): {
                "bind": "/simulant-project",
                "mode": "Z"
            }
        },
        tty=True,
        stdin_open=True,
        name=DOCKER_CONTAINER_NAME,
        working_dir=working_dir
    )
```
