### ISSUE TITLE
ConnectionRefusedError 

### ISSUE THREAD

**Issue by statiksof** [docker/docker-py#2176]
Any idea about this issue?
Docker version: 18.09
Python: 3.6.5

``` File "/opt/conda/lib/python3.6/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/conda/lib/python3.6/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))```

**Comment by StanSilas** [comment]
@statiksof  @Datamance  What was the cause and How did you resolve it?
We are running into the exact same issue at random. 
Thank you

**Comment by himito** [comment]
I have the same error, 
@statiksof  how did you solve the problem? 
Thank you in advance.

**Comment by milas** [comment]
`ConnectionRefusedError` is a generic network-level error when the Docker Engine API cannot be reached.

If you're accessing a local Docker install, make sure that it's running. If it's a remote instance, ensure ports are open, etc.

You can always test with the Docker CLI by setting `DOCKER_HOST` env var or passing the `--host` / `-H` flag.

I'm going to lock this issue now as it's quite old and thus far nothing here has pointed to an issue with `docker-py` rather than generic configuration issues.
