### ISSUE TITLE
Cannot use SSH adapter after close

### ISSUE THREAD

**Issue by rumpl** [docker/docker-py#2248]
When connecting over SSH it is not possible to do other calls after the connection is closed. However we can still make API calls when connecting on a socket, sample code:

```python
import docker 

client = docker.APIClient(base_url='unix://var/run/docker.sock')
print(client.version()['Version'])
client.close()
print(client.version()['Version'])


ssh_client = docker.APIClient(base_url='ssh://...')
print(ssh_client.version()['Version'])
ssh_client.close()
print(ssh_client.version()['Version'])
```

The output is:
```
18.09.1
18.09.1
18.09.1
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 13, in main
    print(ssh_client.version()['Version'])
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/Users/djordjelukic/.virtualenvs/test-url/lib/python2.7/site-packages/docker/transport/sshconn.py", line 29, in connect
    sock = self.ssh_transport.open_session()
AttributeError: 'NoneType' object has no attribute 'open_session'
```

`docker-compose` [closes the connection for some reason that I don't quite understand](https://github.com/docker/compose/blob/master/compose/service.py#L1098-L1101) I wander if we should remove it from compose...

But in any case I think that the different adapters should work the same way. What do you think?

**Comment by arcenik** [comment]
Hi,

I was abble to reproduce the 10th connection problem using only docker-py on a host with 20 running containers with the following script:

```python
#! /usr/bin/env python

from docker import APIClient
import sys

import logging

logging.basicConfig()
logging.getLogger("paramiko").setLevel(logging.DEBUG)

client = APIClient(base_url='ssh://192.168.x,y)

list = client.containers()
for c in list:
    i = (client.inspect_container(c['Id']))
    print("Inspect returned: {id}".format(id=i['Id']))
    print("#"*200)
    sys.stdout.flush()

print()
print("#"*200)
print("test finished")
```

I've also made a PR with a fix: https://github.com/docker/docker-py/pull/2262
