### ISSUE TITLE
using ssh protocol gives paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted

### ISSUE THREAD

**Issue by ssbarnea** [docker/docker-py#2251]
When trying to use ssh transport to talk with docker, docker-py chokes with belower error complaining that the private key is encrypted when in reality it should connect succesfully as the key is provided by the ssh agent.

Docker cli on the other hand works as expected.

```
export DOCKER_HOST=ssh://localhost
#  ^ can as well be another host, it does not matter.

Traceback (most recent call last):
File "./py-docker", line 5, in <module>
c = docker.from_env()
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/docker/client.py", line 85, in from_env
timeout=timeout, version=version, **kwargs_from_env(**kwargs)
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/docker/client.py", line 40, in __init__
self.api = APIClient(*args, **kwargs)
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/docker/api/client.py", line 162, in __init__
base_url, timeout, pool_connections=num_pools
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/docker/transport/sshconn.py", line 84, in __init__
parsed.hostname, parsed.port, parsed.username,
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
passphrase,
File "/Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
raise saved_exception
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```

This is caused by the fact that current implementation assumes that if `~/.ssh/id_rsa` exists it should be an unencrypted key (which would be something really stupid from securitu point of view).

I can confirm that the ssh agent is working correctly on the machine and that ssh and docker-cli do have not problem accessing the ssh keys from the agent.
```
ssh-add -l
```

**Comment by ssbarnea** [comment]
It proved to be caused by paramiko https://github.com/paramiko/paramiko/issues/1383 -- in case someone else encounters it we could maybe add a runtime warning if the ssh:// url does not contain a user. Missing user does not mean that `~/.ssh/config` one will be used, just mean current user.

`docker` will user the one from ssh config but docker-compose or docker-py would not!
