### ISSUE TITLE
docker.errors.InvalidVersion: Health options were only introduced in API version 1.24 with all packages updated

### ISSUE THREAD

**Issue by FedeG** [docker/docker-py#2321]
Hi, I have a error when docker-compose try run a container with healthcheck.

I added a pdb to docker-py file for check value of `version` variable and it was `1.23` value but I has updated all packages

Full log:
```bash
ERROR: for redis  Health options were only introduced in API version 1.24
Traceback (most recent call last):
  File "/home/fedeg/.local/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/cli/main.py", line 1085, in up
    to_attach = up(False)
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/cli/main.py", line 1081, in up
    silent=options.get('--quiet-pull'),
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/project.py", line 555, in up
    get_deps,
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/project.py", line 541, in do
    renew_anonymous_volumes=renew_anonymous_volumes,
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/service.py", line 533, in execute_convergence_plan
    scale, detached, start
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/service.py", line 455, in _execute_convergence_create
    "Creating"
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/service.py", line 453, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/service.py", line 441, in create_and_start
    container = service.create_container(number=n, quiet=True)
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/service.py", line 337, in create_container
    return Container.create(self.client, **container_options)
  File "/home/fedeg/.local/lib/python3.6/site-packages/compose/container.py", line 52, in create
    response = client.create_container(**options)
  File "/home/fedeg/.local/lib/python3.6/site-packages/docker/api/container.py", line 425, in create_container
    stop_timeout, runtime
  File "/home/fedeg/.local/lib/python3.6/site-packages/docker/api/container.py", line 430, in create_container_config
    return ContainerConfig(self._version, *args, **kwargs)
  File "/home/fedeg/.local/lib/python3.6/site-packages/docker/types/containers.py", line 575, in __init__
    'Health options were only introduced in API version 1.24'
docker.errors.InvalidVersion: Health options were only introduced in API version 1.24
```

#### docker-compose version
```bash
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.2
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

#### docker version        
```bash
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by shin-** [comment]
This should have been reported in Compose. Make sure you've unset `DOCKER_API_VERSION` in your environment (or set it to `1.24` or above).
