### ISSUE TITLE
Build API doesn't accept Path Like objects

### ISSUE THREAD

**Issue by isidentical** [docker/docker-py#2336]
```py
Traceback (most recent call last):
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/batuhan/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/evality/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evality.py", line 12, in obtain_image
    return self._docker_client.images.get('evality')
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/models/images.py", line 295, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: evality: No such image: evality:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evality.py", line 21, in <module>
    evality = Evality(docker_client, api_client)
  File "evality.py", line 8, in __init__
    self._image = self.obtain_image()
  File "evality.py", line 15, in obtain_image
    path = Path(__file__).parent
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/models/images.py", line 258, in build
    resp = self.client.api.build(**kwargs)
  File "/home/batuhan/.local/lib/python3.7/site-packages/docker/api/build.py", line 138, in build
    elif path.startswith(('http://', 'https://',
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

```py
return self._docker_client.images.build(path = Path(__file__).parent)
```

**Comment by jsolbrig** [comment]
I'm a little surprised this hasn't gotten more attention. I suppose the workaround is easy enough (wrap your path in `str()`), but it would be nice if this worked well with `pathlib` since `pathlib` is part of the standard library.
