### ISSUE TITLE
Starting a container with 'npipe' mount results in API error.

### ISSUE THREAD

**Issue by rantonov** [docker/docker-py#2390]
When programmatically create a docker container that communicates with a service running on the host machine and listening on a named pipe (a.k.a. unix socket). I get: 

APIError: 400 Client Error: Bad Request ("invalid mount config for type "npipe": mount type unknown")

My setup includes: 

- Docker version 18.09.7, build 2d0083d 
- Python 2.7.12 
- docker==4.0.1 (from pip freeze)
```
import docker
from docker.types import Mount

mounts = [
    Mount('/tmp/redis.sock', '/tmp/redis.sock', type='npipe'),
    Mount('/opt/data/', '/tmp'),
]

client = docker.from_env()
client.containers.run(
    "alpine", 
    **{
        "command":"sleep 600", 
        "network_mode": "host", 
        "mounts": mounts
    }
)
```
Here is the exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/models/containers.py", line 803, in run
    detach=detach, **kwargs)
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/api/container.py", line 429, in create_container
    return self.create_container_from_config(config, name)
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/api/container.py", line 440, in create_container_from_config
    return self._result(res, True)
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/grok/ve/grok/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("invalid mount config for type "npipe": mount type unknown")
```

**Comment by shin-** [comment]
Named pipe and UNIX sockets are not the same thing. `npipe` mounts are Windows-specific.
You should use the `bind` type in your case.

**Comment by rantonov** [comment]
Thanks! That works!
