### ISSUE TITLE
Cant pass input variable from keyboard to docker/utils/utils.py 

### ISSUE THREAD

**Issue by gdmlnx** [docker/docker-py#2405]
Hi guys, I'm pretty new to the docker api, so basically Im trying to use docker.Client with a python  script using input ip as variable, Im getting this error. any Ideas?.

script -> 
import docker
import re
import sys
ip =  sys.argv[1]
cli = docker.Client(base_url="'http://"+ (ip) +":4243'")

usage : >
python3 docker-jen.py 192.168.1.122

Traceback (most recent call last):
  File "docker-jen.py", line 10, in <module>
    cli = docker.Client(base_url="'http://"+ (ip) +":4243'")
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 59, in __init__
    base_url, constants.IS_WINDOWS_PLATFORM, tls=bool(tls)
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/utils.py", line 415, in parse_host
    "Invalid bind address protocol: {0}".format(addr)
docker.errors.DockerException: Invalid bind address protocol: **'http://192.168.1.122:4243'**

According to utils.py line 415 the error should be generated if no protocol is used,  but in the bold line above I can see it passing thru. what am I doing wrong? if I perform that script using an static ip from the code it works like a charm.

many thanks in advance and sorry if this is a silly question.

**Comment by shin-** [comment]
`http` is not a valid protocol for the Docker API. Use the `tcp://` prefix instead.

**Comment by gdmlnx** [comment]
Hi there Shin! thanks for your quick answer.

inside the same class I found :

if addr == 'tcp://':
        raise errors.DockerException(
            "Invalid bind address format: {0}".format(addr)
        )

so I dont think thats the problem, again If I set the ip static it works.

**Comment by shin-** [comment]
I believe you're using an extremely outdated version of the library. Please upgrade to the latest version, and if you're still having issues, I'll need you to provide the [necessary information](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues) before we can dig any deeper.
