### ISSUE TITLE
SyntaxError credentials: Union[Credentials, str]

### ISSUE THREAD

**Issue by dmitryhruzin** [docker/docker-py#2410]
After the latest update I get the following error:

Signal handler <bound method ?.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7fd3777b4510>> raised: SyntaxError('invalid syntax', ('/usr/local/lib/python2.7/site-packages/apns2/client.py', 41, 29, ' credentials: Union[Credentials, str],\n'))
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 230, in send
response = receiver(signal=self, sender=sender, **named)
File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 82, in on_import_modules
self.worker_fixup.validate_models()
File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 120, in validate_models
self.django_setup()
File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 116, in django_setup
django.setup()
File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
app_config.ready()
File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
self.module.autodiscover()
File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
autodiscover_modules('admin', register_to=site)
File "/usr/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
import_module('%s.%s' % (app_config.name, module_to_search))
File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/usr/local/lib/python2.7/site-packages/push_notifications/admin.py", line 4, in <module>
from .apns import APNSServerError
File "/usr/local/lib/python2.7/site-packages/push_notifications/apns.py", line 9, in <module>
from apns2 import client as apns2_client
File "/usr/local/lib/python2.7/site-packages/apns2/client.py", line 41
credentials: Union[Credentials, str],

**Comment by dmitryhruzin** [comment]
How can I pull the previous version of docker python:2.7?

**Comment by shin-** [comment]
Not related to this library, as far as I can tell. Your problem is somewhere else (likely in the `apns2` package)
