### ISSUE TITLE
Client.containers.list(all=True) fails nondeterministically if some container is being removed in parallel

### ISSUE THREAD

**Issue by bzak9LD** [docker/docker-py#2451]
We have encountered a following issue in following scenario:

**Scenario:**
- Have docker on a node
- Have docker-service with one replica
- Scale service down to zero replicas
- List containers in a loop (waiting for the container of a service to disappear)

**Expected results:**
Eventually created list of the containers has one less element.

**Actual results:**

Nondeterministically the code fails with following backtrace:
```
...
07:40:01    File ..., line 108, in getAllContainerNames
07:40:01      return [container.name for client in self._swarm.clients for container in client.containers.list(all=True)]
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/models/containers.py", line 943, in list
07:40:01      containers.append(self.get(r['Id']))
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/models/containers.py", line 880, in get
07:40:01      resp = self.client.api.inspect_container(container_id)
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
07:40:01      return f(self, resource_id, *args, **kwargs)
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/api/container.py", line 756, in inspect_container
07:40:01      self._get(self._url("/containers/{0}/json", container)), True
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/api/client.py", line 267, in _result
07:40:01      self._raise_for_status(response)
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
07:40:01      raise create_api_error_from_http_exception(e)
07:40:01    File "/tmp/tmp.xrnVzrxn9J/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
07:40:01      raise cls(e, response=response, explanation=explanation)
07:40:01  NotFound: 404 Client Error: Not Found ("No such container: 3701121bed79b3925404c76b5f66a89c0d20fd86eab541fdd85690cecd07aafa")
```

**Reproduction:**
I was able to reproduce this issue with a minimalisic test:
- In first terminal run 
```
import docker
cli = docker.DockerClient()
while True:
   a = cli.containers.list(all=True)
```
- In second terminal run: ```for i in `seq 10`; do docker rm -f `docker run -d busybox tail -F /dev/null`; done``` (in my environment this issue occurs quickly and 10 loop iterations are enough)
Output obtained:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/models/containers.py", line 943, in list
    containers.append(self.get(r['Id']))
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/models/containers.py", line 880, in get
    resp = self.client.api.inspect_container(container_id)
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/api/container.py", line 756, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/bzak/persistentVenv/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: edf87eb0d1906fd2c567f62846922e3b537552fe28f689d761baece250b21145")
```
**Suspicions:**
I believe this is a race condition in which docker-py tries to list containers first and then inspect them. Since those commands are "non-atomic" the list can contain container that is removed immediately thereafter and tries to inspect a non-existing container.

**Additional information:**
Python: `Python 2.7.5`
Docker-py: `4.0.2`
Docker:
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by shin-** [comment]
Use `sparse=True` or `ignore_removed=True`: https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.list

**Comment by bzak9LD** [comment]
It works, thanks a lot!
