### ISSUE TITLE
docker client on Python 3.8 is not working

### ISSUE THREAD

**Issue by SLdragon** [docker/docker-py#2454]
Hi,
After updating to the python to 3.8, docker client is not working, when I try to create a new docker client instance, it would throw exceptions:

```
>>> import docker
>>> docker.DockerClient.from_env(version='auto')

raceback (most recent call last):
  File "D:\Azure IoT Tools\iotedgehubdev\.venv\lib\site-packages\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Azure IoT Tools\iotedgehubdev\.venv\lib\site-packages\docker\client.py", line 84, in from_env
    return cls(
  File "D:\Azure IoT Tools\iotedgehubdev\.venv\lib\site-packages\docker\client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "D:\Azure IoT Tools\iotedgehubdev\.venv\lib\site-packages\docker\api\client.py", line 158, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
```

installed packages:

```
Requirement already satisfied: docker in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (4.1.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from docker) (2.22.0)
Requirement already satisfied: six>=1.4.0 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from docker) (1.12.0)
Requirement already satisfied: websocket-client>=0.32.0 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from docker) (0.56.0)
Requirement already satisfied: pypiwin32==223; sys_platform == "win32" and python_version >= "3.6" in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from docker) (223)       
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from requests!=2.18.0,>=2.14.2->docker) (1.25.6)     
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from requests!=2.18.0,>=2.14.2->docker) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from requests!=2.18.0,>=2.14.2->docker) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from requests!=2.18.0,>=2.14.2->docker) (2019.9.11)
Requirement already satisfied: pywin32>=223 in d:\azure iot tools\iotedgehubdev\venv\lib\site-packages (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker) (225)
```

**Comment by carbonox-infernox** [comment]
I have this problem in python 3.7

**Comment by aaronpburke** [comment]
I'm also experiencing this problem with Python 3.7.4 and Windows 10 1809.

(.venv) c:\Code\ig-control>c:\Code\ig-control\.venv\Scripts\python.exe c:\Users\aburke\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 1258 c:\Code\ig-control\control.py
Traceback (most recent call last):
  File "c:\Code\ig-control\.venv\lib\site-packages\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\aburke\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\aburke\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\aburke\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\aburke\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\aburke\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\aburke\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Code\ig-control\control.py", line 2, in <module>
    client = docker.from_env()
  File "c:\Code\ig-control\.venv\lib\site-packages\docker\client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "c:\Code\ig-control\.venv\lib\site-packages\docker\client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "c:\Code\ig-control\.venv\lib\site-packages\docker\api\client.py", line 159, in __init__
    'Install pypiwin32 package to enable npipe:// support'
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support

(.venv) c:\Code\ig-control>pip install pypiwin32
Requirement already satisfied: pypiwin32 in c:\code\ig-control\.venv\lib\site-packages (223)
Requirement already satisfied: pywin32>=223 in c:\code\ig-control\.venv\lib\site-packages (from pypiwin32) (226)

**Comment by ivan-radic** [comment]
Hi,

py 3.7 is working nicely, thanks for that: https://github.com/docker/docker-py/issues/1926

Can we get support for py 3.8?

```
Collecting pywin32>=223 (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker)
  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker)
```

**Comment by adnilsson** [comment]
I have the same issue for Python 3.8.5 on Windows (OSbuild 19042).

I found two workarounds that worked on my system:
 1. Downgrade to Python 3.7
 2. Downgrade from docker 4.4 to 4.2 (4.3 presented the same issue)

I'm using a virtual environment manged via poetry.

**Comment by milas** [comment]
The version constraints for Pywin32 have been adjusted to avoid issues like this in the upcoming 6.0.0 release.
