### ISSUE TITLE
pip install in virtualenv breaks virtualenv

### ISSUE THREAD

**Issue by casey-boyer-spoke** [docker/docker-py#2460]
Upon installing the docker package in a virtualenv, the virtualenv becomes unusable (can no longer call pip or python).

Error: 
```
(test-env) PS C:\Users\me\PyEnv\test-env> pip -V
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "c:\users\me\pyenv\test-env\lib\site.py", line 769, in <module>
    main()
  File "c:\users\me\pyenv\test-env\lib\site.py", line 746, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "c:\users\me\pyenv\test-env\lib\site.py", line 279, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "c:\users\me\pyenv\test-env\lib\site.py", line 202, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "c:\users\me\pyenv\test-env\lib\site.py", line 170, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "c:\users\me\pyenv\test-env\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: module 'site' has no attribute 'getsitepackages'
```
Windows 10 Pro
Python Version 3.7.5, pip version 19.3.1 (installed for user only)

Steps to reproduce:
```
PS C:\Users\me\AppData\Local\Programs\Python\Python37> .\Scripts\virtualenv.exe C:\Users\me\PyEnv\test-env
PS C:\Users\me\AppData\Local\Programs\Python\Python37> cd C:\Users\me\PyEnv\test-env\
PS C:\Users\me\PyEnv\test-env> .\Scripts\activate
(test-env) PS C:\Users\me\PyEnv\test-env> pip install docker
...
Installing collected packages: six, pywin32, pypiwin32, chardet, idna, urllib3, certifi, requests, websocket-client, docker
Successfully installed certifi-2019.9.11 chardet-3.0.4 docker-4.1.0 idna-2.8 pypiwin32-223 pywin32-226 requests-2.22.0 six-1.13.0 urllib3-1.25.6 websocket-client-0.56.0
(test-env) PS C:\Users\me\PyEnv\test-env> pip -V
... ERROR ...
```

**Comment by DrFenerbache** [comment]
Was also getting this, looks like it's caused by the latest release of pywin32

https://github.com/mhammond/pywin32/issues/1439

Going back to 225 works for me

**Comment by casey-boyer-spoke** [comment]
Thank you!
