### ISSUE TITLE
images.build is swallowing the error message from docker build

### ISSUE THREAD

**Issue by BarakBD-Globality** [docker/docker-py#2492]
Expected: 
Full docker build error log should be captured in BuildError.

https://github.com/docker/docker-py/blob/1fc62e6a32c2d3257d5d033fcf924fabb16190ac/docker/models/images.py#L287

This is the error I currently get with `image.build` from this library:
```
docker_client_from_env.images.build failed on BuildError: The command '/bin/sh -c pip install --no-cache-dir --upgrade --extra-index-url ${EXTRA_INDEX_URL} /src/' returned a non-zero code: 1
```

However if I run the `docker build` directly I get the full error:
```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-bvyfl5jd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-bvyfl5jd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-bvyfl5jd/
    Complete output (23 lines):
    Couldn't find index page for 'marquez' (maybe misspelled?)
    No local packages or working download links found for marquez>=0.25131.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-bvyfl5jd/setup.py", line 49, in <module>
        "PyHamcrest>=1.8.5",
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('some_package>=0.25431.0')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install --no-cache-dir --upgrade --extra-index-url ${EXTRA_INDEX_URL} /src/ &&     apt-get remove --purge -y ${BUILD_PACKAGES} &&     apt-get autoremove -y &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

**Comment by BarakBD-Globality** [comment]
I see it is possible to access BuildErro.build_log as an iterable.
Not sure if this is documented well.
Also, When I print out th eror like this, it is not formatted well:
```
        for error in error.build_log:
            print(f"docker_client_from_env.images.build failed on BuildError: {error}")
```
Any suggestions?

**Comment by feliperuhland** [comment]
Hi @BarakBD-Globality 

Could you create a small Dockerfile (without sensitive data) that reproduces this behavior?
That will help me debug your issue.

Thank you.

**Comment by tvkit** [comment]
Posting for reference...

This should have been a _no-brainer_ for the team given you provided enough details upfront.

Anyway, @BarakBD-Globality , you helped me to identify the exception that's being raised. Armed with that info, getting the build is pretty straight forward.  The `BuildError` includes the enumerable containing the details of the build operation and _hopefully_ the cause of the failure. 

Here's an example:

```
    dockerfile = "..."
    tag = "..."
    try:
        results = dkr.images.build(nocache=True, tag=tag, dockerfile=dockerFile, path=".", rm=True, forcerm=True, )
        iterable = iter(results[1])
        while True:
            try:
                item = next(iterable)
                logging.info(item)
            except StopIteration:
                break
        return results[0]
    except docker.errors.BuildError as buildError:
        iterable = iter(buildError.build_log)
        while True:
            try:
                item = next(iterable)
                logging.warn(item)
            except StopIteration:
                break
        abort(1, buildError)
    except Exception as error:
        abort(1, error)

```
The `abort` call simply logs and exits.

This issue should be closed.
