### ISSUE TITLE
containers.run not working as expected with kwargs

### ISSUE THREAD

**Issue by leokun** [docker/docker-py#2496]
Hello,

I was trying to use the method `client.container.run()` by passing a dict as arguments without success

As a beginer I don't know if this the good way to do so, but I wanted to give args dynamicly.

ex : 

```python
opts = {
    'detach': True,
    'name': 'runner-python3_task_csv_20200121094759995153',
    'volumes': {
        '/home/leo/www/proj/data/tmp': {'bind': '/opt/tmp', 'mode': 'rw'},
        '/etc/localtime': {'bind': '/etc/locatime', 'mode': 'ro'}
    },
    'environment': {
        'PYTHONUNBUFFERED': True,
        'MONGO_IP': 'mongo',
        'MONGO_PORT': '27017',
    },
    'user': 'root',
    'group_add': ['root'],
    'links': ['mongo']
}
if getenv('ENV') == 'dev':
    opts['links'] = ['mongo']

client = docker.from_env()
container = client.containers.run(**opts)
```

Which gives that error : 

```
watcher    | Traceback (most recent call last):
watcher    |   File "/app/proj_lib/runners.py", line 78, in docker_exec
watcher    |     container = client.containers.run(params['image'], command=params['command'],stdout=True, stderr=False, remove=False, **opts)
watcher    |   File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 784, in run
watcher    |     container = self.create(image=image, command=command,
watcher    |   File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 842, in create
watcher    |     create_kwargs = _create_container_args(kwargs)
watcher    |   File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 1058, in _create_container_args
watcher    |     create_kwargs['host_config'] = HostConfig(**host_config_kwargs)
watcher    |   File "/usr/local/lib/python3.8/site-packages/docker/types/containers.py", line 304, in __init__
watcher    |     self['Links'] = normalize_links(links)
watcher    |   File "/usr/local/lib/python3.8/site-packages/docker/utils/utils.py", line 445, in normalize_links
watcher    |     return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
watcher    |   File "/usr/local/lib/python3.8/site-packages/docker/utils/utils.py", line 445, in <listcomp>
watcher    |     return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
watcher    | ValueError: too many values to unpack (expected 2)
```

Is it something I am not doing wrong or is it a bug ? 
I was expecting to gives args this way as this works in python : 

```python
>>> def myfunc(a, b=None, c=None):
...     print(str(a))
...     print(str(b))
...     print(str(c))
... 
>>> myfunc(**{"a": 123, "b": "aze", "c": True})
123
aze
True
>>> 
```

Thanks a lot for your support.
Regards, Leo

**Comment by leokun** [comment]
Oh ! and for compatibility issue I am using docker<4.0

**Comment by leokun** [comment]
### It was a link error sorry about that

I replace `opts['links'] = ["mongo"]` by `opts['links'] = [{"mongo": "mongo"}]`
