### ISSUE TITLE
Can't pull image from ECR after successfully logging in.

### ISSUE THREAD

**Issue by buddyroo30** [docker/docker-py#2535]
I saw this previous closed issue which is almost what is happening to me:

https://github.com/docker/docker-py/issues/2157

However, I am not able to pull whether I provide credentials (username and password) to the pull command or not (i.e. just relying on the docker login still being in effect). It doesn't work to pull either way, even though I get a successful login. Here is the error I am getting:

>>>docker_client.images.pull('....us-east.1.amazonaws.com/REPO',tag='TAG')
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "//anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/.....us-east-1.amazonaws.com/REPO:TAG/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/lib/python3.7/site-packages/docker/models/images.py", line 454, in pull
    repository, tag, '@' if tag.startswith('sha256:') else ':'
  File "//anaconda3/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "//anaconda3/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/docker/api/image.py", line 246, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "//anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "//anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "//anaconda3/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: .......us-east-1.amazonaws.com/REPO:TAG: No such image: ..........us-east-1.amazonaws.com/REPO:TAG")

One thing I noticed: why is it trying to fetch the image using a localhost url? It also is taking a very long time to timeout, about 15 minutes or so.

I'm getting this on a Mac and I am using version 4.2.0 of docker-py. Is this a bug or am I doing something wrong? Note that if I just manually try to pull the image, i.e. first doing 'docker login' then 'docker pull' it works fine.

**Comment by buddyroo30** [comment]
Actually, I got it working. I'm not sure exactly what I did, but anyway it is working and there doesn't seem to be a bug. I'll update later with details if possible.

**Comment by inhumantsar** [comment]
it's likely related to this: https://github.com/docker/docker-py/issues/2101

**Comment by mweitzel2005** [comment]
I am seeing the same issue when trying to pull and existing image (with enough free local disk space [373GB free]) using the Docker SDK for Python:
```python
_image = client.images.pull(
    repository=repository,
    tag=tag
)
```

I am getting the following error:
```bash
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/images/create?tag=<tag_iddentifier>&fromImage=<ecr_hostname><repository_name><image_name>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<username>/dev/<project_folder>/<python_file>.py", line 129, in pull_image
    _image = client.images.pull(
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docker/models/images.py", line 465, in pull
    pull_log = self.client.api.pull(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/opt/homebrew/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=<tag_iddentifier>&fromImage=<ecr_hostname><repository_name><image_name>: Not Found ("pull access denied for <ecr_hostname><repository_name><image_name>, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.")
```

This code actually works without any changes however **ONLY** if I authenticate with ECR and Docker on the command line first:
```bash
❯ aws ecr get-login-password --region <region> --profile <profile_name> | docker login --username AWS <ecr_hostname> --password-stdin
Login Succeeded
```
