### ISSUE TITLE
KeyError when orchestrator unset on context

### ISSUE THREAD

**Issue by FallenWarrior2k** [docker/docker-py#2546]
```
$ pip freeze | grep 'docker=='
docker==4.2.0
$ python --version
Python 3.7.5
$ docker version
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14.1
 Git commit:        afacb8b7f0
 Built:             Thu Apr  2 00:04:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

My local OS is current Arch Linux, the remote host is running Ubuntu 18.04.4.

When the Metadata.StackOrchestrator key is unset on a Docker Context, which is valid with the Docker CLI (none of the commands I tried errored out), then [this line](https://github.com/docker/docker-py/blob/1d1532f0be8fdf69443cfc71f1fb9002e9af4ae4/docker/context/context.py#L87) throws a key error. See stacktrace below (latest Git docker-compose to try out contexts).

```
Traceback (most recent call last):
  File "/home/simon/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/compose/cli/command.py", line 76, in project_from_options
    environment_file=environment_file
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/compose/cli/command.py", line 142, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/compose/cli/docker_client.py", line 47, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/compose/cli/docker_client.py", line 143, in docker_client
    context = ContextAPI.get_current_context()
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/docker/context/api.py", line 132, in get_current_context
    return cls.get_context()
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/docker/context/api.py", line 97, in get_context
    return Context.load_context(name)
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/docker/context/context.py", line 61, in load_context
    name, orchestrator, endpoints = Context._load_meta(name)
  File "/home/simon/.local/pipx/venvs/docker-compose/lib/python3.7/site-packages/docker/context/context.py", line 87, in _load_meta
    metadata["Name"], metadata["Metadata"]["StackOrchestrator"],
KeyError: 'StackOrchestrator'
```

In my case, I was trying to get the logs of a Compose deployment on a remote host using `docker-compose logs`, after `docker context use`ing my newly created context. As I was able to get the logs just fine with the docker CLI (without the interleaving of course), I think this is a bug.

**Comment by FallenWarrior2k** [comment]
Closing this as it appears to have been fixed in #2578.
