### ISSUE TITLE
Bad Request API error when creating a service with secrets flag

### ISSUE THREAD

**Issue by Mokatsu** [docker/docker-py#2558]
Server Version: 19.03.6
OS: Ubuntu 18.04
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Code:
```
secret = docker_service.secrets.get('test')
docker_service.services.create(image='<image id>', name='<name>', `secrets=[secret.name])
```

Error:
> Traceback (most recent call last):
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/error/venv_cir/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/services/create
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "/home/error/bin/cir/modules/test.py", line 11, in <module>
    print(docker_service.services.create(image='57a93ecd5c39', name='text_stats', secrets=[secret.name]))
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/models/services.py", line 225, in create
    service_id = self.client.api.create_service(**create_kwargs)
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/api/service.py", line 190, in create_service
    self._post_json(url, data=data, headers=headers), True
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/error/venv_cir/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("json: cannot unmarshal string into Go struct field ContainerSpec.Secrets of type swarm.SecretReference")
> Process finished with exit code 1

Am I submitting the secrets wrong? if i remove the secrets flag i get no error at all. The documentation says to submit secret names as a list: 
```
secrets (list of SecretReference) – List of secrets accessible to containers for this service.
```

Any help, guidance would be appreciateddocker

**Comment by Mokatsu** [comment]
Figured it out, leaving it here in case someone else is being dump like me:

> docker_service.services.create(image='<image id>', name='<name>', `secrets=[docker.types.SecretReference(secret_name=secret.name, secret_id=secret.id)])
