### ISSUE TITLE
Address pool is only available for API version >= 1.39 but API version is 1.40

### ISSUE THREAD

**Issue by Miesvanderlippe** [docker/docker-py#2594]
I'm trying to use the Python API with the example from the docs. 

Here's my Docker version
```
➜  swarm-controller docker version
Client:
 Version:           19.03.11-ce
 API version:       1.40
 Go version:        go1.14.3
 Git commit:        42e35e61f3
 Built:             Tue Jun  2 15:09:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.10-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.3
  Git commit:       9424aeaee9
  Built:            Fri May 29 11:14:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Here's what I typed into Python (including error)
```
>>> client.swarm.init(
...         advertise_addr='eth0', listen_addr='0.0.0.0:5000',
...         force_new_cluster=False, default_addr_pool=['10.20.0.0/16'],
...         subnet_size=24, snapshot_interval=5000,
...         log_entries_for_slow_followers=1200
...     )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miesl/.local/lib/python3.8/site-packages/docker/models/swarm.py", line 126, in init
    node_id = self.client.api.init_swarm(**init_kwargs)
  File "/home/miesl/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/miesl/.local/lib/python3.8/site-packages/docker/api/swarm.py", line 136, in init_swarm
    raise errors.InvalidVersion(
docker.errors.InvalidVersion: Address pool is only available for API version >= 1.39
```
PS: Might as well mention the docs miss a quote in default_addr_pool param.

**Comment by milas** [comment]
Old versions of `docker-py` had a fixed API version for communications by default, which was lower. Newer versions use `auto` which should negotiate to ensure the highest supported version is picked, which prevents issues like this.
