### ISSUE TITLE
[Mac OS] Attempt to Create Client over SSH – Python Package "invoke" missing

### ISSUE THREAD

**Issue by pklaus** [docker/docker-py#2613]
After Installing the Docker package on Mac OS (my local terminal) using

    pip install docker[ssh]

I have the Python packages docker (and also paramiko) installed. But when I try to create a client via SSH (on a server running Docker CE on Linux), I get:

```python
Python 3.8.3 (default, May 27 2020, 20:54:22) 
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.APIClient(base_url='ssh://192.168.2.2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pklaus/.pyvenv/py38r3/lib/python3.8/site-packages/docker/api/client.py", line 165, in __init__
    self._custom_adapter = SSHHTTPAdapter(
  File "/Users/pklaus/.pyvenv/py38r3/lib/python3.8/site-packages/docker/transport/sshconn.py", line 95, in __init__
    host_config = conf.lookup(base_url.hostname)
  File "/Users/pklaus/.pyvenv/py38r3/lib/python3.8/site-packages/paramiko/config.py", line 223, in lookup
    options = self._lookup(hostname=hostname)
  File "/Users/pklaus/.pyvenv/py38r3/lib/python3.8/site-packages/paramiko/config.py", line 250, in _lookup
    or self._does_match(
  File "/Users/pklaus/.pyvenv/py38r3/lib/python3.8/site-packages/paramiko/config.py", line 387, in _does_match
    raise invoke_import_error
  File "/Users/pklaus/.pyvenv/py38r3/lib/python3.8/site-packages/paramiko/config.py", line 36, in <module>
    import invoke
ModuleNotFoundError: No module named 'invoke'
```

I can fix this manually by also installing invoke on my Mac OS X machine:

    pip install invoke

In paramiko's manual they state that you can get it by specifying: `paramiko[invoke]`.
So if invoke is needed, should the [`extras_require` section of docker-py's setup.py be changed](https://github.com/docker/docker-py/blob/c65d437/setup.py#L40) to the following?

```
     'ssh': ['paramiko[invoke]>=2.4.2'],
```

---------------------

I'm using Mac OS X 10.15 and the docker-py package v4.2.2

The OS release:
`Darwin mycomputer 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

```
docker==4.2.2
Python 3.8.3
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by milas** [comment]
This is a Paramiko limitation/requirement for `Match` support. Given that, I don't think we want to include it as a direct dependency here - best option IMO would be to add it to your requirements if needed.
