### ISSUE TITLE
module 'selectors' has no attribute 'SelectSelector' import error

### ISSUE THREAD

**Issue by MikeVlad6** [docker/docker-py#2618]
Hi, i'm getting an import error when trying to `import docker`.
I'm running on ubuntu 20.02, tried both python 3.8.2 and 3.6.11. docker version is `4.2.2`
Steps:
Create a virtualenvironment `virtualenv venv`, `pip install docker`. 
Error log:

```
Traceback (most recent call last):
  File "/home/mike/Documents/git/scrapyPuppet/controller/test.py", line 1, in <module>
    import docker
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/auth.py", line 7, in <module>
    from . import credentials
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/credentials/__init__.py", line 2, in <module>
    from .store import Store
  File "/home/mike/Documents/git/scrapyPuppet/controller/venv/lib/python3.8/site-packages/docker/credentials/store.py", line 3, in <module>
    import subprocess
  File "/usr/lib/python3.8/subprocess.py", line 218, in <module>
    _PopenSelector = selectors.SelectSelector
AttributeError: module 'selectors' has no attribute 'SelectSelector'
```
Here is a pip.freeze for python 3.8.2:

```
appdirs==1.4.3
CacheControl==0.12.6
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
contextlib2==0.6.0
distlib==0.3.0
distro==1.4.0
docker==4.2.2
html5lib==1.0.1
idna==2.8
ipaddr==2.2.0
lockfile==0.12.2
msgpack==0.6.2
packaging==20.3
pep517==0.8.2
progress==1.5
psycopg2-binary==2.8.5
pyparsing==2.4.6
pytoml==0.1.21
requests==2.22.0
retrying==1.3.3
six==1.14.0
urllib3==1.25.8
webencodings==0.5.1
websocket-client==0.57.0
```

Any help would be appreciated.

Thanks!

**Comment by thorwhalen** [comment]
Same here.

**Comment by CBlackBird** [comment]
it seems the selectors moudule have some issue. Using "print(selectors.__file__)" to get the moudule path, and then check the moudule file if it has “SelectSelector”
