### ISSUE TITLE
credstore_env not a valid parameter to docker.from_env even though it is listed in docs

### ISSUE THREAD

**Issue by anorth2** [docker/docker-py#2627]
```
docker_client = docker.from_env(credstore_env=credentials)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/...../docker/client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
TypeError: kwargs_from_env() got an unexpected keyword argument 'credstore_env'
```

https://docker-py.readthedocs.io/en/stable/client.html#docker.client.from_env

**Comment by anorth2** [comment]
Ping
