### ISSUE TITLE
Possible race condition in Remove/wait 

### ISSUE THREAD

**Issue by ashokkumarrathore** [docker/docker-py#2655]
https://github.com/docker/docker-py/blob/master/docker/api/container.py
While there is some thread waiting on container on the client side using API
**wait(self, container, timeout=None, condition=None)**
  the container could get removed on the daemon side(auto_remove=true). And the wait throws this error:
Maybe in **def remove_container(self, container, v=False, link=False, force=False):** we should check if some client is waiting before deleting the container url.
We are seeing this issue intermittently in Airflow , which uses both of these APIs.
File "/opt/sfdc/python36/lib/python3.6/site-packages/docker/api/client.py", line 226, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/opt/sfdc/python36/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/sfdc/python36/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/sfdc/python36/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/sfdc/python36/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='XXXXXXXX', port=2376): Read timed out. (read timeout=None)

**Comment by danielhass** [comment]
Ran into this as well today. I like to provide the following minimal example to show the race condition.

This does not work:
```
import docker

client = docker.from_env()
client.containers.run('alpine', ["/bin/sh", "-c", "echo 'test'"], auto_remove=True)
```

Error with Traceback:
```
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/vscode/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/0328e54300025f6b0bc9672c4e3776400d55f24643a9d8385d471b8c5ea23459/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/test_docker.py", line 4, in <module>
    client.containers.run('alpine', ["/bin/sh", "-c", "echo test"], auto_remove=True)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/models/containers.py", line 827, in run
    out = container.logs(
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/models/containers.py", line 306, in logs
    return self.client.api.logs(self.id, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/container.py", line 871, in logs
    output = self._get_result(container, stream, res)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/client.py", line 456, in _get_result
    return self._get_result_tty(stream, res, self._check_is_tty(container))
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/client.py", line 452, in _check_is_tty
    cont = self.inspect_container(container)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/container.py", line 773, in inspect_container
    return self._result(
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/vscode/.local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/0328e54300025f6b0bc9672c4e3776400d55f24643a9d8385d471b8c5ea23459/json: Not Found ("No such container: 0328e54300025f6b0bc9672c4e3776400d55f24643a9d8385d471b8c5ea23459")
```

Howevery this does work:
```
import docker

client = docker.from_env()
client.containers.run('alpine', ["/bin/sh", "-c", "sleep 1"], auto_remove=True)
```

Is this an intended behavior?
In my use case I cannot run the container with `detach=True`, as I would like to wait for its execution to finish before continuing.

**Comment by scottrbaxter** [comment]
@danielhass i ran into this same issue just last night... it seems that any command that executes too quickly (e.g. `echo ...` or `ls`)  will result in failure to run successfully. I ran the same test by adding a `sleep 1` delay and it runs successfully, consistently. My traceback was nearly identical, so I'll not add it, but here is the error:

```
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/4c4031e6e36bb89955d28d97df5725b543092eaa16d548e06dd51529ec7567ef/json: Not Found ("No such container: 4c4031e6e36bb89955d28d97df5725b543092eaa16d548e06dd51529ec7567ef")
```
Using `sleep 1` like this is successful:
```
import docker

client = docker.from_env()
client.containers.run(
    'alpine',
    'sleep 1',
    auto_remove=True,
)
```

macOS 11.5 (m1)
Python 3.9.1
Docker for Mac 4

**Comment by djmattyg007** [comment]
I've noticed a similar thing when using `detach=True`, `auto_remove=True`, and then trying to `.wait()` on the container object a very short time later.
