### ISSUE TITLE
Mount doesn't work

### ISSUE THREAD

**Issue by mvxxx** [docker/docker-py#2663]
Hi,
I am trying to use `mounts` in client.containers.run:

```python
import docker
from docker.types import Mount
import os

client = docker.from_env()

print(docker.__version__)


container=client.containers.run(
    'ubuntu',
    device_requests=[
        docker.types.DeviceRequest(count=1, capabilities=[['gpu']])
    ],
    detach=True,
    stdin_open=True,
    tty = True,
    ports={'8000/tcp': 8000, '8001/tcp': 8001, '8002/tcp': 8002},
    mounts=[Mount(target='/abcde',
                  source='/home/e6dn/dev/path/to/dir/')]
)

print(os.listdir('workspace'))

print(container.exec_run('/bin/sh -c "ls"', workdir='/abcde))
container.kill()

```

I got following error:
```
4.3.1
Traceback (most recent call last):
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.40/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner/test.py", line 10, in <module>
    container=client.containers.run(
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/models/containers.py", line 809, in run
    container = self.create(image=image, command=command,
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/models/containers.py", line 868, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/e6dn/.local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("create /home/e6dn/dev/path/to/dir: "/home/e6dn/dev/path/to/dir" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")
```

but /home/e6dn/dev/path/to/dir is absolute path.

**Comment by jeroenherczeg** [comment]
I have no knowledge about this, but had the same error.
I solved it with adding type='bind'

`mounts=[Mount(target='/target',source='/mnt/loki/source',type='bind')],`

**Comment by mvxxx** [comment]
Thanks @jeroenherczeg, I think that documentation should be more detailed about this. Another solution is to use `volumes` arguments:

`volumes={os.path.join(os.getcwd(), HOST_PATH): {'bind': DOCKER_PATH, 'mode': 'rw'}}`
