### ISSUE TITLE
docker.from_env() return FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by robinhli** [docker/docker-py#2683]
ENVIRONMENT
Operating System: Windows 10， Docker 19.03.12
Python 3.7.3
docker            4.3.1

when I run the docker.from_env() from hostmachine, it's ok. (host: Windows 10, Python3.5.4, docker 4.3.1)
When I run the same command with in a container, it has problems as below (container: Python 3.7.3, docker 4.3.1)

Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.from_env()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by robinhli** [comment]
need to start container with -v /var/run/docker.sock:/var/run/docker.sock. add this paramter then start container, it's ok.

**Comment by Arlington1985** [comment]
it's happening for me when it's started from the host machine

**Comment by Arlington1985** [comment]
My bad, the issue was docker service was not running.

**Comment by tridelt** [comment]
> -v /var/run/docker.sock:/var/run/docker.sock

that solved it for me, thank you so much!

**Comment by susnato** [comment]
This happenned to me while I was using a Mac, for me keeping the Docker desktop running in the backend fixed the issue.
