### ISSUE TITLE
Module docker has no attribute from_env

### ISSUE THREAD

**Issue by solairen** [docker/docker-py#2692]
Hi,

I have a problem with the docker in WSL2. 
I've configured the docker that can be used in WSL2 (WSL integration) and installed docker SDK for python.
When I want to run a python file it shows an error:

```log
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    client = docker.from_env()
AttributeError: module 'docker' has no attribute 'from_env'
```
If I use the `sudo` command the error will be:

```log
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'
```
The same situation occurs when I change the **Python interpreter** from **/bin/python3** to **/usr/bin/python3**

Do I need to configure something else to be able to run on WSL2? 

My configuration:
* Python interpreter: /bin/python3
* Python version: 3.8.5
* Python SDK: 4.3.1
* WSL OS: Ubuntu 20.04

**Comment by solairen** [comment]
OK, I figure it out.
I had to install docker SDK  with command **sudo**
