### ISSUE TITLE
setblocking(False) fails on npipesocket object

### ISSUE THREAD

**Issue by jbayfield** [docker/docker-py#2701]
I'm currently working with a socket produced by the container `exec_run()` function. I am trying to set the socket to be non-blocking (i.e. instant timeout if no data to receive), but running into an error when executing `socket.setblocking(False)`.

This is an area of Python I haven't really explored before so forgive any missing detail - let me know if any more info would be helpful.

### Stacktrace
```
Traceback (most recent call last):
  File "d:\Repositories\DockerProj\test.py", line 9, in __init__
    self.socket.setblocking(False)
  File "D:\Repositories\DockerProj\.venv\lib\site-packages\docker\transport\npipesocket.py", line 167, in setblocking
    return self.settimeout(0)
  File "D:\Repositories\DockerProj\.venv\lib\site-packages\docker\transport\npipesocket.py", line 177, in settimeout
    self._timeout = win32pipe.NMPWAIT_NO_WAIT
AttributeError: module 'win32pipe' has no attribute 'NMPWAIT_NO_WAIT'
```

### System information
OS: Windows 10 Build 19041
Docker-py version: 4.3.1
Python version: 3.8.5

### Docker information
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by atmaranto** [comment]
This still seems to be a problem as of docker-py version 6.0.1.
```>>> sock.settimeout(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[python path]\lib\site-packages\docker\transport\npipesocket.py", line 173, in settimeout
    self._timeout = win32pipe.NMPWAIT_NO_WAIT
AttributeError: module 'win32pipe' has no attribute 'NMPWAIT_NO_WAIT'. Did you mean: 'NMPWAIT_NOWAIT'?
```
