### ISSUE TITLE
Testing openAI universe, an error occurred while using docker，requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.41/images/create?tag=0.20.28&fromImage=quay.io%2Fopenai%2Funiverse.flashgames

### ISSUE THREAD

**Issue by wuke12331** [docker/docker-py#2727]
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.41/containers/create?name=universe-0r4JfN-0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 264, in _spawn
    container = self._spawn_container()
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 314, in _spawn_container
    'com.openai.automanaged': 'true',
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/api/container.py", line 146, in create_container_from_config
    return self._result(res, True)
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'{"message":"No such image: quay.io/openai/universe.flashgames:0.20.28"}'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.41/images/create?tag=0.20.28&fromImage=quay.io%2Fopenai%2Funiverse.flashgames

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuk/PycharmProjects/pythonProject/main.py", line 5, in <module>
    env.configure(remotes=1)  # automatically creates a local docker container
  File "/home/wuk/universe/universe/wrappers/timer.py", line 14, in configure
    self.env.configure(**kwargs)
  File "/home/wuk/universe/universe/wrappers/render.py", line 21, in configure
    self.env.configure(**kwargs)
  File "/home/wuk/universe/universe/wrappers/throttle.py", line 32, in configure
    self.env.configure(**kwargs)
  File "/home/wuk/universe/universe/envs/vnc_env.py", line 199, in configure
    use_recorder_ports=record,
  File "/home/wuk/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 55, in __init__
    self._start()
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 82, in _start
    [instance.start() for instance in self.instances]
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 82, in <listcomp>
    [instance.start() for instance in self.instances]
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 236, in start
    self._spawn()
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 270, in _spawn
    self._pull_image()
  File "/home/wuk/universe/universe/remotes/docker_remote.py", line 288, in _pull_image
    output = self.client.pull(self.runtime.image, stream=True)
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/api/image.py", line 175, in pull
    self._raise_for_status(response)
  File "/home/wuk/anaconda3/envs/universe/lib/python3.6/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"unauthorized: access to the requested resource is not authorized"}'")

**Comment by raushankumar586** [comment]
I am facing the same problem

**Comment by MJohnson20** [comment]
Same, did anyone find a solution to this?
