### ISSUE TITLE
ConnectionResetError raised in case a build_arg has incorrect type and a build context folder contains large file

### ISSUE THREAD

**Issue by eltimen** [docker/docker-py#2836]
Hello.

I passed a boolean value as a build argument by mistake and found that it hangs on Windows and raises `Connection reset by peer` exception on Linux:
<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker_false_arg.py", line 14, in <module>
    decode=True)
  File "/home/user/.local/lib/python3.7/site-packages/docker/api/build.py", line 269, in build
    timeout=timeout,
  File "/home/user/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

```
</details>

This behavior occurs only if a build context folder contains a large file or files (>1 MB). Otherwise, the error message about incorrect type is displayed. 

Environment:
* docker-py 5.0.0
* Docker Engine 20.10.3

How to reproduce:
1) Create an empty folder and cd to it
2) Place this example script and Dockerfile in the folder:
```dockerfile
FROM alpine
ARG bool_arg
RUN echo $bool_arg
```
```python
import docker
import os

build_args = {'bool_arg': True}
location = os.getcwd()
client = docker.from_env()
log = client.api.build(path=location,
                       tag='test_bool_arg:latest',
                       dockerfile='test.dockerfile',
                       rm=True,
                       nocache=True,
                       pull=True,
                       buildargs=build_args,
                       decode=True)

for line in log:
    for _, value in line.items():
        print(f'{value}')
```

3) Launch script and get message `error reading build args: json: cannot unmarshal bool into Go value of type string` 
4) Create a large file in the folder (`truncate -s 1M dummy_file`)
5) Launch script again and get ConnectionResetError

**Comment by lheuveline** [comment]
@eltimen Thanks a lot. I got stuck on large file misleading error message for few hours, after .git directory got oversized (220Mb in objects). Scoping docker context allowed me to get the original error (repository name contianing uppercase) and fix it !
