### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by WolfgangFahl** [docker/docker-py#2856]
https://github.com/WolfgangFahl/pymediawikidocker/actions/runs/918096175 failed 
with
```
======================================================================
ERROR: tests.test_install (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_install
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/pymediawikidocker/pymediawikidocker/tests/test_install.py", line 7, in <module>
    import docker
  File "/home/runner/.local/lib/python3.9/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/runner/.local/lib/python3.9/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/runner/.local/lib/python3.9/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/home/runner/.local/lib/python3.9/site-packages/docker/auth.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```
since the requirements.txt file only contained:
```
# Dependencies for Python controlled MediaWiki Docker image Installation
# Since 2021-06-08
# Docker SDK for Python
#https://pypi.org/project/docker/
docker
```

as a workaround i had to change it to:
```
# Dependencies for Python controlled MediaWiki Docker image Installation
# Since 2021-06-08
# Docker SDK for Python
#https://pypi.org/project/docker/
docker      
#
# avoid ModuleNotFoundError: No module named 'six'
six
```

**Comment by WolfgangFahl** [comment]
duplicate of #2842
