### ISSUE TITLE
Latest release `5.0.0` is still using `six`

### ISSUE THREAD

**Issue by gbolmier** [docker/docker-py#2882]
Hi maintainers 👋 

Latest release `5.0.0` is still using `six`, precisely in the `auth.py` module:

https://github.com/docker/docker-py/blob/80878bc61064616a26a3c9423fab4049ad50260d/docker/auth.py#L5

Seems like to be an omission from [`c8fba21`](https://github.com/docker/docker-py/commit/c8fba210a222d4f7fde90da8f48db1e7faa637ec#).

#### Steps to reproduce the error

```sh
(base) ➜  ~ docker run --rm -it --entrypoint bash python:3.7-slim
root@df9a9b4b8b18:/# pip install docker
Collecting docker
  Downloading docker-5.0.0-py2.py3-none-any.whl (146 kB)
     |████████████████████████████████| 146 kB 5.6 MB/s 
Collecting requests!=2.18.0,>=2.14.2
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.5 MB/s 
Collecting websocket-client>=0.32.0
  Downloading websocket_client-1.2.1-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 2.4 MB/s 
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 4.6 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB 15.4 MB/s 
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 16.6 MB/s 
Installing collected packages: urllib3, idna, charset-normalizer, certifi, websocket-client, requests, docker
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.4 docker-5.0.0 idna-3.2 requests-2.26.0 urllib3-1.26.6 websocket-client-1.2.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@df9a9b4b8b18:/# python
Python 3.7.11 (default, Aug 17 2021, 03:21:46) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/usr/local/lib/python3.7/site-packages/docker/auth.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by felixfontein** [comment]
This has been fixed by #2863, and got finally released in 5.0.1 yesterday.
