### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'

### ISSUE THREAD

**Issue by milanbalazs** [docker/docker-py#2891]
**Used OS:**
- Red Hat Enterprise Linux Server - 7.8 (Maipo)

**Tried Python versions:**
- Python 3.6.6
- Python 3.9.0

**Docker version:**
- Docker version 18.03.0-ce, build 0520e24

**SSL version of different Python interpreters:**
- Python 3.9.0:
```
Python 3.9.0 (default, Nov 26 2020, 12:13:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 1.1.1h  22 Sep 2020
```

- Python 3.6.6:
```
Python 3.6.6 (default, Aug 24 2018, 09:30:17) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 1.0.2o  27 Mar 2018
```

**The docker related part of my requirements.txt file:**

```
docker==5.0.0
docker[tls]==5.0.0
```

**My Python code:**

```
import docker


client = docker.from_env()

cont = client.containers.run(
    "artifactory-oss:latest",
    name="arm_instance",
#    detach=True,
    stream=True,
    auto_remove=True,
    ports={"8081/tcp": 10001, "8082/tcp": 10002},
    volumes={
        "/local/scratch/arm_docker": {"bind": "/var/opt/jfrog/artifactory", "mode": "rw"}
    },
)
```

**The getting error:**

```
>>> python3 test.py 
/python/3.6-addons-scp-0.13.2/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:159: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/venv3/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/user/venv3/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/user/venv3/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/user/venv3/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/user/venv3/lib/python3.9/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/user/venv3/lib/python3.9/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/venv3/lib/python3.9/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/venv3/lib/python3.9/site-packages/requests/adapters.py", line 435, in send
    resp = conn.urlopen(
  File "/home/user/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/user/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/user/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/user/venv3/lib/python3.9/site-packages/urllib3/connection.py", line 342, in connect
    self.ssl_context = create_urllib3_context(
  File "/home/user/venv3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 277, in create_urllib3_context
    context = SSLContext(ssl_version or ssl.PROTOCOL_SSLv23)
  File "/home/user/venv3/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 382, in __init__
    self._ctx = OpenSSL.SSL.Context(self.protocol)
  File "/home/user/venv3/lib/python3.9/site-packages/OpenSSL/SSL.py", line 644, in __init__
    res = _lib.SSL_CTX_set_ecdh_auto(context, 1)
AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/test.py", line 4, in <module>
    client = docker.from_env()
  File "/home/user/venv3/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/user/venv3/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/user/venv3/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/user/venv3/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'
```

**Note:**
- I have tried my implementation (included Docker version and config and Virtual Environment config) on a different server and it works as expected. I don't understand why it is not working on this server. But the Python interpreter is the same (It is a centralized Python interpreter on a mounted partition).

I have tried to upgrade the OpenSSL on my Linux server and tried to upgrade the `pyOpenSSL` (adding `pyOpenSSL==20.0.1
` line to my requirement.txt file) but these trying didn't solve my problem.

I have read some articles that I have to **rebuild** the Python but it **is not possible in my case**! On the other hand as I mentioned above my implementation works on a different server with the same Python interpreter so I think the problem is in my server but perhaps there is something solution which solve my problem without server configuration.

Could you provide a solution (or at least some hints) to solve this problem?

Thanks in advance,
Milan

**Comment by milanbalazs** [comment]
I have managed to solve the problem. I had a `paramiko` and `SCP` Python modules on the affected server which have old OpenSSL version.

**Comment by avie14** [comment]
Hi, suddenly getting this error when installing autobahn 
Any advise on how it can be resolved ?

Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nbrwvm4j/autobahn/setup.py", line 321, in <module>
          from twisted.internet import reactor
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/reactor.py", line 38, in <module>
          from twisted.internet import default
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/default.py", line 55, in <module>
          install = _getInstallFunction(platform)
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/default.py", line 43, in _getInstallFunction
          from twisted.internet.epollreactor import install
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/epollreactor.py", line 19, in <module>
          from twisted.internet import posixbase
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 20, in <module>
          from twisted.internet import error, udp, tcp
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/tcp.py", line 36, in <module>
          from twisted.internet._newtls import (
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/internet/_newtls.py", line 19, in <module>
          from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/twisted/protocols/tls.py", line 44, in <module>
          Connection(Context(TLSv1_METHOD), None)
        File "/home/avi/temp_venvs/new4/venv/lib/python3.8/site-packages/OpenSSL/SSL.py", line 674, in __init__
          res = _lib.SSL_CTX_set_ecdh_auto(context, 1)
      AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'
