### ISSUE TITLE
does not install on windows python 3.10

### ISSUE THREAD

**Issue by inorton** [docker/docker-py#2967]
```
C:\WINDOWS\system32>pip install --upgrade docker==5.0.3
Collecting docker==5.0.3
  Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)
ERROR: Could not find a version that satisfies the requirement pywin32==227; sys_platform == "win32" (from docker) (from versions: 302, 303)
ERROR: No matching distribution found for pywin32==227; sys_platform == "win32"
```

It seems unusual to me that the docker package depends on a specific exact version of pywin32

**Comment by gustawdaniel** [comment]
Not only windows. I have the same problem on arch. Logs:

```
pip3 install docker docker-compose
Collecting docker
  Downloading docker-5.0.3-py2.py3-none-any.whl (146 kB)
Collecting docker-compose
  Downloading docker_compose-1.29.2-py2.py3-none-any.whl (114 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3030, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2827, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 348, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 208, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 199, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate=candidate):
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
    return [
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
    return [
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 251, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2748, in requires
    dm = self._dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3032, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3042, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3098, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3108, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 1100, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line [381](https://gitlab.com/preciselab/on-chain/twitter-producer/-/jobs/2244104057#L381)0, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line [402](https://gitlab.com/preciselab/on-chain/twitter-producer/-/jobs/2244104057#L402)4, in parseImpl
    return e._parse(
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 4854, in parseImpl
    loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 827, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 283, in wrapper
    ret = func(*args[limit:])
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 81, in <lambda>
    lambda s, l, t: Marker(s[t._original_start : t._original_end])
TypeError: slice indices must be integers or None or have an __index__ method
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by kakaiba-talaga** [comment]
It's early stated in PyPi.org that it only supports `>= 3.6.x` and `<= 3.9.x`.

![Supported Python Versions](https://user-images.githubusercontent.com/62324916/165009366-2947172b-8e65-485a-b0e9-1e2e705dbb43.png)

Let's just wait for an update.

**Comment by inorton** [comment]
@kakaiba-talaga that may be so, if it is the way it is intended right now the setu.py should add the constraints on the python versions at the very least

**Comment by aijogja** [comment]
I used `python 3.9.7` but also cannot install it.

![image](https://user-images.githubusercontent.com/1049429/165663387-5fe760c4-e87e-45fe-85f4-c39b02e58e2d.png)

**Comment by jonapich** [comment]
We're getting there soon now; what can we do to rocket this further? Need help?

**Comment by milas** [comment]
Upcoming release will properly support Python 3.10

**Comment by digger-yu** [comment]
same error on python 3.11.1 

```
Requirement already satisfied: websocket-client>=0.32.0 in c:\program files\python311\lib\site-packages (from docker==5.0.3) (1.5.1)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in c:\program files\python311\lib\site-packages (from docker==5.0.3) (2.28.2)
ERROR: Could not find a version that satisfies the requirement pywin32==227; sys_platform == "win32" (from docker) (from versions: 303, 304, 305)
ERROR: No matching distribution found for pywin32==227; sys_platform == "win32"
```
