### ISSUE TITLE
Version 6.0.0 does not offer version_info

### ISSUE THREAD

**Issue by mkesper** [docker/docker-py#3040]
I don't see it mentioned in the changelog so I guess it's a bug that version 6.0.0 does not offer any version_info. This causes breakage in software depending on docker module like e.g. docker-squash:

```
2022-08-25 06:21:47,359 root         ERROR    module 'docker' has no attribute 'version_info'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker_squash/image.py", line 357, in _save_image
    if docker.version_info[0] < 3:
AttributeError: module 'docker' has no attribute 'version_info'
```

With docker==5.0.3 everything works as expected.

**Comment by coffnix** [comment]
Same error here:

```
python3.7 setup.py build -j 4
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    maintainer_email='ulysses.souza@docker.com',
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 480, in __init__
    for k, v in attrs.items()
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 900, in finalize_options
    ep(self)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3.7/site-packages/setuptools_scm/integration.py", line 90, in version_keyword
    _assign_version(dist, config)
  File "/usr/lib/python3.7/site-packages/setuptools_scm/integration.py", line 62, in _assign_version
    _version_missing(config)
  File "/usr/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 110, in _version_missing
    f"setuptools-scm was unable to detect version for {config.absolute_root}.\n\n"
LookupError: setuptools-scm was unable to detect version for /var/tmp/portage/dev-python/docker-py-6.0.0/work/docker-py-6.0.0.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

```

**Comment by milas** [comment]
The version info in 6.0.0+ is now exposed as `__version__` as a result of packaging changes, which is the general convention/standard in Python.

```sh
python3 -c 'import docker; print(docker.__version__);'
6.0.1.dev1+g2494d63f
```

I'll add a note to the changelog in the GitHub release.
