### ISSUE TITLE
how to get a interactive shell on docker-py

### ISSUE THREAD

**Issue by calvinweb** [docker/docker-py#3057]
it seems nothing can get a writable stream by docker-py

**Comment by semwai** [comment]
try the `attach_socket` function. It returns a socket from which you can read and write data to stdin

**Comment by calvinweb** [comment]
> try the `attach_socket` function. It returns a socket from which you can read and write data to stdin

well i tried it but it said 
```
>>> a1=a.attach_socket()
>>> a1.write('a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/socket.py", line 685, in write
    self._checkWritable()
io.UnsupportedOperation: File or stream is not writable.
```

**Comment by semwai** [comment]
Maybe this (this is partly from my project, but I haven't tested exactly this code)
```
import docker

client = docker.from_env()



container = client.containers.create(
            'python:3.10',
            command='python',
            tty=False,
            detach=True,
            stdin_open=True,
        )

container.start()
stdin = client.api.attach_socket(container.id, params={'stdin': 1, 'stdout': 0, 'stderr': 0, 'stream': 1})
stdout = client.api.attach_socket(container.id, params={'stdin': 0, 'stdout': 1, 'stderr': 0, 'stream': 1})
stderr = client.api.attach_socket(container.id, params={'stdin': 0, 'stdout': 0, 'stderr': 1, 'stream': 1})

self.stdin._sock.setblocking(0) 
self.stdin._writing = True
self.stdout._sock.setblocking(0)
self.stderr._sock.setblocking(0)



#  write data to stdin
stdin.write("print('123321')\n".encode('utf-8'))
#  read from stdout
print(self.stdout.read(1024))
#  write data to stdin
stdin.write("print(1/0)\n".encode('utf-8'))
#  read from stderr
print(self.stderr.read(1024))
```

**Comment by calvinweb** [comment]
thank you, i will try it
