### ISSUE TITLE
Run from Docker send: Connection aborted

### ISSUE THREAD

**Issue by MagTemTenebrius** [docker/docker-py#3069]
How to run a python script with this library from docker?

`docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`

Code: 
```
async def containers() -> List[str]:
    client = docker.from_env()
    logger.info("Successful connect!")
    for container in client.containers.list():
        logger.info(f"{container}")
```

Run: `python3 main.py` - successful, but

Run: `docker-compose up`
docker-compose.yaml:
```version: '3.3'
services:
  monitor:
    build:
      dockerfile: monitor/Dockerfile
      context: .
    volumes:
      - ./runtime:/runtime
    env_file:
      - .env
    restart: always
    network_mode: host
```
Output:

```
monitor_1  | During handling of the above exception, another exception occurred:
monitor_1  |
monitor_1  | Traceback (most recent call last):
monitor_1  |   File "main.py", line 66, in <module>
monitor_1  |     asyncio.run(containers())
monitor_1  |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
monitor_1  |     return loop.run_until_complete(main)
monitor_1  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
monitor_1  |     return future.result()
monitor_1  |   File "/monitor/container/server.py", line 10, in containers
monitor_1  |     client = docker.from_env()
monitor_1  |   File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
monitor_1  |     return cls(
monitor_1  |   File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
monitor_1  |     self.api = APIClient(*args, **kwargs)
monitor_1  |   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
monitor_1  |     self._version = self._retrieve_server_version()
monitor_1  |   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
monitor_1  |     raise DockerException(
monitor_1  | docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by MagTemTenebrius** [comment]
Solve.

add:
```
volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by zackees** [comment]
Thanks i think this fixed my issue.
