### ISSUE TITLE
Docs about running params of the containers

### ISSUE THREAD

**Issue by latot** [docker/docker-py#3086]
Hi all, I like this lib! finally portable apps from python! great!, today I tried to run some container params from the lib, sadly seems not to works:

This works from the terminal
```
docker run -e POSTGRES_DB="db" -e POSTGRES_PASSWORD="postgres" -e POSTGRES_HOST_AUTH_METHOD="trust" -e POSTGRES_USER="postgres" postgis/postgis -c max_worker_processes=15 -c max_parallel_workers=1 -c max_parallel_workers_per_gather=1 -c max_parallel_maintenance_workers=1 -c enable_async_append=on -c enable_bitmapscan=on -c enable_gathermerge=on -c enable_hashagg=on -c enable_hashjoin=on -c enable_incremental_sort=on -c enable_indexscan=on -c enable_indexonlyscan=on -c enable_material=on -c enable_memoize=on -c enable_mergejoin=on -c enable_nestloop=on -c enable_parallel_append=on -c enable_parallel_hash=on -c enable_partition_pruning=on -c enable_partitionwise_join=on -c enable_partitionwise_aggregate=on -c enable_seqscan=on -c enable_sort=on -c enable_tidscan=on -c parallel_setup_cost=0 -c min_parallel_table_scan_size=0B -c min_parallel_index_scan_size=0B -c jit_above_cost=0 -c jit_inline_above_cost=0 -c jit_optimize_above_cost=0 -c geqo=on -c jit=on -c cpu_tuple_cost=0 -c cpu_index_tuple_cost=0 -c cpu_operator_cost=0 -c parallel_tuple_cost=0 -c shared_buffers=12800000000B -c effective_cache_size=24000000000B -c checkpoint_completion_target=0.9 -c min_wal_size=1000000000B -c max_wal_size=4000000000B
```

The same over python:
```
params = "-c max_worker_processes=15 -c max_parallel_workers=1 -c max_parallel_workers_per_gather=1 -c max_parallel_maintenance_workers=1 -c enable_async_append=on -c enable_bitmapscan=on -c enable_gathermerge=on -c enable_hashagg=on -c enable_hashjoin=on -c enable_incremental_sort=on -c enable_indexscan=on -c enable_indexonlyscan=on -c enable_material=on -c enable_memoize=on -c enable_mergejoin=on -c enable_nestloop=on -c enable_parallel_append=on -c enable_parallel_hash=on -c enable_partition_pruning=on -c enable_partitionwise_join=on -c enable_partitionwise_aggregate=on -c enable_seqscan=on -c enable_sort=on -c enable_tidscan=on -c parallel_setup_cost=0 -c min_parallel_table_scan_size=0B -c min_parallel_index_scan_size=0B -c jit_above_cost=0 -c jit_inline_above_cost=0 -c jit_optimize_above_cost=0 -c geqo=on -c jit=on -c cpu_tuple_cost=0 -c cpu_index_tuple_cost=0 -c cpu_operator_cost=0 -c parallel_tuple_cost=0 -c shared_buffers=12800000000B -c effective_cache_size=24000000000B -c checkpoint_completion_target=0.9 -c min_wal_size=1000000000B -c max_wal_size=4000000000B"

container = client.containers.run(
      "postgis/postgis:latest",
      params,
      environment = {
        'POSTGRES_DB': "db",
        'POSTGRES_USER': "postgres",
        'POSTGRES_PASSWORD': "password",
        'POSTGRES_HOST_AUTH_METHOD': "trust"
      },
      detach = True,
      auto_remove = True,
      ports = {
        '5432/tcp': 60000 #Some random port
      }
    )
```

The out logs (```container.logs()```):
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/6c966830293b241a1a0be4644aff312955e1a6397eddd2a67281d75554338442/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/docker/models/containers.py", line 306, in logs
    return self.client.api.logs(self.id, **kwargs)
  File "/usr/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/docker/api/container.py", line 869, in logs
    output = self._get_result(container, stream, res)
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 460, in _get_result
    return self._get_result_tty(stream, res, self._check_is_tty(container))
  File "/usr/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 456, in _check_is_tty
    cont = self.inspect_container(container)
  File "/usr/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/docker/api/container.py", line 771, in inspect_container
    return self._result(
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/6c966830293b241a1a0be4644aff312955e1a6397eddd2a67281d75554338442/json: Not Found ("No such container: 6c966830293b241a1a0be4644aff312955e1a6397eddd2a67281d75554338442")
```

Well, maybe the ```comands``` param of the container func is now where we pass the container params, in that case, I don't know where, I already checked: https://docker-py.readthedocs.io/en/stable/

Sadly nothing very explicit to where the container commands go, I think would be great explicit it in the docs.

```
docker==5.0.3
docker-compose==1.29.2
dockerpty==0.4.1
Python 3.10.9
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.4
 Git commit:        3a2c30b63a
 Built:             Wed Jan  4 15:50:19 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.4
  Git commit:       42c8b31499
  Built:            Wed Jan  4 15:59:52 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad007797e0dcd8b7126f27bb87401d224240
```

Thx!

**Comment by milas** [comment]
The `command` is passed to `run()` as shown in the docs: https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run

The error you showed is that the container does not exist when being attached to for logs.

You also set `auto_remove=True`, so likely the container is exiting and getting removed from the engine as a result.
