### ISSUE TITLE
partially initialized module 'docker' has no attribute 'from_env' on arch linux

### ISSUE THREAD

**Issue by zkrmftj** [docker/docker-py#3104]
Hello everyone!

I got error when run my python code, it looks like docker module not working on my system
# Python Docker Run Environment
Linux
```
Linux linux 6.2.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 18 Mar 2023 01:06:36 +0000 x86_64 GNU/Linux
```
Python
```
○ → python --version
Python 3.10.10
```
Python Docker
```
pip freeze | grep docker
docker==6.0.1
docker-py==1.10.6
docker-pycreds==0.4.0
```
# The error
When I create object for client the error looks like this:
```
Traceback (most recent call last):
  File "/home/aji/async/docker.py", line 1, in <module>
    import docker
  File "/home/aji/async/docker.py", line 9, in <module>
    run_container()
  File "/home/aji/async/docker.py", line 5, in run_container
    client = docker.from_env()
AttributeError: partially initialized module 'docker' has no attribute 'from_env' (most likely due to a circular import)
```
if you got any vision just discus with me here :)
Thank you in advance!

**Comment by edraft** [comment]
How did you fix that?
