### ISSUE TITLE
How does docker-py use websocket to correctly connect to the container terminal for interaction

### ISSUE THREAD

**Issue by 745719408** [docker/docker-py#3133]
My python: 3.7.0, django: 3.2.15, channels: 3.0.5, docker: 6.0.1
The following error will be reported when establishing a websocket connection. I don’t know where the problem is. Please answer the question
terminal_consumers.py
` import docker
from threading import Thread
from channels.generic.websocket import WebsocketConsumer,AsyncWebsocketConsumer
from docker.errors import NotFound
from urllib.parse import parse_qs
import dockerpty

class DockerStreamThread(Thread):
    def __init__(self, websocket, container_stream):
        Thread.__init__(self)
        self.websocket = websocket
        self.stream = container_stream

    def run(self):
        for line in self.stream:
            self.websocket.send(line)

class TerminalConsumer(AsyncWebsocketConsumer):
    async def connect(self):

        query_params = parse_qs(self.scope["query_string"].decode())
        self.address = query_params.get("address", [""])[0]
        self.port = query_params.get("port", [""])[0]
        self.containers = query_params.get("containers", [""])[0]
        remote_docker_host = f'tcp://{self.address}:{self.port}'
        client = docker.DockerClient(base_url=remote_docker_host)

        try:
            self.container = client.containers.get(self.containers)

            await self.accept()

            container_stream = self.container.attach(stream=True, stdout=True, stderr=True, logs=True)
            docker_thread = DockerStreamThread(self, container_stream)
            docker_thread.start()
            
        except Exception as e:
            print(e)

    async def disconnect(self, close_code):
        self.close()

    async def receive(self, text_data):

        exec_instance = self.container.exec_run(cmd=text_data, tty=True)
        output = exec_instance.output[1]

        if isinstance(output, bytes):

            output = output.decode('utf-8')
        else:

            output = str(output)
            

        await self.send(text_data=output)

        `
report error
`
Exception inside application: 400 Client Error for http://192.168.1.225:2375/v1.39/containers/cddb8aa4dfa6ac65460f5504d2cd43881ed0ca44f180b4ebc2b046d33e1fa533/exec: Bad Request ("No exec command specified")
Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/bin/python3/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.1.225:2375/v1.39/containers/cddb8aa4dfa6ac65460f5504d2cd43881ed0ca44f180b4ebc2b046d33e1fa533/exec

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/channels/generic/websocket.py", line 194, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/root/shell/k8s_log/k8s_log/websocket/terminal_consumers.py", line 49, in receive
    exec_instance = self.container.exec_run(cmd=text_data, tty=True)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/models/containers.py", line 196, in exec_run
    workdir=workdir,
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/api/exec_api.py", line 78, in exec_create
    return self._result(res, True)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/bin/python3/lib/python3.7/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://192.168.1.225:2375/v1.39/containers/cddb8aa4dfa6ac65460f5504d2cd43881ed0ca44f180b4ebc2b046d33e1fa533/exec: Bad Request ("No exec command specified")
WebSocket DISCONNECT /docker_terminal/ [127.0.0.1:52405]
`

**Comment by milas** [comment]
The error is being shown:
```
400 Bad Request
No exec command specified
```

You need to ensure your command is not empty as stated.

I can't provide further support here, given what you've shared, there's no indication this is a bug in `docker-py`.
