### ISSUE TITLE
Container.exec_run crashes with BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Hubro** [docker/docker-py#3218]
Code:

```python
docker_client = docker.from_env(use_ssh_client=True)

my_container = docker_client.containers.run(
    IMAGE_NAME,
    detach=True,
    remove=True,
    name=CONTAINER_NAME,
)

result = my_container.exec_run(
    ["sleep", "5"]
)
```

Crash stack trace:

```
  ...

  File "/path/to/my-script.py", line 193, in wait_started
    result = my_container.exec_run(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/docker/models/containers.py", line 210, in exec_run
    exec_output = self.client.api.exec_start(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/docker/api/exec_api.py", line 173, in exec_start
    output = self._read_from_socket(res, stream, tty=tty, demux=demux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/docker/api/client.py", line 437, in _read_from_socket
    response.close()
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/requests/models.py", line 1030, in close
    self.raw.close()
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/urllib3/response.py", line 630, in close
    self._connection.close()
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/http/client.py", line 964, in close
    sock.close()   # close it manually... there may be other refs
    ^^^^^^^^^^^^
  File "/path/to/my/virtualenv/lib/python3.11/site-packages/docker/transport/sshconn.py", line 94, in close
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

I'm using `use_ssh_client` because I need a SSH ProxyJump to reach the Docker host and for some reason it doesn't work when using Paramiko, it just times out. With `use_ssh_client` everything seems to work, I'm able to list and pull images, run containers etc. but running `exec_run` crashes every time.

```
$ pip freeze | grep docker
docker==7.0.0
```

**Comment by Khushiyant** [comment]
The problem stems from the way the `use_ssh_client` capability is implemented in the Docker library. When `use_ssh_client` is set to `True`, the library connects to the Docker host using the SSH client installed on your machine. This is not a standard TCP socket, but rather a pipe connected to the SSH client process.

When you use `exec_run` on a container, the library attempts to read from the SSH connection via a socket-like interface. However, when the SSH client process terminates (for example, owing to a timeout or a `BrokenPipeError`), the pipe is closed, and all subsequent efforts to read from it result in a BrokenPipeError.

**Comment by shaoyijia** [comment]
Hi @Khushiyant , I am trying to use run execute code in Jupyter Docker environment using docker-py. I also run into `BrokenPipeError: [Errno 32] Broken pipe` from time to time (not always, but frequently).

Here is a minimal example of my code:
```python
import atexit
import datetime
import io
import json
import secrets
import time
import uuid
from pathlib import Path
from typing import Any, cast, Dict, Optional

import docker
import requests
import websocket


def _wait_for_ready(container: Any, timeout: int = 60, stop_time: float = 0.1) -> None:
    elapsed_time = 0.0
    while container.status != "running" and elapsed_time < timeout:
        time.sleep(stop_time)
        elapsed_time += stop_time
        container.reload()
        continue
    if container.status != "running":
        raise ValueError("Container failed to start")


def main():
    image_name = 'debug-jupyterkernel'
    DEFAULT_DOCKERFILE = """FROM quay.io/jupyter/docker-stacks-foundation

    SHELL ["/bin/bash", "-o", "pipefail", "-c"]

    USER ${NB_UID}
    RUN mamba install --yes jupyter_kernel_gateway ipykernel && \
        mamba clean --all -f -y && \
        fix-permissions "${CONDA_DIR}" && \
        fix-permissions "/home/${NB_USER}"

    ENV TOKEN="UNSET"
    CMD python -m jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0 \
        --KernelGatewayApp.port=8888 \
        --KernelGatewayApp.auth_token="${TOKEN}" \
        --JupyterApp.answer_yes=true \
        --JupyterWebsocketPersonality.list_kernels=true

    EXPOSE 8888

    WORKDIR "${HOME}"
    """
    client = docker.from_env()
    try:
        client.images.get(image_name)
    except docker.errors.ImageNotFound:
        # Build the image
        # Get this script directory
        here = Path(__file__).parent
        dockerfile = io.BytesIO(DEFAULT_DOCKERFILE.encode("utf-8"))
        client.images.build(path=here, fileobj=dockerfile, tag=image_name)
    token = secrets.token_hex(32)
    env = {"TOKEN": token}
    container = client.containers.run(
        image_name,
        detach=True,
        auto_remove=True,
        environment=env,
        publish_all_ports=True,
    )
    print(container.logs().decode())
    _wait_for_ready(container)
    time.sleep(3)

    def cleanup() -> None:
        try:
            inner_container = client.containers.get(container.id)
            inner_container.stop()
        except docker.errors.NotFound:
            pass

    atexit.register(cleanup)

    port = int(container.ports["8888/tcp"][0]["HostPort"])

    connection_info = {
        'host': '127.0.0.1',
        'use_https': False,
        'port': port,
        'token': token
    }

    # Start a new kernel
    session = requests.Session()
    api_base_url = f"http://{connection_info['host']}:{connection_info['port']}/api/kernels"
    headers = {"Authorization": f"token {connection_info['token']}"}
    response = session.post(
        api_base_url,
        headers=headers,
        json={"name": "python3"},
    )
    kernel_id = cast(str, response.json()["id"])
    print(f'Kernel ID: {kernel_id}')

    # JupyterKernelClient
    session_id = uuid.uuid4().hex
    ws_url = f"ws://{connection_info['host']}:{connection_info['port']}/api/kernels/{kernel_id}/channels"
    ws = websocket.create_connection(ws_url, header=headers)
    ws.settimeout(30 * 60)  # Set a long timeout for the websocket.

    def send_message(content: Dict[str, Any], channel: str, message_type: str) -> str:
        timestamp = datetime.datetime.now().isoformat()
        message_id = uuid.uuid4().hex
        message = {
            "header": {
                "username": "debug",
                "version": "0.1",
                "session": session_id,
                "msg_id": message_id,
                "msg_type": message_type,
                "date": timestamp,
            },
            "parent_header": {},
            "channel": channel,
            "content": content,
            "metadata": {},
            "buffers": {},
        }
        ws.send_text(json.dumps(message))
        return message_id

    def receive_message(timeout_seconds: Optional[float]) -> Optional[Dict[str, Any]]:
        ws.settimeout(timeout_seconds)
        try:
            data = ws.recv()
            if isinstance(data, bytes):
                data = data.decode("utf-8")
            return cast(Dict[str, Any], json.loads(data))
        except websocket.WebSocketTimeoutException:
            return None

    def wait_for_kernel_client_ready(timeout_seconds: Optional[float] = None) -> bool:
        message_id = send_message(content={}, channel="shell", message_type="kernel_info_request")
        cnt = 0
        while True:
            cnt += 1
            print(f"Waiting for kernel to be ready: {cnt}")
            message = receive_message(timeout_seconds)
            # This means we timed out with no new messages.
            if message is None:
                return False
            if (
                    message.get("parent_header", {}).get("msg_id") == message_id
                    and message["msg_type"] == "kernel_info_reply"
            ):
                return True

    wait_for_kernel_client_ready()

    # Delete the kernel
    session.delete(f"http://{connection_info['host']}:{connection_info['port']}/api/kernels/{kernel_id}")


if __name__ == '__main__':
    main()
```

I don't always run into the BrokenPipe error, but occasionally run into it when looping in `wait_for_kernel_client_ready()`. This error appears more frequently if I have started the connection for a long time (even though I have already set a very long time-out period). For example, when I run the loop step by step with breakpoint, I may get the error log like this
```
> ${mydir}/debug_docker.py(159)wait_for_kernel_client_ready()
-> print(f"Waiting for kernel to be ready: {cnt}")
(Pdb) c
Waiting for kernel to be ready: 5
> ${mydir}/debug_docker.py(159)wait_for_kernel_client_ready()
-> print(f"Waiting for kernel to be ready: {cnt}")
(Pdb) c
Waiting for kernel to be ready: 6
Waiting for execution: 1
Traceback (most recent call last):
  File "${mydir}/debug_docker.py", line 227, in <module>
    main()
  File "${mydir}/debug_docker.py", line 220, in main
    execute(code)
  File "${mydir}/debug_docker.py", line 189, in execute
    message = receive_message(timeout_seconds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${mydir}/debug_docker.py", line 145, in receive_message
    data = ws.recv()
           ^^^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 388, in recv
    opcode, data = self.recv_data()
                   ^^^^^^^^^^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 416, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 457, in recv_data_frame
    self.send_close()
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 494, in send_close
    self.send(struct.pack("!H", status) + reason, ABNF.OPCODE_CLOSE)
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 297, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 337, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_core.py", line 559, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_socket.py", line 176, in send
    return _send()
           ^^^^^^^
  File "/nlp/scr/shaoyj/miniconda3/envs/agent/lib/python3.11/site-packages/websocket/_socket.py", line 153, in _send
    return sock.send(data)
           ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
```

I am not sure whether the problem is related to docker side or related to websocket. I don't really know how to debug this issue and am looking for help.

Thank you so much for your help!
