### ISSUE TITLE
`unix://` client URL fails

### ISSUE THREAD

**Issue by AstraLuma** [docker/docker-py#3303]
Doing https://github.com/docker/docker-py/issues/3146#issuecomment-1834480674 , and I'm now getting errors like:

```
  File "/home/astraluma/code/unholy/unholy/docker.py", line 48, in get_client
    return docker.DockerClient(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
```

The initial root looks like:

https://github.com/docker/docker-py/blob/03e43be6af9b21f9f966eb84ca46a159b664ccf4/docker/api/client.py#L153

where it looks for `http+unix://` but not `unix://`.

But if I munge the URL to be `http+unix://` instead, I get:

```
Traceback (most recent call last):
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/requests/adapters.py", line 633, in send
    conn = self.get_connection_with_tls_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/requests/adapters.py", line 489, in get_connection_with_tls_context
    conn = self.poolmanager.connection_from_host(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/unholy/lib/python3.12/site-packages/urllib3/poolmanager.py", line 325, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker
```

Note that the Docker CLI is fine with `unix://`.

**Comment by AstraLuma** [comment]
```
$ docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT                            ERROR
default *   Current DOCKER_HOST based configuration   unix:///run/user/1000/podman/podman.sock   
docker      system docker                             unix:///var/run/docker.sock                
podman      user podman                               unix:///run/user/1000/podman/podman.sock   
Warning: DOCKER_HOST environment variable overrides the active context. To use a context, either set the global --context flag, or unset DOCKER_HOST environment variable.
```

**Comment by felixfontein** [comment]
Searching for that error message in this repo gives you #3256.

Using a newer version of Docker SDK for Python or a newer or older version of Python requests should fix the problem.

**Comment by AstraLuma** [comment]
Yeah, looks fixed.
