### ISSUE TITLE
Better documentation for connecting with TLS

### ISSUE THREAD

**Issue by micahhausler** [docker/docker-py#365]
I followed the examples in the `README.md`, but I could only get errors.
## Version info

```
$ docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): darwin/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f

$ boot2docker version
Boot2Docker-cli version: v1.3.0
Git commit: deafc19

$ boot2docker ip
The VM's Host only interface IP address is: 192.168.59.103

$ python -V
2.7.7

$ pip freeze
backports.ssl-match-hostname==3.4.0.2
docker-py==0.5.3
requests==2.4.3
six==1.8.0
websocket-client==0.21.0
wsgiref==0.1.2
```

And tried the following code:

```
import ssl
from docker import Client
from docker.tls import TLSConfig

url = 'https://192.168.59.103:2376'
cert_dir = '/Users/micahhausler/.boot2docker/certs/boot2docker-vm/'

tls_config = TLSConfig(verify=False)
client = Client(base_url=url, tls=tls_config)
print(client.images())
```

```
Traceback (most recent call last):
File "test.py", line 38, in <module>
print(client.images())
File "/Users/micahhausler/code/open_source/docker-py/docker/client.py", line 1005, in images
res = self._result(self._get(self._url("/images/json"), params=params),
                   File "/Users/micahhausler/code/open_source/docker-py/docker/client.py", line 164, in _get
return self.get(url, **self._set_request_timeout(kwargs))
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 469, in get
return self.request('GET', url, **kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/adapters.py", line 420, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
```

Specifying the certs:

```
tls_config = TLSConfig(
  client_cert=(cert_dir + 'cert.pem', cert_dir + 'key.pem'),
  ca_cert=cert_dir + 'ca.pem',
)
client = Client(base_url=url, tls=tls_config)
print(client.images())
```

```
Traceback (most recent call last):
File "test.py", line 65, in <module>
print(client.images())
File "/Users/micahhausler/code/open_source/docker-py/docker/client.py", line 1005, in images
res = self._result(self._get(self._url("/images/json"), params=params),
                   File "/Users/micahhausler/code/open_source/docker-py/docker/client.py", line 164, in _get
return self.get(url, **self._set_request_timeout(kwargs))
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 469, in get
return self.request('GET', url, **kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/adapters.py", line 420, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Even trying to set the protocol to SSLv2 failed:

```
tls_config = TLSConfig(
  client_cert=(cert_dir + 'cert.pem', cert_dir + 'key.pem'),
  ca_cert=cert_dir + 'ca.pem', ssl_version=ssl.PROTOCOL_SSLv2
)
client = Client(base_url=url, tls=tls_config)
print(client.images())
```

```
Traceback (most recent call last):
File "test.py", line 114, in <module>
print(client.images())
File "/Users/micahhausler/code/open_source/docker-py/docker/client.py", line 1005, in images
res = self._result(self._get(self._url("/images/json"), params=params),
                   File "/Users/micahhausler/code/open_source/docker-py/docker/client.py", line 164, in _get
return self.get(url, **self._set_request_timeout(kwargs))
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 469, in get
return self.request('GET', url, **kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/Users/micahhausler/code/open_source/docker-py/testenv/lib/python2.7/site-packages/requests/adapters.py", line 420, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 6] _ssl.c:510: TLS/SSL connection has been closed
```

**Comment by RacingDawn** [comment]
> http://blog.sequenceiq.com/blog/2014/10/17/boot2docker-tls-workaround/

hello，how to bypass tls? the wed page is invalid.

**Comment by RacingDawn** [comment]
> Does #360 help at all?

i follow as #360. but the log is:
![image](https://user-images.githubusercontent.com/13477849/54477069-168d2880-483f-11e9-84d0-9fd32fdcb1c5.png)
