### ISSUE TITLE
Support a range of versions for the requests library

### ISSUE THREAD

**Issue by nickjoyce-wf** [docker/docker-py#415]
The ``requests`` library is hard pinned to ``2.2.1`` in ``requirements.txt`` and ``requirements3.txt``.

I would like to use ``2.4.3`` in a library I am working on due to various improvements/bug fixes (when compared to ``2.2.1``) but because of the hard pin, when invoking a ``console_scripts`` built command, I get an exception:

```python
Traceback (most recent call last):
  File "/Users/nick/.virtualenvs/example/bin/my-example-command", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/nick/.virtualenvs/example/lib/python2.7/site-packages/pkg_resources.py", line 2880, in <module>
    working_set = WorkingSet._build_master()
  File "/Users/nick/.virtualenvs/example/lib/python2.7/site-packages/pkg_resources.py", line 434, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/nick/.virtualenvs/example/lib/python2.7/site-packages/pkg_resources.py", line 447, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/nick/.virtualenvs/example/lib/python2.7/site-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(tmpl % args)
pkg_resources.VersionConflict: requests 2.4.3 is installed but requests==2.2.1 is required by ['docker-py']
```

Installed versions:
```
setuptools==7.0
pip==1.5.6
```

**Comment by nir0s** [comment]
You can always install requests prior to installing docker-py and get the desired version.

**Comment by nickjoyce-wf** [comment]
@nir0s Yes, that is a possible workaround, but that doesn't necessarily mean that ``docker-py`` will support that version

**Comment by nir0s** [comment]
So your request is not to allow you to use a different version of requests. It's that docker-py should support the latest version...

**Comment by nickjoyce-wf** [comment]
@nir0s I think ``docker-py`` should support a minimum version of requests, something like ``requests >=2.2.1 <= 3.0``.

Thoughts?

**Comment by shin-** [comment]
https://github.com/docker/docker-py/blob/master/setup.py#L10

**Comment by nickjoyce-wf** [comment]
Looks like that solves this issue - thanks!
