### ISSUE TITLE
_stream_helper chunked reponse assertion breaks when Client.build() is called with a malformed namespace name

### ISSUE THREAD

**Issue by omribahumi** [docker/docker-py#443]
When running
```python
import docker
import docker.utils
from io import BytesIO

client = docker.Client(**docker.utils.kwargs_from_env())
print "\n".join(client.build(fileobj=BytesIO(), tag="a/b/c"))
```

I get an exception:
```python
Traceback (most recent call last):
  File "/Users/omrib/git/docker/main.py", line 6, in <module>
    print "\n".join(client.build(fileobj=BytesIO(), tag="a/b/c"))
  File "/Users/omrib/git/docker/env/lib/python2.7/site-packages/docker/client.py", line 295, in _stream_helper
    assert reader._fp.chunked
AssertionError
```

When commenting the ```assert``` line, it behaves as expected:
```
Invalid namespace name (a), only [a-z0-9_] are allowed, size between 4 and 30
```

Either the server should always return a chunked response on this call, or the assertion should be turned off (the right way of solving this, IMHO).

**Comment by davibe** [comment]
which docker version are you running docker-py against ?

**Comment by omribahumi** [comment]
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by shin-** [comment]
Thank you!
