### ISSUE TITLE
local system: "client and server don't have same version (client : 1.16, server: 1.15)"

### ISSUE THREAD

**Issue by zopyx** [docker/docker-py#446]
docker-py 0.7.0 gives me the following error against a local Docker installation of Docker 1.3.2
and docker-py 0.7.0. The host ist running CentOS 6.6. How can this be fixed?

    
    xxxx@dev1 myproject]$ bin/python d.py
    Traceback (most recent call last):
      File "d.py", line 3, in <module>
        c.create_container(image='zopyx/xmldirector-plone')
      File "/home/xxxx/sandboxes/myproject/lib/python2.7/site-packages/docker/client.py", line 546, in create_container
        return self.create_container_from_config(config, name)
      File "/home/xxxx/sandboxes/myproject/lib/python2.7/site-packages/docker/client.py", line 554, in create_container_from_config
        return self._result(res, True)
      File "/home/xxxx/sandboxes/myproject/lib/python2.7/site-packages/docker/client.py", line 98, in _result
        self._raise_for_status(response)
      File "/home/xxxx/sandboxes/myproject/lib/python2.7/site-packages/docker/client.py", line 94, in _raise_for_status
        raise errors.APIError(e, response, explanation=explanation)
    docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.16, server: 1.15)")

    >>docker --version
    Docker version 1.3.2, build 39fa2fa/1.3.2

    >>docker version
    Client version: 1.3.2
    Client API version: 1.15
    Go version (client): go1.3.3
    Git commit (client): 39fa2fa/1.3.2
    OS/Arch (client): linux/amd64
    Server version: 1.3.2
    Server API version: 1.15
    Go version (server): go1.3.3
    Git commit (server): 39fa2fa/1.3.2

**Comment by shin-** [comment]
```python

import docker
c = docker.Client(version='1.15')
```

or update Docker to 1.4.1
