### ISSUE TITLE
Running tests on btrfs fails consistently on `tearDown`

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker-py#450]
see output of logs here:
https://jenkins.dockerproject.com/job/Docker%20Master/label=ubuntu-btrfs/141/console

But it does pass sometime, but once it fails, it fails over and over and over again.

Which you can see here: https://jenkins.dockerproject.com/job/Docker%20Master/label=ubuntu-btrfs/

**Comment by jfrazelle** [comment]
I'm wiping the device now to see if that helps.

**Comment by shin-** [comment]
Is it always this same test that's failing? Always a timeout?
```
======================================================================
ERROR: runTest (__main__.TestCommit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/integration_test.py", line 64, in tearDown
    self.client.remove_container(container)
  File "/docker-py/docker/client.py", line 885, in remove_container
    params=params)
  File "/docker-py/docker/client.py", line 84, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 526, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
    raise Timeout(e)
Timeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=5)

----------------------------------------------------------------------
Ran 56 tests in 92.059s

FAILED (errors=1)
```

**Comment by jfrazelle** [comment]
ya it's always that test

**Comment by jfrazelle** [comment]
hmmm its working now that I cleared the device so closing until I see it again
