### ISSUE TITLE
create_container() doesn't remote pull for you

### ISSUE THREAD

**Issue by br0ch0n** [docker/docker-py#501]
I'm assuming that like 'docker run', create_container should fetch images for you. However, it seems I have to do it myself via pull() first?  Is this expected? The docs imply no.

``` 
>>> c = Client(base_url='unix://var/run/docker.sock')
>>> ct = c.create_container(image='redis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 425, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 433, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 99, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("No such image: redis (tag: latest)")
```
but, 
```
>>> im = c.pull('redis')
>>> print im
{"status":"Pulling repository redis"}
{"status":"Pulling image (2.8.17) from redis","progressDetail":{},"id":"dad71287aacb"}{"status":"Pulling image (2.8.17) from redis, endpoint: https://registry-1.docker.io/v1/","progressDetail":{},"id":"dad71287aacb"}{"status":"Pulling image (2.8.12) from redis","progressDetail":{},"id":"a2f8e5952444"}{"status":"Pulling image (2.8.12) from redis, endpoint: https://registry-1.docker.io/v1/","progressDetail":{},"id":"a2f8e5952444"}{"status":"Pulling image (2.8.7) from redis","progressDetail":{},"id":"818c43182340"} (etc etc truncated...all good)

```
and then I can
```
>>> ct = c.create_container(image='redis')
>>> print ct
{u'Id': u'7e14f8f92998ec76d4825b8c0667da1b194e4cbde1eb004d30f91371ff6c625b', u'Warnings': None}
```

?

**Comment by shin-** [comment]
Hi,

Thanks for your report! This is working as intended.

**Comment by br0ch0n** [comment]
I'm assuming this is because /containers/create in the remote api (which I believe docker-py is using) doesn't pull for you?  I'm fine working around it, but just out of curiosity, is there a reason it doesn't?  I'd think it would be the same as the 'docker create' command, which does pull for you.

**Comment by shin-** [comment]
> /containers/create in the remote api (which I believe docker-py is using) doesn't pull for you?

Yep

> is there a reason it doesn't?

It's a docker CLI feature for ease of use (if image isn't present, try to pull it, then re-run the create command). When using the API programmatically you want to privilege control over ease of use, and avoid side effects like that.

Hope that makes sense!

**Comment by br0ch0n** [comment]
OK, makes sense.  Thanks for clarifying.
