### ISSUE TITLE
Ubuntu 14.10: system-wide pip is broken by docker-py

### ISSUE THREAD

**Issue by vitalyisaev2** [docker/docker-py#525]
My case may seem bad practice for some part of the community, but I really need to provide an access to the Docker Python API for a running docker container (e.g. mount /var/run/docker.sock into container). Our team use Ubuntu 14.10 both for development and production. So I just wanted to install the *latest* version of **docker-py** directly to system directories (using system-wide **pip**) of my Docker container. I didn't want to resort to virtualenv inside a container because it's an excess level of isolation.

Unfortunately installation of **docker-py** anywhere outside the virtualenv leads to **pip** corruption on the recent version of Ubuntu. I guess that the reason is broken backward compatibility of **requests** module.
```bash
$ docker run -it --rm ubuntu:utopic bash
$ apt-get update
$ apt-get install -y python-pip
$ pip install docker-py
$ pip freeze
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```
There are a lot of workarounds here (install virtualenv inside container, etc), but probably it's possible just to reconfigure docker-py for the mentioned distribution.

**Comment by TomasTomecek** [comment]
How about `pip install --user docker-py`?

**Comment by vitalyisaev2** [comment]
The same error in my case. 

```sh
root@44ca347ef5d4:/# pip install --user docker-py
Downloading/unpacking docker-py
  Downloading docker-py-1.1.0.tar.gz (42kB): 42kB downloaded
  Running setup.py (path:/tmp/pip_build_root/docker-py/setup.py) egg_info for package docker-py
    
Downloading/unpacking requests>=2.5.2 (from docker-py)
  Downloading requests-2.5.3-py2.py3-none-any.whl (468kB): 468kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/lib/python2.7/dist-packages (from docker-py)
Downloading/unpacking websocket-client>=0.11.0 (from docker-py)
  Downloading websocket_client-0.26.0.tar.gz (189kB): 189kB downloaded
  Running setup.py (path:/tmp/pip_build_root/websocket-client/setup.py) egg_info for package websocket-client
    
Downloading/unpacking backports.ssl-match-hostname (from websocket-client>=0.11.0->docker-py)
  Downloading backports.ssl_match_hostname-3.4.0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
    
Installing collected packages: docker-py, requests, websocket-client, backports.ssl-match-hostname
  Running setup.py install for docker-py
    
  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 644 to 755
    
    changing mode of /root/.local/bin/wsdump.py to 755
  Running setup.py install for backports.ssl-match-hostname
    
Successfully installed docker-py requests websocket-client backports.ssl-match-hostname
Cleaning up...
root@44ca347ef5d4:/# pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

```

**Comment by TomasTomecek** [comment]
First thing: this should be definitely reported in ubuntu's, request's and/or pip's issue tracker. It's not docker-py's fault that pip can't handle new version of requests.

What may work is to update pip first, then install docker-py. (wanted to try it out, but it takes ages to install pip from ubuntu's repositories):

```shell
$ pip install --upgrade pip
$ pip install docker-py
```

**Comment by TomasTomecek** [comment]
This has worked for me:

```shell
$ apt-get install -y python-pip
$ pip install -U --user pip
$ pip install --user docker-py
$ ~/.local/bin/pip

Usage:   
  pip <command> [options]
...
```

**Comment by vitalyisaev2** [comment]
Thanks!
