### ISSUE TITLE
create_container with entrypoint is double escaped

### ISSUE THREAD

**Issue by omribahumi** [docker/docker-py#672]
```python
$ pip freeze | grep -i docker
docker-py==1.2.3
$ cat bug.py
from docker import Client
from docker.utils import kwargs_from_env

client = Client(version='auto', **kwargs_from_env())
container = client.create_container('ubuntu:14.04', entrypoint='/bin/sh')
client.start(container=container['Id'])
$ python bug.py
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    client.start(container=container['Id'])
  File "/Users/omrib/git/stabber/env/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/omrib/git/stabber/env/lib/python2.7/site-packages/docker/client.py", line 1076, in start
    self._raise_for_status(res)
  File "/Users/omrib/git/stabber/env/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("Cannot start container d00ac5da33c7e0f01a3f04435566c9d48d8acf40b51637aba5f31e97cd44d909: [8] System error: exec: "\"/bin/sh\"": stat "/bin/sh": no such file or directory")
```

`docker inspect` on the container yields:
```javascript
// ...
        "Entrypoint": [
            "\"/bin/sh\""
        ],
// ...
```

As you can see, it looks double-escaped. Not sure why.
When creating the same container with the docker CLI things are ok:
```
$ docker create --entrypoint /bin/sh ubuntu:14.04
ffd55d6cda782c87ceb41d754db424c462b5bbb0731ce3f011805a04184d577b
$ docker inspect ffd55d6cda782c87ceb41d754db424c462b5bbb0731ce3f011805a04184d577b
// ...
        "Entrypoint": [
            "/bin/sh"
        ],
// ...
```

I'm using docker 1.7.0 with boot2docker on OSX:
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by aanand** [comment]
This is a Docker 1.7.0 bug (https://github.com/docker/docker/issues/14170), and will be fixed in 1.7.1.

**Comment by aanand** [comment]
You can work around it for now by passing `entrypoint` as a list, e.g. `entrypoint=['/bin/sh']`

**Comment by omribahumi** [comment]
Thanks
