### ISSUE TITLE
hostname 'w.x.y.z' doesn't match 'boot2docker', even though 'w.x.y.z' is allowed by the certificate

### ISSUE THREAD

**Issue by posita** [docker/docker-py#706]
This may be a dup of #406, but I don't think that's fixed (yes, there's an [`/etc/hosts` hack/work-around](https://github.com/docker/docker-py/blob/master/docs/boot2docker.md), but it doesn't address the underlying issue). You can see this when doing the following:

```sh
% mkdir -p foo
% virtualenv foo
...
% cd foo
% . ./bin/activate
% pip install requests==2.2.1 # it was suggested that >=2.5.0 was a cause
...
% pip install docker-py
...
% unset DOCKER_CERT_PATH DOCKER_HOST DOCKER_TLS_VERIFY
% export DOCKER_HOST=tcp://10.68.69.86:2376
% export DOCKER_TLS_VERIFY=0
% export DOCKER_CERT_PATH="${HOME}/.docker"
% cat >test.py
```

```py
from docker import AutoVersionClient
from docker.utils import kwargs_from_env
dc = AutoVersionClient(**kwargs_from_env())
```
```sh
^D
% python test.py
python test.py
Traceback (most recent call last):
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 172, in connect
    self.assert_hostname or self.host)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 289, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname '10.68.69.86' doesn't match 'boot2docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../foo/lib/python3.4/site-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 508, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: hostname '10.68.69.86' doesn't match 'boot2docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 65, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File ".../foo/lib/python3.4/site-packages/docker/client.py", line 837, in version
    return self._result(self._get(url), json=True)
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File ".../foo/lib/python3.4/site-packages/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File ".../foo/lib/python3.4/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File ".../foo/lib/python3.4/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File ".../foo/lib/python3.4/site-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname '10.68.69.86' doesn't match 'boot2docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dc = AutoVersionClient(**kwargs_from_env())
  File ".../foo/lib/python3.4/site-packages/docker/client.py", line 863, in __init__
    super(AutoVersionClient, self).__init__(*args, **kwargs)
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 53, in __init__
    self._version = self._retrieve_server_version()
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 73, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: hostname '10.68.69.86' doesn't match 'boot2docker'
```

But `docker ps` works fine and `10.68.69.86` is listed in the server certificate:

```sh
% DOCKER_TLS_VERIFY=0 docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
% DOCKER_TLS_VERIFY=1 docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
% ssh docker@10.68.69.86 sudo openssl x509 -in /var/lib/boot2docker/tls/server.pem -text
docker@10.68.69.86's password:
Certificate:
    Data:
        ...
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:boot2docker, IP Address:127.0.0.1, IP Address:10.211.55.253, IP Address:10.68.69.86
...
```

What's weird (maybe) is that this works (partially):

```sh
% cat >test2.py
```

```py
from os import environ
from os.path import join as ospath_join
try:
    from urllib.parse import ( # pylint: disable=no-name-in-module
        urlparse,
        urlunparse,
    )
except ImportError:
    from urlparse import ( # pylint: disable=no-name-in-module
        urlparse,
        urlunparse,
    )
from docker import AutoVersionClient
from docker.tls import TLSConfig
from docker.utils.utils import DEFAULT_UNIX_SOCKET
DOCKER_CERT_PATH = environ.get('DOCKER_CERT_PATH', None)
DOCKER_HOST = environ.get('DOCKER_HOST', DEFAULT_UNIX_SOCKET)
DOCKER_TLS_VERIFY = environ.get('DOCKER_TLS_VERIFY', None)

if DOCKER_CERT_PATH:
    docker_host = urlparse(DOCKER_HOST)
    DOCKER_HOST = urlunparse(( 'https', ) + docker_host[1:])

    tls_config_args = {
        'client_cert': (
            ospath_join(DOCKER_CERT_PATH, 'cert.pem'),
            ospath_join(DOCKER_CERT_PATH, 'key.pem'),
        ),
    }

    if DOCKER_TLS_VERIFY is not None:
        tls_config_args['verify'] = ospath_join(DOCKER_CERT_PATH, 'ca.pem') if DOCKER_TLS_VERIFY != '0' else False

    tls = TLSConfig(**tls_config_args)
else:
    tls = False

dc = AutoVersionClient(DOCKER_HOST, tls=tls)
```

```sh
^D
% python test2.py # works, but
% DOCKER_TLS_VERIFY=1 python test2.py # fails with hostname '10.68.69.86' doesn't match 'boot2docker' like above
...
```

**Comment by shin-** [comment]
Also being discussed in #731

**Comment by posita** [comment]
FYI, the original error is being raised [here](https://github.com/python/cpython/blob/2.7/Lib/ssl.py#L273) (note the path to the standard library from `requests`):

```py
(Pdb) bt
  ...
  /.../lib/python2.7/site-packages/docker/client.py(325)__init__()
-> super(AutoVersionClient, self).__init__(*args, **kwargs)
  /.../lib/python2.7/site-packages/docker/client.py(77)__init__()
-> self._version = self._retrieve_server_version()
  /.../lib/python2.7/site-packages/docker/client.py(89)_retrieve_server_version()
-> return self.version(api_version=False)["ApiVersion"]
  /.../lib/python2.7/site-packages/docker/api/daemon.py(78)version()
-> return self._result(self._get(url), json=True)
  /.../lib/python2.7/site-packages/docker/client.py(110)_get()
-> return self.get(url, **self._set_request_timeout(kwargs))
  /.../lib/python2.7/site-packages/requests/sessions.py(477)get()
-> return self.request('GET', url, **kwargs)
  /.../lib/python2.7/site-packages/requests/sessions.py(465)request()
-> resp = self.send(prep, **send_kwargs)
  /.../lib/python2.7/site-packages/requests/sessions.py(573)send()
-> r = adapter.send(request, **kwargs)
  /.../lib/python2.7/site-packages/requests/adapters.py(370)send()
-> timeout=timeout
  /.../lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py(544)urlopen()
-> body=body, headers=headers)
  /.../lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py(341)_make_request()
-> self._validate_conn(conn)
  /.../lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py(761)_validate_conn()
-> conn.connect()
  /.../lib/python2.7/site-packages/requests/packages/urllib3/connection.py(253)connect()
-> match_hostname(cert, self.assert_hostname or hostname)
> /.../lib/python2.7/ssl.py(273)match_hostname()
-> raise CertificateError("hostname %r "
(Pdb) dnsnames
['localhost']
(Pdb) hostname
'10.211.55.34'
(Pdb) cert
{'subjectAltName': (('DNS', 'localhost'), ('IP Address', '10.211.55.34')), 'notBefore': u'Nov 28 05:52:00 2015 GMT', 'serialNumber': u'930745814BB1FC51B9785C5811FCAA2D', 'notAfter': 'Nov 12 05:52:00 2018 GMT', 'version': 3L, 'subject': ((('organizationName', u'xyz.test'),),), 'issuer': ((('organizationName', u'xyz'),),)}
```

I found these:

* http://docs.python-requests.org/en/latest/community/faq/#what-are-hostname-doesn-t-match-errors
* https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484

But of course those don't address the same issue. If I do a `pip install 'requests[security]'` I get a different error (see this https://github.com/docker/docker-py/issues/816#issuecomment-160264212).
