### ISSUE TITLE
NotFound: 404 Client Error: Not Found ("No such image: test")

### ISSUE THREAD

**Issue by ibmalan** [docker/docker-py#748]
I am using ubuntu 14.0.4 with openstack juno community version, When I spawn a docker instance from controller node, it failed and here is the log from compute node
```
root@nsj7:/var/log/upstart# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

2015-08-28 10:57:16.236 10740 AUDIT nova.compute.manager [req-3e297824-5765-4336-bd8a-7fa61583eb69 None] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Starting instance...
2015-08-28 10:57:16.334 10740 AUDIT nova.compute.claims [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Attempting claim: memory 2048 MB, disk 20 GB
2015-08-28 10:57:16.335 10740 AUDIT nova.compute.claims [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Total memory: 64416 MB, used: 512.00 MB
2015-08-28 10:57:16.336 10740 AUDIT nova.compute.claims [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] memory limit not specified, defaulting to unlimited
2015-08-28 10:57:16.336 10740 AUDIT nova.compute.claims [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Total disk: 915 GB, used: 0.00 GB
2015-08-28 10:57:16.337 10740 AUDIT nova.compute.claims [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] disk limit not specified, defaulting to unlimited
2015-08-28 10:57:16.351 10740 AUDIT nova.compute.claims [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Claim successful
2015-08-28 10:57:16.461 10740 INFO nova.scheduler.client.report [-] Compute_service record updated for ('nsj7', 'nsj7')
2015-08-28 10:57:16.595 10740 INFO nova.scheduler.client.report [-] Compute_service record updated for ('nsj7', 'nsj7')
2015-08-28 10:57:17.026 10740 ERROR nova.compute.manager [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Instance failed to spawn
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Traceback (most recent call last):
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2267, in _build_resources
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     yield resources
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2137, in _build_and_run_instance
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     block_device_info=block_device_info)
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/local/lib/python2.7/dist-packages/novadocker/virt/docker/driver.py", line 388, in spawn
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     image = self.docker.inspect_image(self._encode_utf8(image_name))
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/local/lib/python2.7/dist-packages/novadocker/virt/docker/client.py", line 36, in wrapper
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     out = f(*args, **kwds)
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 20, in wrapped
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     return f(self, resource_id, *args, **kwargs)
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 491, in inspect_image
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     True
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/local/lib/python2.7/dist-packages/docker/clientbase.py", line 108, in _result
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     self._raise_for_status(response)
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]   File "/usr/local/lib/python2.7/dist-packages/docker/clientbase.py", line 103, in _raise_for_status
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371]     raise errors.NotFound(e, response, explanation=explanation)
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371] NotFound: 404 Client Error: Not Found ("No such image: test")
2015-08-28 10:57:17.026 10740 TRACE nova.compute.manager [instance: 3261b9a0-3b88-4756-a56f-704a33524371] 
2015-08-28 10:57:17.111 10740 INFO nova.scheduler.client.report [-] Compute_service record updated for ('nsj7', 'nsj7')
2015-08-28 10:57:17.112 10740 AUDIT nova.compute.manager [req-3e297824-5765-4336-bd8a-7fa61583eb69 None] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Terminating instance
2015-08-28 10:57:17.153 10740 INFO nova.scheduler.client.report [-] Compute_service record updated for ('nsj7', 'nsj7')
2015-08-28 10:57:17.198 10740 INFO nova.network.neutronv2.api [-] [instance: 3261b9a0-3b88-4756-a56f-704a33524371] Unable to reset device ID for port None
2015-08-28 10:57:43.180 10740 AUDIT nova.compute.resource_tracker [-] Auditing locally available compute resources
2015-08-28 10:57:43.246 10740 AUDIT nova.compute.resource_tracker [-] Total physical ram (MB): 64416, total allocated virtual ram (MB): 2560
2015-08-28 10:57:43.247 10740 AUDIT nova.compute.resource_tracker [-] Free disk (GB): 895
2015-08-28 10:57:43.247 10740 AUDIT nova.compute.resource_tracker [-] Total usable vcpus: 1, total allocated vcpus: 0
2015-08-28 10:57:43.248 10740 AUDIT nova.compute.resource_tracker [-] PCI stats: []
2015-08-28 10:57:43.314 10740 INFO nova.scheduler.client.report [-] Compute_service record updated for ('nsj7', 'nsj7')
2015-08-28 10:57:43.315 10740 INFO nova.compute.resource_tracker [-] Compute_service record updated for nsj7:nsj7
root@nsj7:~# 

root@nsj7:/var/log/upstart# tail -n 100 docker.log 
ERRO[7534] HTTP Error                                    err=No such image: nsj7 statusCode=404
INFO[7534] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[7534] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[7534] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[7534] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[7546] Processing signal 'terminated'               
Waiting for /var/run/docker.sock
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Option DefaultDriver: bridge                 
INFO[0000] Option DefaultNetwork: bridge                
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1 
INFO[0000] Firewalld running: false                     
/var/run/docker.sock is up
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   
..
INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=d12ea79 execdriver=native-0.2 graphdriver=aufs version=1.8.1
INFO[0044] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[0044] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[0385] GET /v1.13/images/nsj7/json                  
ERRO[0385] Handler for GET /images/{name:.*}/json returned error: No such image: nsj7 
ERRO[0385] HTTP Error                                    err=No such image: nsj7 statusCode=404
INFO[0386] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[0386] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[0386] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[0386] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[0645] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[0645] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1255] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1255] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1431] GET /v1.13/images/ubuntu/json                
INFO[1431] POST /v1.13/containers/create?name=nova-ee92d19e-e983-4cc9-b5a7-7a95beeb0304 
WARN[1431] Your kernel does not support swap limit capabilities, memory limited without swap. 
INFO[1431] POST /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/start 
INFO[1432] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1432] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1432] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1432] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1432] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1433] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1433] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1434] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1434] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1435] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1435] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1436] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1436] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1437] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1437] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1438] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1438] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1439] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1439] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1440] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1440] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1441] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1441] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1442] GET /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/json 
INFO[1442] POST /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00/kill 
INFO[1442] DELETE /v1.13/containers/2743670eaaaa3895973c90ec8cd58865bb8c1ebbba8e6c72edfb0ed0395a0b00?link=False&force=True&v=False 
INFO[1442] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1442] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1442] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1443] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1616] GET /v1.20/images/ubuntu/get                 
INFO[1628] GET /v1.20/images/ubuntu/get                 
INFO[1667] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1667] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1667] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1667] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1679] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1679] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1679] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1679] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1691] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1691] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1691] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1691] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1705] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1705] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1705] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1705] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1786] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1786] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1789] GET /v1.13/images/test/json                  
ERRO[1789] Handler for GET /images/{name:.*}/json returned error: No such image: test 
ERRO[1789] HTTP Error                                    err=No such image: test statusCode=404
INFO[1789] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1789] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1789] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1789] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[1866] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[1866] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
INFO[2031] GET /v1.20/containers/json                   
INFO[2482] GET /v1.13/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[2482] GET /v1.13/containers/0e2e93bb565965629957a2967a28ea0809291eb24dd1b528039c77dc9ef3d8fd/json 
root@nsj7:/var/log/upstart# 


operation on controller, image test is there.

root@nsj5:~# nova list
+--------------------------------------+------+--------+------------+-------------+----------+
| ID                                   | Name | Status | Task State | Power State | Networks |
+--------------------------------------+------+--------+------------+-------------+----------+
| 3261b9a0-3b88-4756-a56f-704a33524371 | d1   | ERROR  | spawning   | NOSTATE     |          |
+--------------------------------------+------+--------+------------+-------------+----------+

root@nsj5:~# glance image-list
+--------------------------------------+---------------------+-------------+------------------+-----------+--------+
| ID                                   | Name                | Disk Format | Container Format | Size      | Status |
+--------------------------------------+---------------------+-------------+------------------+-----------+--------+
| 8268aab9-882a-41b2-a355-06f688e2e118 | cirros              | raw         | docker           | 8092160   | active |
| 2b9f194d-196d-4d86-8c8d-6df549ad1b03 | cirros-0.3.4-x86_64 | qcow2       | bare             | 13287936  | active |
| d0106947-fe54-4419-b50b-da1cb48cc37a | nsj7                | raw         | docker           | 197479936 | active |
| 6b23c310-645c-4f8a-bad7-b5e3cf35e3ca | test                | raw         | docker           | 197479936 | active |
| a9fd41ac-45e9-4297-88af-3bafa0f17598 | ubuntu              | raw         | docker           | 197479936 | active |
| f0fc9ee8-5cab-42ff-aca2-ad9904223580 | ubuntu              | raw         | docker           | 197479936 | active |
| 29b6d938-673a-47fd-a2c4-f8496b9eeec0 | ubuntu              | raw         | docker           | 197479936 | active |
| 54087bf5-95a5-49b3-b34e-9fe2f04a8bf7 | ubuntu              | raw         | docker           | 197479936 | active |
+--------------------------------------+---------------------+-------------+------------------+-----------+--------+

```

**Comment by ibmalan** [comment]
How to solve this issue?any help will be great appreciate!

**Comment by shin-** [comment]
docker-py version?

**Comment by ibmalan** [comment]
I have solved the issue.

**Comment by cheneydc** [comment]
@ibmalan Hi, I got the same porblem, could you tell me how you fix it?

**Comment by ibmalan** [comment]
you need to make sure the both names are same when you saving docker image on compute node.

**Comment by cheneydc** [comment]
@ibmalan oh, you're right, thanks for your help :)
