### ISSUE TITLE
In python 2.6, the library is throwing error

### ISSUE THREAD

**Issue by rakesh-roshan** [docker/docker-py#758]
>>> import docker
>>> dc = docker.Client(base_url='unix://var/run/docker.sock')
>>> gobuilds_image_tag='12_23_12345'
>>> gobuilds_image_tag = 'rroshan-service:5000/rroshan/gobuilds:%s' % gobuilds_image_tag
>>> c = dc.create_container(image=gobuilds_image_tag, command='/bin/bash', detach=True, name='gobuilds_12345', stdin_open=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/toolchain/lin32/python-2.6.1/lib/python2.6/site-packages/docker/client.py", line 245, in create_container
  File "build/toolchain/lin32/python-2.6.1/lib/python2.6/site-packages/docker/client.py", line 253, in create_container_from_config
  File "build/toolchain/lin32/python-2.6.1/lib/python2.6/site-packages/docker/clientbase.py", line 108, in _result
  File "build/toolchain/lin32/python-2.6.1/lib/python2.6/site-packages/docker/clientbase.py", line 103, in _raise_for_status
docker.errors.NotFound: 404 Client Error: Not Found ("404 page not found")
>

While the same code works in python2.7.5

Docker Details:
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-108.el7.centos.x86_64
Go version (client): go1.4.2
Git commit (client): 3043001/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-108.el7.centos.x86_64
Go version (server): go1.4.2
Git commit (server): 3043001/1.7.1
OS/Arch (server): linux/amd64

Docker-Py Details:
Name: docker-py
Version: 1.3.1
Summary: Python client for Docker.

**Comment by rakesh-roshan** [comment]
With http url it worked. It is not working with an unix socket.

**Comment by shin-** [comment]
I wasn't able to reproduce, but I noticed you're using python 2.6.1 which is extremely outdated - can you try using 2.6.9 and see if you notice any difference?

**Comment by shin-** [comment]
No response in 1 month, closing. Feel free to reopen if you're still having this issue.
