### ISSUE TITLE
Create container bind volume with Unicode folder name

### ISSUE THREAD

**Issue by ColinHuang** [docker/docker-py#782]
If bind volume folder name is Unicode, for example Japanese, It will raise exception:
Host volume and container volume both should handle Unicode.

```
  File "/home/vagrant/.local/share/virtualenvs/qnap/local/lib/python2.7/site-packages/docker/utils/utils.py", line 461, in create_host_config
    host_config['Binds'] = convert_volume_binds(binds)
  File "/home/vagrant/.local/share/virtualenvs/qnap/local/lib/python2.7/site-packages/docker/utils/utils.py", line 208, in convert_volume_binds
    k, v['bind'], mode
```

**Comment by dnephin** [comment]
I suspect this is an issue in python2 (and not python3). Can you confirm?

**Comment by ColinHuang** [comment]
Yes, only in python 2.

Don't know how to make CI works for both python 2 and python 3. Need someone help.
https://github.com/docker/docker-py/pull/774

**Comment by shin-** [comment]
I'll take a look.

**Comment by shin-** [comment]
I tried to reproduce this issue but was unable to (tested with python 2.7 and 3.4). Here is the code I'm running.

```
# -*- coding: utf-8 -*-

from docker.utils import convert_volume_binds

data = {
    '/mnt/지연': {
        'bind': '/unicode/박',
        'mode': 'rw'
    }
}

print(convert_volume_binds(data) == ['/mnt/지연:/unicode/박:rw'])
```

@ColinHuang , can you provide a short example of code that fails. Also, the stacktrace you shared seems to be truncated, can you provide a full stacktrace so we can look deeper into that issue?

Thanks!

**Comment by ColinHuang** [comment]
```python
import docker

dc = docker.Client()

image = 'busybox'
host_config = dict()
create_args = dict()
host_config['binds'] = {
    u'/home/test/\u6e2c\u8a66\u6211\u662f\u4e2d\u6587': {
        u'bind': u'/a',
        u'ro': False
    }
}

create_args['host_config'] = docker.utils.create_host_config(
    binds=host_config.get('binds', None))

result = dc.create_container(image, **create_args)
```

Exception:
```text
Traceback (most recent call last):
  File "d.py", line 36, in <module>
    binds=host_config.get('binds', None))
  File "/home/vagrant/.local/share/virtualenvs/0923/local/lib/python2.7/site-packages/docker/utils/utils.py", line 461, in create_host_config
    host_config['Binds'] = convert_volume_binds(binds)
  File "/home/vagrant/.local/share/virtualenvs/0923/local/lib/python2.7/site-packages/docker/utils/utils.py", line 208, in convert_volume_binds
    k, v['bind'], mode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-16: ordinal not in range(128)

```

**Comment by shin-** [comment]
@ColinHuang Can you give the patch in #787 a try and confirm it fixes the issue for you? Thanks!

**Comment by ColinHuang** [comment]
It works well for #787. Thanks!
