### ISSUE TITLE
Handle floats for memory and swap limits

### ISSUE THREAD

**Issue by lots0logs** [docker/docker-py#813]
```
 build_pkg.build_pkg_handler() from build_queue
5f9134eb-9e13-4adc-80ea-115e86038811
Failed 29 minutes ago
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "./build_pkg.py", line 324, in build_pkg_handler
    build_result = build_pkgs(pkgobj)
  File "./build_pkg.py", line 637, in build_pkgs
    hconfig = docker_utils.create_pkgs_host_config(cache, pkgbuild_dir, result)
  File "./utils/docker_util.py", line 117, in create_pkgs_host_config
    }, privileged=True, cap_add=['ALL'], mem_limit='2.5G', memswap_limit='-1')
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 138, in create_host_config
    return utils.create_host_config(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 493, in create_host_config
    mem_limit = parse_bytes(mem_limit)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 459, in parse_bytes
    raise errors.DockerException(formatted_message)
DockerException: Failed converting the string value formemory (2.5) to a number.
```

**Comment by shin-** [comment]
We won't support float values after all, see rationale here https://github.com/docker/docker-py/pull/880#issuecomment-166335547
