### ISSUE TITLE
Could container create/start lead to an error?

### ISSUE THREAD

**Issue by yoanisgil** [docker/docker-py#857]
We have this internal tool for deploying our containers, the main script looks like this:

https://gist.github.com/yoanisgil/6277a17e1766b533b70d

We have been using it for some months now with Docker 1.8.x. Recently we decided to upgrade to Docker 1.9 and use Swarm 1.0.0 as well (yes too many changes at once ...). Given that the Swarm API is supposed to be nearly 100% with the Docker one, the deployment script is supposed to work. However I hit this bug from time to time and on what it seems to be a very random manner:

```
2015-11-20 10:08:07,180 - roll.single.deploy - INFO - Starting container 2b0e5d7e34402e145d73385b2711e11efa3ef945c561d90ff732f0bec27fea04
None None
Traceback (most recent call last):
  File "./single-roll", line 44, in <module>
    deploy.run()
  File "/home/ygil/dev/docker-roll/roll/single/deploy.py", line 111, in run
    self.client.start(new_container.get('Id'))
  File "/home/ygil/.envs/docker-roll/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ygil/.envs/docker-roll/lib/python2.7/site-packages/docker/api/container.py", line 344, in start
    self._raise_for_status(res)
  File "/home/ygil/.envs/docker-roll/lib/python2.7/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot start container 2b0e5d7e34402e145d73385b2711e11efa3ef945c561d90ff732f0bec27fea04: [8] System error: open /sys/fs/cgroup/devices/system.slice/docker-2b0e5d7e34402e145d73385b2711e11efa3ef945c561d90ff732f0bec27fea04.scope/cgroup.procs: no such file or directory")
```

We run the script like this:

```bash
SLEEP=0 DOCKER_HOST='tcp://aws034:2375' ./single-roll docker-roll-config.yml crakmedia/crakrevenue-affiliate:5.10.1
```
where `tcp://aws034:2375` is the address of the Swarm manager. I do get the same error if I point directly to a cluster node.

The reason I ask here first, is because I was wondering if the fact that it takes two API calls to actually get a container running (create then start), might lead to such an error.

Here is some context information:

Pip
============

```bash
pip list
coverage (3.7.1)
docker-py (1.5.0)
docker-roll (0.0.5)
nose (1.3.7)
pip (7.1.2)
pyaml (15.6.3)
python-consul (0.4.2)
PyYAML (3.11)
requests (2.8.1)
setuptools (18.0.1)
six (1.10.0)
websocket-client (0.32.0)
wheel (0.24.0)
```

Swarm
============

```bash
$ docker info
Containers: 3
Images: 30
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 aws038.crakmedia.lan: 10.1.8.52:2375
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 7.892 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.20.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
 aws074.crakmedia.lan: 10.1.8.42:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.16 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.4.2.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
CPUs: 8
Total Memory: 24.05 GiB
Name: a3eb26954e24
```

```bash
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:10:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:
 OS/Arch:      linux/amd64
````

Swarm Node
================

```bash
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```

```bash
$ docker info
Containers: 1
Images: 455
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-135349446-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.42 GB
 Data Space Total: 107.4 GB
 Data Space Available: 34.09 GB
 Metadata Space Used: 18.35 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 15.39 GiB
Name: aws074.crakmedia.lan
ID: 63ON:R2QD:GYJ2:EVJX:YMZ7:HH5Q:Y6TB:C745:MJUS:MZXB:BAYB:QR4M
Username: yoanisgil
Registry: https://index.docker.io/v1/
```

**Comment by shin-** [comment]
Hm, the separation between `create` and `start` has always been there, and it certainly is the same in swarm as well.

This looks like a swarm issue to me. @vieux @aluzzardi ?

**Comment by yoanisgil** [comment]
@shin- whether I go through swarm or docker I get the same error. However I've been trying to narrowing down a bit more and it turns out I do not have the same issue with Docker 1.8.3. So I think we should close this a file a new issue on the docker project.

**Comment by shin-** [comment]
Yup, if that's the case, you should create an issue on [docker/docker](https://github.com/docker/docker) :)
