### ISSUE TITLE
Problems with Python3

### ISSUE THREAD

**Issue by yncxcw** [docker/docker-py#878]
It works well with Python but I have some issues with python3.  I just executed containers API
by cl.containers() get the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/docker/client.py", line 138, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.21/containers/json?limit=-1&size=0&all=1&trunc_cmd=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/docker/api/container.py", line 68, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python3.4/dist-packages/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.4/dist-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'client is newer than server (client API version: 1.21, server API version: 1.20)'")

**Comment by shin-** [comment]
> Bad Request ("b'client is newer than server (client API version: 1.21, server API version: 1.20)'")

Try initializing your client with `c = docker.Client(version='1.20')` - you're probably seeing a difference because your docker-py version is not the same in python2 and python3.

**Comment by yncxcw** [comment]
works fine for me,  thanks!

**Comment by prabhakar-pal** [comment]
For later versions of docker-py , you would need to do this

client = docker.DockerClient(version='1.20')
