### ISSUE TITLE
Doesn't work with special chars in path

### ISSUE THREAD

**Issue by ostrolucky** [docker/docker-py#903]
Not working:

``` bash
Správca@gadelat-pc MINGW64 ~/Documents/feed/docker2 (stats)
$ pwd
/c/Users/Správca/Documents/feed/docker2

Správca@gadelat-pc MINGW64 ~/Documents/feed/docker2 (stats)
$ docker-compose build
Building adminer
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 54, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_disp     atch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 171, in perform_command
  File "C:\projects\compose\compose\cli\main.py", line 192, in build
  File "C:\projects\compose\compose\project.py", line 235, in build
  File "C:\projects\compose\compose\service.py", line 683, in build
  File "c:\projects\compose\venv\lib\site-packages\docker\api\build.py", line 41     , in build
TypeError: You must specify a directory to build in path
docker-compose returned -1
```

After copying, this issue no longer exists (another problem occured, but that's another issue I guess):

``` bash
Správca@gadelat-pc MINGW64 /c/Downloads/feed/docker2 (stats)
$ pwd
/c/Downloads/feed/docker2

Správca@gadelat-pc MINGW64 /c/Downloads/feed/docker2 (stats)
$ docker-compose build
Building adminer
Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```

**Comment by gadelat** [comment]
I believe second problem is same culprit.
```bash
Správca@gadelat-pc MINGW64 /c/Downloads/feed/docker2 (stats)
$ docker-compose --verbose build
compose.config.config.find: Using configuration files: .\docker-compose.yml
Traceback (most recent call last):
  File "c:\python27-x64\Lib\logging\__init__.py", line 859, in emit
  File "c:\python27-x64\Lib\logging\__init__.py", line 732, in format
  File "c:\python27-x64\Lib\logging\__init__.py", line 474, in format
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 19: ordinal not in range(128)
Logged from file auth.py, line 147
docker.auth.auth.load_config: File doesn't exist
Traceback (most recent call last):
  File "c:\python27-x64\Lib\logging\__init__.py", line 859, in emit
  File "c:\python27-x64\Lib\logging\__init__.py", line 732, in format
  File "c:\python27-x64\Lib\logging\__init__.py", line 474, in format
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 19: ordinal not in range(128)
Logged from file auth.py, line 170
docker.auth.auth.load_config: File doesn't exist - returning empty config
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 54, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 169, in perform_command
  File "C:\projects\compose\compose\cli\command.py", line 53, in project_from_options
  File "C:\projects\compose\compose\cli\command.py", line 89, in get_project
  File "C:\projects\compose\compose\cli\command.py", line 72, in get_client
  File "c:\projects\compose\venv\lib\site-packages\docker\api\daemon.py", line 78, in version
  File "c:\projects\compose\venv\lib\site-packages\docker\client.py", line 110, in _get
  File "c:\projects\compose\venv\lib\site-packages\requests\sessions.py", line 477, in get
  File "c:\projects\compose\venv\lib\site-packages\requests\sessions.py", line 465, in request
  File "c:\projects\compose\venv\lib\site-packages\requests\sessions.py", line 573, in send
  File "c:\projects\compose\venv\lib\site-packages\requests\adapters.py", line 415, in send
requests.exceptions.ConnectionError: ('Connection aborted.', error(10061, 'Nedalo sa vytvori\x9d \x9eiadne spojenie, preto\x9ee cie\xbeov\xfd po\xe8\xedta\xe8 ho akt\xedvne odmietol'))
docker-compose returned -1
```
Also this:
```bash
$ eval "$(docker-machine env default)"
bash: $'\302\203eval': command not found
```
I think this is because docker toolbox saves everything to user directory - and it's name is in my case with diacritic. This issue doesn't occur when I create new windows user profile without diacritic and install there docker toolbox again.

**Comment by shin-** [comment]
What are the contents of your compose file? Specifically for the `adminer` service?

**Comment by gadelat** [comment]
```
adminer:
    build: images/adminer
    restart: always
    ports:
        - "8012:80"
```
images/adminer:
```
FROM clue/adminer
```

**Comment by shin-** [comment]
I'm not able to reproduce the issue:
```
aやよい$ docker-compose build
Building adminer
Step 1 : FROM clue/adminer
 ---> ea11c9f031e5
Successfully built ea11c9f031e5
```

Do you still encounter the same issue with docker-compose 1.6.0?

**Comment by gadelat** [comment]
Your output isn't from windows terminal as mine is. Also, you didn't show output of pwd. In my output it's clear that my home directory is with diacritic. In yours, it's not clear if that's home. I don't think so.

I have access to windows pc like... once a month.

**Comment by osaris** [comment]
After hours of tests I have finally found this thread which looks to be exactly my problem :

```
Raphaël@X1YOGA MINGW64 ~/Projets/docker/lamp
$ docker-compose up
Building lamp
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 56, in main
  File "compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "compose\cli\docopt_command.py", line 26, in dispatch
  File "compose\cli\main.py", line 191, in perform_command
  File "compose\cli\main.py", line 657, in up
  File "compose\project.py", line 318, in up
  File "compose\service.py", line 351, in execute_convergence_plan
  File "compose\service.py", line 252, in create_container
  File "compose\service.py", line 275, in ensure_image_exists
  File "compose\service.py", line 679, in build
  File "site-packages\docker\api\build.py", line 42, in build
TypeError: You must specify a directory to build in path
docker-compose returned -1

Raphaël@X1YOGA MINGW64 ~/Projets/docker/lamp
$ pwd
/c/Users/Raphaël/Projets/docker/lamp

Raphaël@X1YOGA MINGW64 ~/Projets/docker/lamp
$ docker-compose -v
docker-compose version 1.6.2, build e80fc83
```

**Comment by osaris** [comment]
I changed my account folder to ```C:\Raphael``` and it works.

**Comment by ostrolucky** [comment]
It isn't.
```
C:\Users\Šarlatán
λ docker-compose build
Building adminer
ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)

C:\Users\Šarlatán
```


Reopen please, thx.

**Comment by shin-** [comment]
Fixed in 1.22.0: https://github.com/docker/compose/issues/5998

What version of Compose / docker-py are you running?

**Comment by shin-** [comment]
Hmm, I've tried to reproduce on Windows with the same user name, but this still works fine for me:

```
PS C:\Users\Šarlatán\Documents\feed\docker2> docker-compose version
docker-compose version 1.23.1, build b02f130
docker-py version: 3.5.1
CPython version: 3.7.1
OpenSSL version: OpenSSL 1.1.0i  14 Aug 2018
PS C:\Users\Šarlatán\Documents\feed\docker2> docker-compose build
Building adminer
Step 1/1 : FROM docker4w/nsenter-dockerd
 ---> cae870735e91
Successfully built cae870735e91
Successfully tagged docker2_adminer:latest
```

With Compose file:
```yaml
version: '2'
services:
  adminer:
    build: images/adminer
    ports:
      - 8012:80
    restart: always
```

I have a few questions if we want to figure this out:

- Please post the full output of the `docker-compose version` command
- What terminal program are you using? Is it git-bash, Cygwin, something else?
  - Does it change anything if you run Compose from Powershell instead?
- What version of Windows are you running on?
- How did you install Docker? (`docker-machine` or Toolbox, Docker Desktop for Windows, other?)
- How did you install `docker-compose`?
  - If installed through `pip`, what version of Python are you running on? 
  - If installed through `pip`, does the [binary package](https://github.com/docker/compose/releases/tag/1.23.1) exhibit the same issue?

**Comment by ostrolucky** [comment]
```
C:\Users\Šarlatán>docker-compose version
docker-compose version 1.23.0, build c8524dc1
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

C:\Users\Šarlatán>docker-compose build
ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)
```

> terminal program
> Does it change anything if you run Compose from Powershell instead

Reproducible in any. Tried cmd.exe, powershell, ConEmu

> version of Windows

Last one I tried this is Windows 10 64bit, version 1803, build 17134.345, running in Virtualbox VM. I know docker won't work there, this is only to confirm this issue has been fixed.

> How did you install Docker, docker-compose?

I use [chocolatey](https://chocolatey.org/), install via `choco install docker-compose`

**Comment by shin-** [comment]
> Last one I tried this is Windows 10 64bit, version 1803, build 17134.345, running in Virtualbox VM. I know docker won't work there, this is only to confirm this issue has been fixed.

Oh, if Docker isn't running, then the error you're seeing is normal and expected (it's not a great error message [but we're getting that fixed soon](https://github.com/docker/compose/pull/6244))

All in all, I'm pretty confident it's been fixed, but please confirm on a machine running Docker so I can close this!

**Comment by ostrolucky** [comment]
Ah ok that makes sense. I'm not going to have access to windows machine for a while so I think we can close it until someone here will report this again.

What might have been the issue anyway that that you are confident this is fixed?
