### ISSUE TITLE
Test Failure in 1.6 and 1.7

### ISSUE THREAD

**Issue by alunduil** [docker/docker-py#904]
While packaging applications, I like to run the test suite (usually just unit depending on the integration points) to verify that I've got the packaging correct.  Since 1.6 this has resulted in a failure (coming from pytest for some reason and shown below).  The invocation seems to be pretty standard but I was hoping someone could shed some light on why this would be happening with the recent versions of docker-py.

```
pytest tests/unit
```

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/py.test", line 9, in <module>
    load_entry_point('pytest==2.7.2', 'console_scripts', 'py.test')()
  File "/usr/lib64/python2.7/site-packages/_pytest/config.py", line 41, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib64/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/usr/lib64/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 116, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 96, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/usr/lib64/python2.7/site-packages/_pytest/config.py", line 654, in notify_exception
    excinfo=excinfo)
  File "/usr/lib64/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/usr/lib64/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/usr/lib64/python2.7/site-packages/_pytest/terminal.py", line 162, in pytest_internalerror
    self.write_line("INTERNALERROR> " + line)
  File "/usr/lib64/python2.7/site-packages/_pytest/terminal.py", line 144, in write_line
    self._tw.line(line, **markup)
  File "/usr/lib64/python2.7/site-packages/py/_io/terminalwriter.py", line 201, in line
    self.write(s, **kw)
  File "/usr/lib64/python2.7/site-packages/py/_io/terminalwriter.py", line 198, in write
    write_out(self._file, markupmsg)
  File "/usr/lib64/python2.7/site-packages/py/_io/terminalwriter.py", line 348, in write_out
    fil.flush()
IOError: [Errno 32] Broken pipe
```

**Comment by TomasTomecek** [comment]
Fedora packager here. Unit tests for 1.6 pass just fine for us: https://kojipkgs.fedoraproject.org//packages/python-docker-py/1.6.0/2.fc24/data/logs/noarch/build.log

Am trying 1.7 now.

**Comment by shin-** [comment]
CI behaves properly and the tests run locally for the team as well, so I have no idea where this could be coming from. The stacktrace provided doesn't reference any of our code either.

**Comment by shin-** [comment]
Feel free to reopen if reproduction info can be provided.
